# System Monitor
# Run: make run

OVELC = ../../target/debug/ovelc
NCURSES = /opt/homebrew/opt/ncurses

all: sysmon

sysmon.c: sysmon.ov
	$(OVELC) -rewrite-ovel sysmon.ov -o sysmon.c -fno-ovel-arc

sysmon: sysmon.c
	clang -std=c99 -fblocks \
		-I ../../include -I ../../include/Foundation -I ../../include/Terminal \
		-I $(NCURSES)/include \
		sysmon.c \
		../../include/ovel/runtime.c \
		../../include/Terminal/ncurses_mouse.c \
		../../include/Terminal/sysinfo.c \
		$(NCURSES)/lib/libncurses.dylib \
		-Wl,-rpath,$(NCURSES)/lib \
		-o sysmon -w

run: sysmon
	./sysmon

clean:
	rm -f sysmon.c sysmon

.PHONY: all run clean