// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"


#include <string.h>

struct nopa_NFObject_vtable;
struct nopa_Person_vtable;

#define nopa_NFObject_vtable_index_init 2
#define nopa_NFObject_vtable_index_dealloc 3

static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nopa_sel_name = {.name = "name", .hash = 0x8D39BDE6};
static const SEL __nopa_sel_age = {.name = "age", .hash = 0x2C41499C};

typedef struct NFObject NFObject;
typedef struct Person Person;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
char * Person_name(NFObject * self, SEL _cmd);
void Person_setName_(NFObject * self, SEL _cmd, char * value);
int Person_age(NFObject * self, SEL _cmd);
void Person_setAge_(NFObject * self, SEL _cmd, int value);
NFClass * Person_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass nopa_NFObject_class;
extern NFClass nopa_Person_class;
void nopa_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct nopa_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct nopa_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct Person {
    struct NFClass *isa;
    uint32_t retain_count;
    char * _name;
    int _age;
};
typedef struct Person Person;
struct nopa_Person_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    char * (*name)(NFObject *, SEL);
    void (*setName_)(NFObject *, SEL, char *);
    int (*age)(NFObject *, SEL);
    void (*setAge_)(NFObject *, SEL, int);
};
struct nopa_Person_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return nopa_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = nopa_alloc(self);
    return nopa_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return nopa_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &nopa_NFObject_class;
}

NFObject * nopa_alloc(struct NFClass * cls);
NFObject * nopa_init(NFObject * );
char * Person_name(NFObject * self, SEL _cmd) {
    return ((struct Person *)(self))->_name;
}

void Person_setName_(NFObject * self, SEL _cmd, char * value) {
    ((struct Person *)(self))->_name = value;
}

int Person_age(NFObject * self, SEL _cmd) {
    return ((struct Person *)(self))->_age;
}

void Person_setAge_(NFObject * self, SEL _cmd, int value) {
    ((struct Person *)(self))->_age = value;
}

NFClass * Person_getClass(NFClass * self, SEL _cmd) {
    return &nopa_Person_class;
}

int main() {
    nopa_autoreleasepool_t *__pool = nopa_autoreleasepool_push();
    nopa_meta_init();
    NFObject *__nopa_tmp_0 = (NFObject_alloc(&nopa_Person_class, __nopa_sel_alloc));
    Person * p = ((struct nopa_NFObject_vtable *)__nopa_tmp_0->isa->vtable)->init(__nopa_tmp_0, __nopa_sel_init);
    p->_name = "Alice";
    p->_age = 30;
    printf("%s is %d years old\n", ((struct nopa_Person_vtable *)p->isa->vtable)->name(p, __nopa_sel_name), ((struct nopa_Person_vtable *)p->isa->vtable)->age(p, __nopa_sel_age));
    return 0;
    nopa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nopa_NFObject_vtable nopa_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct nopa_Person_vtable nopa_Person_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .name = Person_name,
    .setName_ = Person_setName_,
    .age = Person_age,
    .setAge_ = Person_setAge_,
};

struct nopa_NFObject_meta_vtable nopa_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct nopa_Person_meta_vtable nopa_Person_meta_vtable_inst = {
    .class = Person_getClass,
};

NFClass nopa_NFObject_class;
NFClass nopa_Person_class;

void nopa_meta_init(void) {
    nopa_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &nopa_NFObject_vtable_inst,
        .class_vtable = &nopa_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Person_class = (NFClass){
        .name = "Person",
        .superclass = &nopa_NFObject_class,
        .instance_size = sizeof(struct Person),
        .vtable = &nopa_Person_vtable_inst,
        .class_vtable = &nopa_Person_meta_vtable_inst,
        .protocol_count = 0,
    };
}
