// Generated by nepac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nepa/runtime.h"


#include <string.h>

struct nepa_NPObject_vtable;
struct nepa_Box_vtable;

#define nepa_NPObject_vtable_index_init 2
#define nepa_NPObject_vtable_index_dealloc 3
#define nepa_Box_vtable_index_size 4
#define nepa_Box_vtable_index_setSize_ 5

static const SEL __nepa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nepa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nepa_sel_setSize_ = {.name = "setSize_", .hash = 0x74BDCB47};
static const SEL __nepa_sel_size = {.name = "size", .hash = 0x23A0D95C};

typedef struct NPObject NPObject;
typedef struct Box Box;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
int Box_size(NPObject * self, SEL _cmd);
void Box_setSize_(NPObject * self, SEL _cmd, int s);
NPClass * Box_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nepa_NPObject_class;
extern NPClass nepa_Box_class;
void nepa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nepa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nepa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Box {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct Box Box;
struct nepa_Box_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    int (*size)(NPObject *, SEL);
    void (*setSize_)(NPObject *, SEL, int);
};
struct nepa_Box_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nepa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nepa_alloc(self);
    return nepa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nepa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nepa_NPObject_class;
}

NPObject * nepa_alloc(struct NPClass * cls);
NPObject * nepa_init(NPObject * );
int Box_size(NPObject * self, SEL _cmd) {
    struct Box * _self = ((struct Box *)(self));
    {
        return 99;
    }
}

void Box_setSize_(NPObject * self, SEL _cmd, int s) {
    struct Box * _self = ((struct Box *)(self));
    {
        printf("setSize called with %d\n", s);
    }
}

NPClass * Box_getClass(NPClass * self, SEL _cmd) {
    return &nepa_Box_class;
}

int main() {
    nepa_autoreleasepool_t *__pool = nepa_autoreleasepool_push();
    nepa_meta_init();
    NPObject *__nepa_tmp_0 = (NPObject_alloc(&nepa_Box_class, __nepa_sel_alloc));
    Box * b = ((struct nepa_NPObject_vtable *)__nepa_tmp_0->isa->vtable)->init(__nepa_tmp_0, __nepa_sel_init);
    ((struct nepa_Box_vtable *)b->isa->vtable)->setSize_(b, __nepa_sel_setSize_, 42);
    printf("Size: %d\n", ((struct nepa_Box_vtable *)b->isa->vtable)->size(b, __nepa_sel_size));
    return 0;
    nepa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nepa_NPObject_vtable nepa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nepa_Box_vtable nepa_Box_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .size = Box_size,
    .setSize_ = Box_setSize_,
};

struct nepa_NPObject_meta_vtable nepa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nepa_Box_meta_vtable nepa_Box_meta_vtable_inst = {
    .class = Box_getClass,
};

NPClass nepa_NPObject_class;
NPClass nepa_Box_class;

void nepa_meta_init(void) {
    nepa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nepa_NPObject_vtable_inst,
        .class_vtable = &nepa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nepa_Box_class = (NPClass){
        .name = "Box",
        .superclass = &nepa_NPObject_class,
        .instance_size = sizeof(struct Box),
        .vtable = &nepa_Box_vtable_inst,
        .class_vtable = &nepa_Box_meta_vtable_inst,
        .protocol_count = 0,
    };
}
