[package]
name = "nopac"
version = "0.1.0"
edition = "2021"

[dependencies]
nopa-cst = { path = "../cst" }
nopa-parser = { path = "../parser" }
nopa-binder = { path = "../binder" }
nopa-elaborator = { path = "../elaborator" }
nopa-codegen = { path = "../codegen" }
nopa-preprocessor = { path = "../preprocessor" }
nopa-symbol = { path = "../symbol" }
nopa-ast = { path = "../ast" }
nopa-cfg = { path = "../cfg" }
nopa-arc = { path = "../arc" }
nopa-async = { path = "../async" }
nopa-eh = { path = "../eh" }
nopa-defer = { path = "../defer" }
nopa-pattern = { path = "../pattern" }
nopa-trace = { path = "../trace" }
nopa-checker = { path = "../checker" }
attrs = { path = "../attrs" }
clap = "4.6.6"
clap_complete = "4.6.9"

[build-dependencies]
cc = "1.0"
