// Generated by nepac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nepa/runtime.h"


#include <string.h>

struct nepa_NPObject_vtable;
struct nepa_Widget_vtable;

#define nepa_NPObject_vtable_index_init 2
#define nepa_NPObject_vtable_index_dealloc 3
#define nepa_Widget_vtable_index_initWithValue_ 4

static const SEL __nepa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nepa_sel_initWithValue_ = {.name = "initWithValue_", .hash = 0xF0E5A305};
static const SEL __nepa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};

typedef struct NPObject NPObject;
typedef struct Widget Widget;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * Widget_initWithValue_(NPObject * self, SEL _cmd, int v);
NPClass * Widget_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nepa_NPObject_class;
extern NPClass nepa_Widget_class;
void nepa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nepa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nepa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Widget {
    struct NPClass *isa;
    uint32_t retain_count;
    int value;
};
typedef struct Widget Widget;
struct nepa_Widget_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithValue_)(NPObject *, SEL, int);
};
struct nepa_Widget_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nepa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nepa_alloc(self);
    return nepa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nepa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nepa_NPObject_class;
}

NPObject * nepa_alloc(struct NPClass * cls);
NPObject * nepa_init(NPObject * );
NPObject * Widget_initWithValue_(NPObject * self, SEL _cmd, int v) {
    struct Widget * _self = ((struct Widget *)(self));
    {
        self = NPObject_init(self, __nepa_sel_init);
        if (self) {
            ((struct Widget *)(self))->value = v;
        }
        return self;
    }
}

NPClass * Widget_getClass(NPClass * self, SEL _cmd) {
    return &nepa_Widget_class;
}

int main() {
    nepa_autoreleasepool_t *__pool = nepa_autoreleasepool_push();
    nepa_meta_init();
    {
        nepa_autoreleasepool_t * __pool = nepa_autoreleasepool_push();
        {
            NPObject *__nepa_tmp_0 = (NPObject_alloc(&nepa_Widget_class, __nepa_sel_alloc));
            Widget * w = ((struct nepa_Widget_vtable *)__nepa_tmp_0->isa->vtable)->initWithValue_(__nepa_tmp_0, __nepa_sel_initWithValue_, 42);
            printf("widget value: %d\n", ((struct Widget *)(w))->value);
            nepa_release(w);
        }
        nepa_autoreleasepool_pop(__pool);
    }
    printf("alloc-init chain OK\n");
    return 0;
    nepa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nepa_NPObject_vtable nepa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nepa_Widget_vtable nepa_Widget_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithValue_ = Widget_initWithValue_,
};

struct nepa_NPObject_meta_vtable nepa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nepa_Widget_meta_vtable nepa_Widget_meta_vtable_inst = {
    .class = Widget_getClass,
};

NPClass nepa_NPObject_class;
NPClass nepa_Widget_class;

void nepa_meta_init(void) {
    nepa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nepa_NPObject_vtable_inst,
        .class_vtable = &nepa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nepa_Widget_class = (NPClass){
        .name = "Widget",
        .superclass = &nepa_NPObject_class,
        .instance_size = sizeof(struct Widget),
        .vtable = &nepa_Widget_vtable_inst,
        .class_vtable = &nepa_Widget_meta_vtable_inst,
        .protocol_count = 0,
    };
}
