// Generated by jetic
#import <stdio.h>
#import <stdlib.h>
#import <string.h>
#import <time.h>
#include <stdint.h>
#include <stddef.h>
#include "jeti/runtime.h"


#include <string.h>

struct jeti_NPObject_vtable;
struct jeti_StreamCipher_vtable;
struct jeti_SecurityAuditor_vtable;
struct jeti_UtilityBase_vtable;

#define jeti_NPObject_vtable_index_init 2
#define jeti_NPObject_vtable_index_dealloc 3
#define jeti_StreamCipher_vtable_index_initWithName_key_ 8
#define jeti_StreamCipher_vtable_index_performDiagnostic 9
#define jeti_StreamCipher_vtable_index_transformData_ 10
#define jeti_StreamCipher_vtable_index_dealloc 3
#define jeti_SecurityAuditor_vtable_index_initWithId_target_ 4
#define jeti_SecurityAuditor_vtable_index_auditTargetStatus 5
#define jeti_SecurityAuditor_vtable_index_dealloc 3
#define jeti_UtilityBase_vtable_index_initWithName_version_ 4
#define jeti_UtilityBase_vtable_index_printBanner 5
#define jeti_UtilityBase_vtable_index_refreshInternalToken 6
#define jeti_UtilityBase_vtable_index_runQuickSanityCheck 7
#define jeti_UtilityBase_vtable_index_dealloc 3

static const SEL __jeti_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __jeti_sel_refreshInternalToken = {.name = "refreshInternalToken", .hash = 0x977FDCAA};
static const SEL __jeti_sel_initWithName_version_ = {.name = "initWithName_version_", .hash = 0xC52B8940};
static const SEL __jeti_sel_printBanner = {.name = "printBanner", .hash = 0xAD058FC6};
static const SEL __jeti_sel_utilityName = {.name = "utilityName", .hash = 0x48E6157C};
static const SEL __jeti_sel_initWithId_target_ = {.name = "initWithId_target_", .hash = 0xC5DFD343};
static const SEL __jeti_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __jeti_sel_initWithName_key_ = {.name = "initWithName_key_", .hash = 0x2CC3BF61};
static const SEL __jeti_sel_setMonitoredCipher_ = {.name = "setMonitoredCipher_", .hash = 0x40E88D7A};
static const SEL __jeti_sel_performDiagnostic = {.name = "performDiagnostic", .hash = 0xE4AA559D};
static const SEL __jeti_sel_runQuickSanityCheck = {.name = "runQuickSanityCheck", .hash = 0xE350FC45};
static const SEL __jeti_sel_keyLength = {.name = "keyLength", .hash = 0x6B44CD00};
static const SEL __jeti_sel_transformData_ = {.name = "transformData_", .hash = 0x30825EB4};
static const SEL __jeti_sel_auditTargetStatus = {.name = "auditTargetStatus", .hash = 0x6639C973};

typedef struct NPObject NPObject;
typedef struct StreamCipher StreamCipher;
typedef struct SecurityAuditor SecurityAuditor;
typedef struct UtilityBase UtilityBase;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * StreamCipher_initWithName_key_(NPObject * self, SEL _cmd, char * name, char * key);
void StreamCipher_performDiagnostic(NPObject * self, SEL _cmd);
char * StreamCipher_transformData_(NPObject * self, SEL _cmd, char * input);
void StreamCipher_dealloc(NPObject * self, SEL _cmd);
int StreamCipher_keyLength(NPObject * self, SEL _cmd);
void StreamCipher_setKeyLength_(NPObject * self, SEL _cmd, int value);
NPClass * StreamCipher_getClass(NPClass * self, SEL _cmd);
NPObject * SecurityAuditor_initWithId_target_(NPObject * self, SEL _cmd, char * auditorId, StreamCipher * target);
void SecurityAuditor_auditTargetStatus(NPObject * self, SEL _cmd);
void SecurityAuditor_dealloc(NPObject * self, SEL _cmd);
char * SecurityAuditor_auditorId(NPObject * self, SEL _cmd);
void SecurityAuditor_setAuditorId_(NPObject * self, SEL _cmd, char * value);
StreamCipher * SecurityAuditor_monitoredCipher(NPObject * self, SEL _cmd);
void SecurityAuditor_setMonitoredCipher_(NPObject * self, SEL _cmd, StreamCipher * value);
NPClass * SecurityAuditor_getClass(NPClass * self, SEL _cmd);
NPObject * UtilityBase_initWithName_version_(NPObject * self, SEL _cmd, char * name, int ver);
void UtilityBase_printBanner(NPObject * self, SEL _cmd);
void UtilityBase_refreshInternalToken(NPObject * self, SEL _cmd);
void UtilityBase_runQuickSanityCheck(NPObject * self, SEL _cmd);
void UtilityBase_dealloc(NPObject * self, SEL _cmd);
char * UtilityBase_utilityName(NPObject * self, SEL _cmd);
void UtilityBase_setUtilityName_(NPObject * self, SEL _cmd, char * value);
int UtilityBase_versionMajor(NPObject * self, SEL _cmd);
void UtilityBase_setVersionMajor_(NPObject * self, SEL _cmd, int value);
NPClass * UtilityBase_getClass(NPClass * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NPClass jeti_NPObject_class;
extern NPClass jeti_StreamCipher_class;
extern NPClass jeti_SecurityAuditor_class;
extern NPClass jeti_UtilityBase_class;
void jeti_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct jeti_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct jeti_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct StreamCipher {
    struct NPClass *isa;
    uint32_t retain_count;
    char * _utilityName;
    int _versionMajor;
    int _securityToken;
    char _cipherKey[32];
    int _keyLength;
};
typedef struct StreamCipher StreamCipher;
struct jeti_StreamCipher_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithName_version_)(NPObject *, SEL, char *, int);
    void (*printBanner)(NPObject *, SEL);
    void (*refreshInternalToken)(NPObject *, SEL);
    void (*runQuickSanityCheck)(NPObject *, SEL);
    char * (*utilityName)(NPObject *, SEL);
    void (*setUtilityName_)(NPObject *, SEL, char *);
    int (*versionMajor)(NPObject *, SEL);
    void (*setVersionMajor_)(NPObject *, SEL, int);
    NPObject * (*initWithName_key_)(NPObject *, SEL, char *, char *);
    void (*performDiagnostic)(NPObject *, SEL);
    char * (*transformData_)(NPObject *, SEL, char *);
    int (*keyLength)(NPObject *, SEL);
    void (*setKeyLength_)(NPObject *, SEL, int);
};
struct jeti_StreamCipher_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct SecurityAuditor {
    struct NPClass *isa;
    uint32_t retain_count;
    char * _auditorId;
    StreamCipher * _monitoredCipher;
};
typedef struct SecurityAuditor SecurityAuditor;
struct jeti_SecurityAuditor_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithId_target_)(NPObject *, SEL, char *, StreamCipher *);
    void (*auditTargetStatus)(NPObject *, SEL);
    char * (*auditorId)(NPObject *, SEL);
    void (*setAuditorId_)(NPObject *, SEL, char *);
    StreamCipher * (*monitoredCipher)(NPObject *, SEL);
    void (*setMonitoredCipher_)(NPObject *, SEL, StreamCipher *);
};
struct jeti_SecurityAuditor_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct UtilityBase {
    struct NPClass *isa;
    uint32_t retain_count;
    char * _utilityName;
    int _versionMajor;
    int _securityToken;
};
typedef struct UtilityBase UtilityBase;
struct jeti_UtilityBase_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithName_version_)(NPObject *, SEL, char *, int);
    void (*printBanner)(NPObject *, SEL);
    void (*refreshInternalToken)(NPObject *, SEL);
    void (*runQuickSanityCheck)(NPObject *, SEL);
    char * (*utilityName)(NPObject *, SEL);
    void (*setUtilityName_)(NPObject *, SEL, char *);
    int (*versionMajor)(NPObject *, SEL);
    void (*setVersionMajor_)(NPObject *, SEL, int);
};
struct jeti_UtilityBase_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return jeti_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = jeti_alloc(self);
    return jeti_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return jeti_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &jeti_NPObject_class;
}

NPObject * jeti_alloc(struct NPClass * cls);
NPObject * jeti_init(NPObject * );
NPObject * StreamCipher_initWithName_key_(NPObject * self, SEL _cmd, char * name, char * key) {
    struct StreamCipher * _self = ((struct StreamCipher *)(self));
    {
        self = UtilityBase_initWithName_version_(self, __jeti_sel_initWithName_version_, name, 3);
        if (self) {
            {
                ((struct StreamCipher *)(self))->_keyLength = strlen(key);
                if (((struct StreamCipher *)(self))->_keyLength > 31) {
                    ((struct StreamCipher *)(self))->_keyLength = 31;
                }
                for (int i = 0; i < 32; i++) {
                    {
                        if (i < ((struct StreamCipher *)(self))->_keyLength) {
                            {
                                ((struct StreamCipher *)(self))->_cipherKey[i] = key[i];
                            }
                        } else {
                            {
                                ((struct StreamCipher *)(self))->_cipherKey[i] = 0;
                            }
                        }
                    }
                }
            }
        }
        return self;
    }
}

void StreamCipher_performDiagnostic(NPObject * self, SEL _cmd) {
    struct StreamCipher * _self = ((struct StreamCipher *)(self));
    {
        ((struct jeti_UtilityBase_vtable *)self->isa->vtable)->printBanner(self, __jeti_sel_printBanner);
        printf(" ℹ️ [诊断反馈] 加密密钥长度: %-3d 字节 | 流引擎状态: 活跃\n", ((struct StreamCipher *)(self))->_keyLength);
    }
}

char * StreamCipher_transformData_(NPObject * self, SEL _cmd, char * input) {
    struct StreamCipher * _self = ((struct StreamCipher *)(self));
    {
        int inputLen = strlen(input);
        char * output = ((char *)(malloc(inputLen + 1)));
        for (int i = 0; i < inputLen; i++) {
            {
                output[i] = input[i] ^ ((struct StreamCipher *)(self))->_cipherKey[i % ((struct StreamCipher *)(self))->_keyLength];
                if (output[i] == 0) {
                    output[i] = 126;
                }
            }
        }
        output[inputLen] = 0;
        return output;
    }
}

void StreamCipher_dealloc(NPObject * self, SEL _cmd) {
    struct StreamCipher * _self = ((struct StreamCipher *)(self));
    {
        printf(" 🗑️ [生命周期] 加密流处理器 [%s] 彻底从系统内核卸载。\n", ((struct UtilityBase *)(((UtilityBase *)(self))))->_utilityName);
    }
}

int StreamCipher_keyLength(NPObject * self, SEL _cmd) {
    return ((struct StreamCipher *)(self))->_keyLength;
}

void StreamCipher_setKeyLength_(NPObject * self, SEL _cmd, int value) {
    ((struct StreamCipher *)(self))->_keyLength = value;
}

NPClass * StreamCipher_getClass(NPClass * self, SEL _cmd) {
    return &jeti_StreamCipher_class;
}

NPObject * SecurityAuditor_initWithId_target_(NPObject * self, SEL _cmd, char * auditorId, StreamCipher * target) {
    struct SecurityAuditor * _self = ((struct SecurityAuditor *)(self));
    {
        self = NPObject_init(self, __jeti_sel_init);
        if (self) {
            {
                ((struct SecurityAuditor *)(self))->_auditorId = ((char *)(malloc(strlen(auditorId) + 1)));
                strcpy(((struct SecurityAuditor *)(self))->_auditorId, auditorId);
                ((struct SecurityAuditor *)(self))->_monitoredCipher = target;
            }
        }
        return self;
    }
}

void SecurityAuditor_auditTargetStatus(NPObject * self, SEL _cmd) {
    struct SecurityAuditor * _self = ((struct SecurityAuditor *)(self));
    {
        if (((struct SecurityAuditor *)(self))->_monitoredCipher != NULL) {
            {
                printf(" 🛡️ [审计总线 %s] 正在监听目标状态 -> [%s] 存活且正常工作。\n", ((struct SecurityAuditor *)(self))->_auditorId, ((char *)(((struct jeti_UtilityBase_vtable *)((struct SecurityAuditor *)(self))->_monitoredCipher->isa->vtable)->utilityName(((struct SecurityAuditor *)(self))->_monitoredCipher, __jeti_sel_utilityName))));
            }
        } else {
            {
                printf(" 🛡️ [审计总线 %s] 监听中断：目标对象已被垃圾回收(Auto-Nilled)！安全拦截！\n", ((struct SecurityAuditor *)(self))->_auditorId);
            }
        }
    }
}

void SecurityAuditor_dealloc(NPObject * self, SEL _cmd) {
    struct SecurityAuditor * _self = ((struct SecurityAuditor *)(self));
    {
        printf(" 🗑️ [生命周期] 审计监视器 [%s] 已下线。\n", ((struct SecurityAuditor *)(self))->_auditorId);
        if (((struct SecurityAuditor *)(self))->_auditorId) {
            free(((struct SecurityAuditor *)(self))->_auditorId);
        }
    }
}

char * SecurityAuditor_auditorId(NPObject * self, SEL _cmd) {
    return ((struct SecurityAuditor *)(self))->_auditorId;
}

void SecurityAuditor_setAuditorId_(NPObject * self, SEL _cmd, char * value) {
    ((struct SecurityAuditor *)(self))->_auditorId = value;
}

StreamCipher * SecurityAuditor_monitoredCipher(NPObject * self, SEL _cmd) {
    return ((struct SecurityAuditor *)(self))->_monitoredCipher;
}

void SecurityAuditor_setMonitoredCipher_(NPObject * self, SEL _cmd, StreamCipher * value) {
    ((struct SecurityAuditor *)(self))->_monitoredCipher = value;
}

NPClass * SecurityAuditor_getClass(NPClass * self, SEL _cmd) {
    return &jeti_SecurityAuditor_class;
}

NPObject * UtilityBase_initWithName_version_(NPObject * self, SEL _cmd, char * name, int ver) {
    struct UtilityBase * _self = ((struct UtilityBase *)(self));
    {
        self = NPObject_init(self, __jeti_sel_init);
        if (self) {
            {
                ((struct UtilityBase *)(self))->_utilityName = ((char *)(malloc(strlen(name) + 1)));
                strcpy(((struct UtilityBase *)(self))->_utilityName, name);
                ((struct UtilityBase *)(self))->_versionMajor = ver;
                ((struct UtilityBase *)(self))->_securityToken = 7777;
            }
        }
        return self;
    }
}

void UtilityBase_printBanner(NPObject * self, SEL _cmd) {
    struct UtilityBase * _self = ((struct UtilityBase *)(self));
    {
        printf(" ⚙️ [系统服务] 服务名称: %-18s | 内核版本: v%d.0\n", ((struct UtilityBase *)(self))->_utilityName, ((struct UtilityBase *)(self))->_versionMajor);
    }
}

void UtilityBase_refreshInternalToken(NPObject * self, SEL _cmd) {
    struct UtilityBase * _self = ((struct UtilityBase *)(self));
    {
        ((struct UtilityBase *)(self))->_securityToken = rand() % 9000 + 1000;
        printf("   🔒 [内核安全] 已刷新底层私有防伪令牌 (Token: %d)\n", ((struct UtilityBase *)(self))->_securityToken);
    }
}

void UtilityBase_runQuickSanityCheck(NPObject * self, SEL _cmd) {
    struct UtilityBase * _self = ((struct UtilityBase *)(self));
    {
        printf("   🧪 [分类探针] 快速内存心跳检查启动...\n");
        ((struct jeti_UtilityBase_vtable *)self->isa->vtable)->refreshInternalToken(self, __jeti_sel_refreshInternalToken);
    }
}

void UtilityBase_dealloc(NPObject * self, SEL _cmd) {
    struct UtilityBase * _self = ((struct UtilityBase *)(self));
    {
        printf(" 🗑️ [生命周期] 基类服务 [%s] 安全清退，回收缓存...\n", ((struct UtilityBase *)(self))->_utilityName);
        if (((struct UtilityBase *)(self))->_utilityName) {
            free(((struct UtilityBase *)(self))->_utilityName);
        }
    }
}

char * UtilityBase_utilityName(NPObject * self, SEL _cmd) {
    return ((struct UtilityBase *)(self))->_utilityName;
}

void UtilityBase_setUtilityName_(NPObject * self, SEL _cmd, char * value) {
    ((struct UtilityBase *)(self))->_utilityName = value;
}

int UtilityBase_versionMajor(NPObject * self, SEL _cmd) {
    return ((struct UtilityBase *)(self))->_versionMajor;
}

void UtilityBase_setVersionMajor_(NPObject * self, SEL _cmd, int value) {
    ((struct UtilityBase *)(self))->_versionMajor = value;
}

NPClass * UtilityBase_getClass(NPClass * self, SEL _cmd) {
    return &jeti_UtilityBase_class;
}

int main(int argc, const char * * argv) {
    jeti_autoreleasepool_t *__pool = jeti_autoreleasepool_push();
    jeti_meta_init();
    {
        jeti_autoreleasepool_t * __pool = jeti_autoreleasepool_push();
        {
            srand(((int)(time(NULL))));
            printf("\n======================================================\n");
            printf("      📡 Micrit 纯C99静态运维流式加密工具箱 📡      \n");
            printf("======================================================\n\n");
            NPObject *__jeti_tmp_0 = (NPObject_alloc(&jeti_SecurityAuditor_class, __jeti_sel_alloc));
            SecurityAuditor * globalAuditor = ((struct jeti_SecurityAuditor_vtable *)__jeti_tmp_0->isa->vtable)->initWithId_target_(__jeti_tmp_0, __jeti_sel_initWithId_target_, "AUDIT-01", NULL);
            printf(" --- 🧬 [局部作用域：临时数据混淆与弱引用抹零演练] ---\n");
            {
                NPObject *__jeti_tmp_1 = (NPObject_alloc(&jeti_StreamCipher_class, __jeti_sel_alloc));
                StreamCipher * tempCipher = ((struct jeti_StreamCipher_vtable *)__jeti_tmp_1->isa->vtable)->initWithName_key_(__jeti_tmp_1, __jeti_sel_initWithName_key_, "AES-Lite-99", "CACTUS_SYS_SALT");
                ((struct jeti_SecurityAuditor_vtable *)globalAuditor->isa->vtable)->setMonitoredCipher_(globalAuditor, __jeti_sel_setMonitoredCipher_, tempCipher);
                ((struct jeti_StreamCipher_vtable *)tempCipher->isa->vtable)->performDiagnostic(tempCipher, __jeti_sel_performDiagnostic);
                ((struct jeti_UtilityBase_vtable *)tempCipher->isa->vtable)->runQuickSanityCheck(tempCipher, __jeti_sel_runQuickSanityCheck);
                tempCipher->_keyLength = ((struct jeti_StreamCipher_vtable *)tempCipher->isa->vtable)->keyLength(tempCipher, __jeti_sel_keyLength) + 5;
                printf("   [1] 属性复合赋值更新 ➔ 密钥长度增加至: %d\n", ((struct jeti_StreamCipher_vtable *)tempCipher->isa->vtable)->keyLength(tempCipher, __jeti_sel_keyLength));
                char * rawData = "db_host=127.0.0.1;db_user=cactus;db_pass=root";
                char * cipherData = ((struct jeti_StreamCipher_vtable *)tempCipher->isa->vtable)->transformData_(tempCipher, __jeti_sel_transformData_, rawData);
                printf("   [2] 原始运维明文 ➔ '%s'\n", rawData);
                printf("   [3] 异或加密输出 ➔ '%s'\n\n", cipherData);
                free(cipherData);
                ((struct jeti_SecurityAuditor_vtable *)globalAuditor->isa->vtable)->auditTargetStatus(globalAuditor, __jeti_sel_auditTargetStatus);
                printf("  --> 临时加密流已完成转换任务，即将离开局部作用域并销毁...\n");
            }
            printf("\n --- 🧬 [沙盒作用域外：指针安全与自愈状态审查] ---\n");
            ((struct jeti_SecurityAuditor_vtable *)globalAuditor->isa->vtable)->auditTargetStatus(globalAuditor, __jeti_sel_auditTargetStatus);
            printf("\n -----------------------------------------------------\n\n");
            int captureMultiplier = 5;
            int captureOffset = 100;
            int (^pipelineCalculator)(int baseLength) = ^int(int baseLength) {
    printf("   ⚡ [流式配置闭包] 捕获倍率: %d | 捕获偏移量: %d\n", captureMultiplier, captureOffset);
    return baseLength * captureMultiplier + captureOffset;
}
;
            int outputValue = pipelineCalculator(12);
            printf("   🚀 最终 C99 降维闭包流水线运算结果 (12 * %d + %d): %d\n", captureMultiplier, captureOffset, outputValue);
        }
        jeti_autoreleasepool_pop(__pool);
    }
    return 0;
    jeti_autoreleasepool_pop(__pool);
}


// ─── Protocol metadata ─────────────────────────────────

extern NPProtocol jeti_protocol_DataTransformer;
extern NPProtocol jeti_protocol_CipherCodec;

NPProtocol jeti_protocol_DataTransformer = {
    .name = "DataTransformer",
    .parent_count = 0,
    .required_methods = (NPProtocolMethod[]){
        { .name = "performDiagnostic", .encoding = "@" },
    },
    .required_count = 1,
    .optional_count = 0,
};

NPProtocol jeti_protocol_CipherCodec = {
    .name = "CipherCodec",
    .parents = (NPProtocol *[]){
        &jeti_protocol_DataTransformer,
    },
    .parent_count = 1,
    .required_methods = (NPProtocolMethod[]){
        { .name = "transformData_", .encoding = "@" },
    },
    .required_count = 1,
    .optional_count = 0,
};


// ─── Class metadata ─────────────────────────────────────

struct jeti_NPObject_vtable jeti_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct jeti_StreamCipher_vtable jeti_StreamCipher_vtable_inst = {
    .init = NPObject_init,
    .dealloc = StreamCipher_dealloc,
    .initWithName_version_ = UtilityBase_initWithName_version_,
    .printBanner = UtilityBase_printBanner,
    .refreshInternalToken = UtilityBase_refreshInternalToken,
    .runQuickSanityCheck = UtilityBase_runQuickSanityCheck,
    .utilityName = UtilityBase_utilityName,
    .setUtilityName_ = UtilityBase_setUtilityName_,
    .versionMajor = UtilityBase_versionMajor,
    .setVersionMajor_ = UtilityBase_setVersionMajor_,
    .initWithName_key_ = StreamCipher_initWithName_key_,
    .performDiagnostic = StreamCipher_performDiagnostic,
    .transformData_ = StreamCipher_transformData_,
    .keyLength = StreamCipher_keyLength,
    .setKeyLength_ = StreamCipher_setKeyLength_,
};

struct jeti_SecurityAuditor_vtable jeti_SecurityAuditor_vtable_inst = {
    .init = NPObject_init,
    .dealloc = SecurityAuditor_dealloc,
    .initWithId_target_ = SecurityAuditor_initWithId_target_,
    .auditTargetStatus = SecurityAuditor_auditTargetStatus,
    .auditorId = SecurityAuditor_auditorId,
    .setAuditorId_ = SecurityAuditor_setAuditorId_,
    .monitoredCipher = SecurityAuditor_monitoredCipher,
    .setMonitoredCipher_ = SecurityAuditor_setMonitoredCipher_,
};

struct jeti_UtilityBase_vtable jeti_UtilityBase_vtable_inst = {
    .init = NPObject_init,
    .dealloc = UtilityBase_dealloc,
    .initWithName_version_ = UtilityBase_initWithName_version_,
    .printBanner = UtilityBase_printBanner,
    .refreshInternalToken = UtilityBase_refreshInternalToken,
    .runQuickSanityCheck = UtilityBase_runQuickSanityCheck,
    .utilityName = UtilityBase_utilityName,
    .setUtilityName_ = UtilityBase_setUtilityName_,
    .versionMajor = UtilityBase_versionMajor,
    .setVersionMajor_ = UtilityBase_setVersionMajor_,
};

struct jeti_NPObject_meta_vtable jeti_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct jeti_StreamCipher_meta_vtable jeti_StreamCipher_meta_vtable_inst = {
    .class = StreamCipher_getClass,
};

struct jeti_SecurityAuditor_meta_vtable jeti_SecurityAuditor_meta_vtable_inst = {
    .class = SecurityAuditor_getClass,
};

struct jeti_UtilityBase_meta_vtable jeti_UtilityBase_meta_vtable_inst = {
    .class = UtilityBase_getClass,
};

NPClass jeti_NPObject_class;
NPClass jeti_StreamCipher_class;
NPClass jeti_SecurityAuditor_class;
NPClass jeti_UtilityBase_class;

void jeti_meta_init(void) {
    jeti_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &jeti_NPObject_vtable_inst,
        .class_vtable = &jeti_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_StreamCipher_class = (NPClass){
        .name = "StreamCipher",
        .superclass = &jeti_UtilityBase_class,
        .instance_size = sizeof(struct StreamCipher),
        .vtable = &jeti_StreamCipher_vtable_inst,
        .class_vtable = &jeti_StreamCipher_meta_vtable_inst,
        .protocols = (NPProtocol *[]){
        },
        .protocol_count = 1,
    };
    jeti_SecurityAuditor_class = (NPClass){
        .name = "SecurityAuditor",
        .superclass = &jeti_NPObject_class,
        .instance_size = sizeof(struct SecurityAuditor),
        .vtable = &jeti_SecurityAuditor_vtable_inst,
        .class_vtable = &jeti_SecurityAuditor_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_UtilityBase_class = (NPClass){
        .name = "UtilityBase",
        .superclass = &jeti_NPObject_class,
        .instance_size = sizeof(struct UtilityBase),
        .vtable = &jeti_UtilityBase_vtable_inst,
        .class_vtable = &jeti_UtilityBase_meta_vtable_inst,
        .protocol_count = 0,
    };
}
