// Generated by jetic
#include <string.h>
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "jeti/runtime.h"
struct jeti___jeti_root_vtable;
struct jeti_NPObject_vtable;
struct jeti_NPObject_meta_vtable;
struct jeti_VectorBuffer_int_ptr_vtable;
struct jeti_VectorBuffer_int_ptr_meta_vtable;
struct jeti_VectorBuffer_vtable;
struct jeti_VectorBuffer_meta_vtable;

static const SEL __jeti_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __jeti_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __jeti_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __jeti_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __jeti_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __jeti_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __jeti_sel_count = {.name = "count", .hash = 0x39B1DDF4};

typedef struct __jeti_root __jeti_root;
typedef struct NPObject NPObject;
typedef struct VectorBuffer_int_ptr VectorBuffer_int_ptr;
typedef struct VectorBuffer VectorBuffer;

NPObject * __jeti_root_init(NPObject * self, SEL _cmd);
void __jeti_root_dealloc(NPObject * self, SEL _cmd);
void __jeti_root_release(NPObject * self, SEL _cmd);
NPObject * __jeti_root_retain(NPObject * self, SEL _cmd);
NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
void NPObject_release(NPObject * self, SEL _cmd);
NPObject * NPObject_retain(NPObject * self, SEL _cmd);
NPObject * VectorBuffer_init(NPObject * self, SEL _cmd);
int VectorBuffer_count(NPObject * self, SEL _cmd);
NPObject * jeti_alloc(struct NPClass * cls);
NPObject * jeti_init(NPObject * self);
void jeti_release(NPObject * obj);
NPObject * jeti_retain(NPObject * obj);
int main(void);
int * VectorBuffer_int_ptr_init(int * self, SEL _cmd);
int VectorBuffer_int_ptr_count(int * self, SEL _cmd);

NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPClass * VectorBuffer_int_ptr_getClass(NPClass * self, SEL _cmd);
NPClass * VectorBuffer_getClass(NPClass * self, SEL _cmd);

struct jeti___jeti_root_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
};
struct jeti_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
};
struct jeti_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct jeti_VectorBuffer_int_ptr_vtable {
    int * (*init)(int *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    int (*count)(int *, SEL);
};
struct jeti_VectorBuffer_int_ptr_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct jeti_VectorBuffer_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    int (*count)(NPObject *, SEL);
};
struct jeti_VectorBuffer_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};

struct __jeti_root {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct __jeti_root __jeti_root;

struct VectorBuffer_int_ptr {
    struct NPClass *isa;
    uint32_t retain_count;
    int _count;
};
typedef struct VectorBuffer_int_ptr VectorBuffer_int_ptr;

struct VectorBuffer {
    struct NPClass *isa;
    uint32_t retain_count;
    int _count;
};
typedef struct VectorBuffer VectorBuffer;

extern NPClass jeti___jeti_root_class;
extern NPClass jeti_NPObject_class;
extern NPClass jeti_VectorBuffer_int_ptr_class;
extern NPClass jeti_VectorBuffer_class;
void jeti_meta_init(void);

struct jeti___jeti_root_vtable jeti___jeti_root_vtable_inst = {
    .init = __jeti_root_init,
    .dealloc = __jeti_root_dealloc,
    .release = __jeti_root_release,
    .retain = __jeti_root_retain,
};

struct jeti_NPObject_vtable jeti_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
};

struct jeti_VectorBuffer_int_ptr_vtable jeti_VectorBuffer_int_ptr_vtable_inst = {
    .init = VectorBuffer_int_ptr_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .count = VectorBuffer_int_ptr_count,
};

struct jeti_VectorBuffer_vtable jeti_VectorBuffer_vtable_inst = {
    .init = VectorBuffer_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .count = VectorBuffer_count,
};

struct jeti_NPObject_meta_vtable jeti_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct jeti_VectorBuffer_int_ptr_meta_vtable jeti_VectorBuffer_int_ptr_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = VectorBuffer_int_ptr_getClass,
};

struct jeti_VectorBuffer_meta_vtable jeti_VectorBuffer_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = VectorBuffer_getClass,
};

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * VectorBuffer_int_ptr_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * VectorBuffer_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass jeti___jeti_root_class;
NPClass jeti_NPObject_class;
NPClass jeti_VectorBuffer_int_ptr_class;
NPClass jeti_VectorBuffer_class;

void jeti_meta_init(void) {
    jeti___jeti_root_class = (NPClass){
        .name = "__jeti_root",
        .superclass = NULL,
        .instance_size = sizeof(struct __jeti_root),
        .vtable = &jeti___jeti_root_vtable_inst,
        .class_vtable = NULL,
        .protocol_count = 0,
    };
    jeti_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = &jeti___jeti_root_class,
        .instance_size = sizeof(struct NPObject),
        .vtable = &jeti_NPObject_vtable_inst,
        .class_vtable = &jeti_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_VectorBuffer_int_ptr_class = (NPClass){
        .name = "VectorBuffer<int *>",
        .superclass = &jeti_NPObject_class,
        .instance_size = sizeof(struct VectorBuffer_int_ptr),
        .vtable = &jeti_VectorBuffer_int_ptr_vtable_inst,
        .class_vtable = &jeti_VectorBuffer_int_ptr_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_VectorBuffer_class = (NPClass){
        .name = "VectorBuffer",
        .superclass = &jeti_NPObject_class,
        .instance_size = sizeof(struct VectorBuffer),
        .vtable = &jeti_VectorBuffer_vtable_inst,
        .class_vtable = &jeti_VectorBuffer_meta_vtable_inst,
        .protocol_count = 0,
    };
}
NPObject * __jeti_root_init(NPObject * self, SEL _cmd) {
  struct __jeti_root * _self = (struct __jeti_root *)self;
  {
    return jeti_init(self);
  }
}

void __jeti_root_dealloc(NPObject * self, SEL _cmd) {
  struct __jeti_root * _self = (struct __jeti_root *)self;
  {
    return;
  }
}

void __jeti_root_release(NPObject * self, SEL _cmd) {
  struct __jeti_root * _self = (struct __jeti_root *)self;
  {
    jeti_release(self);
  }
}

NPObject * __jeti_root_retain(NPObject * self, SEL _cmd) {
  struct __jeti_root * _self = (struct __jeti_root *)self;
  {
    return jeti_retain(self);
  }
}

NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
  return jeti_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
  NPObject * obj = jeti_alloc(self);
  return jeti_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return jeti_init(self);
  }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return;
  }
}

void NPObject_release(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    jeti_release(self);
  }
}

NPObject * NPObject_retain(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return jeti_retain(self);
  }
}

NPObject * VectorBuffer_init(NPObject * self, SEL _cmd) {
  struct VectorBuffer * _self = (struct VectorBuffer *)self;
  {
    self = NPObject_init(self, sel_registerName("init"));
    if (self)     {
      _self->_count = 0;
    }
    return self;
  }
}

int VectorBuffer_count(NPObject * self, SEL _cmd) {
  struct VectorBuffer * _self = (struct VectorBuffer *)self;
  {
    return _self->_count;
  }
}

NPObject * jeti_alloc(struct NPClass * cls);

NPObject * jeti_init(NPObject * self);

void jeti_release(NPObject * obj);

NPObject * jeti_retain(NPObject * obj);

int main(void) {
  jeti_meta_init();
  {
    NPObject *__jeti_tmp_0 = (NPObject_alloc(&jeti_VectorBuffer_int_ptr_class, sel_registerName("alloc")));
    VectorBuffer_int_ptr * buf = ((struct jeti_NPObject_vtable *)__jeti_tmp_0->isa->vtable)->init(__jeti_tmp_0, sel_registerName("init"));
    printf("count=%d\n", ((struct jeti_VectorBuffer_vtable *)((NPObject *)(buf))->isa->vtable)->count(buf, sel_registerName("count")));
  }
  return 0;
}

int * VectorBuffer_int_ptr_init(int * self, SEL _cmd) {
  struct VectorBuffer_int_ptr * _self = (struct VectorBuffer_int_ptr *)self;
  {
    self = NPObject_init(self, sel_registerName("init"));
    if (self)     {
      _self->_count = 0;
    }
    return self;
  }
}

int VectorBuffer_int_ptr_count(int * self, SEL _cmd) {
  struct VectorBuffer_int_ptr * _self = (struct VectorBuffer_int_ptr *)self;
  {
    return _self->_count;
  }
}

