// Generated by nopac
#import <stdio.h>
#import <stdlib.h>
#import <string.h>
#import <time.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"


#include <string.h>

struct nopa_NFObject_vtable;
struct nopa_GameEntity_vtable;
struct nopa_Hero_vtable;
struct nopa_Dragon_vtable;

#define nopa_NFObject_vtable_index_init 2
#define nopa_NFObject_vtable_index_dealloc 3
#define nopa_GameEntity_vtable_index_initWithName_hp_attack_ 4
#define nopa_GameEntity_vtable_index_displayStatus 5
#define nopa_GameEntity_vtable_index_takeDamage_ 6
#define nopa_GameEntity_vtable_index_attack_ 7
#define nopa_GameEntity_vtable_index_dealloc 3
#define nopa_Hero_vtable_index_usePotion 8
#define nopa_Dragon_vtable_index_breatheFire_ 8
#define nopa_Dragon_vtable_index_attack_ 7

static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_name = {.name = "name", .hash = 0x8D39BDE6};
static const SEL __nopa_sel_takeDamage_ = {.name = "takeDamage_", .hash = 0x2D2F9664};
static const SEL __nopa_sel_hp = {.name = "hp", .hash = 0x513AD265};
static const SEL __nopa_sel_maxHp = {.name = "maxHp", .hash = 0x4EC68689};
static const SEL __nopa_sel_setHp_ = {.name = "setHp_", .hash = 0x28B12E84};
static const SEL __nopa_sel_attackPower = {.name = "attackPower", .hash = 0xB135287E};
static const SEL __nopa_sel_initWithName_hp_attack_ = {.name = "initWithName_hp_attack_", .hash = 0xECE02257};
static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nopa_sel_setPotions_ = {.name = "setPotions_", .hash = 0x3D0C3BF6};
static const SEL __nopa_sel_setRage_ = {.name = "setRage_", .hash = 0xE3C69E47};
static const SEL __nopa_sel_displayStatus = {.name = "displayStatus", .hash = 0x95B342BF};
static const SEL __nopa_sel_potions = {.name = "potions", .hash = 0xAAE165DB};
static const SEL __nopa_sel_attack_ = {.name = "attack_", .hash = 0x2CB1A706};
static const SEL __nopa_sel_usePotion = {.name = "usePotion", .hash = 0x0861A273};
static const SEL __nopa_sel_rage = {.name = "rage", .hash = 0x7EB2AF0C};
static const SEL __nopa_sel_breatheFire_ = {.name = "breatheFire_", .hash = 0x6506FFFF};

typedef struct NFObject NFObject;
typedef struct GameEntity GameEntity;
typedef struct Hero Hero;
typedef struct Dragon Dragon;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
NFObject * GameEntity_initWithName_hp_attack_(NFObject * self, SEL _cmd, char * name, int hp, int attack);
void GameEntity_displayStatus(NFObject * self, SEL _cmd);
void GameEntity_takeDamage_(NFObject * self, SEL _cmd, int amount);
void GameEntity_attack_(NFObject * self, SEL _cmd, NFObject * target);
void GameEntity_dealloc(NFObject * self, SEL _cmd);
char * GameEntity_name(NFObject * self, SEL _cmd);
void GameEntity_setName_(NFObject * self, SEL _cmd, char * value);
int GameEntity_hp(NFObject * self, SEL _cmd);
void GameEntity_setHp_(NFObject * self, SEL _cmd, int value);
int GameEntity_maxHp(NFObject * self, SEL _cmd);
void GameEntity_setMaxHp_(NFObject * self, SEL _cmd, int value);
int GameEntity_attackPower(NFObject * self, SEL _cmd);
void GameEntity_setAttackPower_(NFObject * self, SEL _cmd, int value);
NFClass * GameEntity_getClass(NFClass * self, SEL _cmd);
void Hero_usePotion(NFObject * self, SEL _cmd);
int Hero_potions(NFObject * self, SEL _cmd);
void Hero_setPotions_(NFObject * self, SEL _cmd, int value);
NFClass * Hero_getClass(NFClass * self, SEL _cmd);
void Dragon_breatheFire_(NFObject * self, SEL _cmd, NFObject * target);
void Dragon_attack_(NFObject * self, SEL _cmd, NFObject * target);
int Dragon_rage(NFObject * self, SEL _cmd);
void Dragon_setRage_(NFObject * self, SEL _cmd, int value);
NFClass * Dragon_getClass(NFClass * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NFClass nopa_NFObject_class;
extern NFClass nopa_GameEntity_class;
extern NFClass nopa_Hero_class;
extern NFClass nopa_Dragon_class;
void nopa_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct nopa_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct nopa_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct GameEntity {
    struct NFClass *isa;
    uint32_t retain_count;
    char * _name;
    int _hp;
    int _maxHp;
    int _attackPower;
};
typedef struct GameEntity GameEntity;
struct nopa_GameEntity_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    NFObject * (*initWithName_hp_attack_)(NFObject *, SEL, char *, int, int);
    void (*displayStatus)(NFObject *, SEL);
    void (*takeDamage_)(NFObject *, SEL, int);
    void (*attack_)(NFObject *, SEL, NFObject *);
    char * (*name)(NFObject *, SEL);
    void (*setName_)(NFObject *, SEL, char *);
    int (*hp)(NFObject *, SEL);
    void (*setHp_)(NFObject *, SEL, int);
    int (*maxHp)(NFObject *, SEL);
    void (*setMaxHp_)(NFObject *, SEL, int);
    int (*attackPower)(NFObject *, SEL);
    void (*setAttackPower_)(NFObject *, SEL, int);
};
struct nopa_GameEntity_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
struct Hero {
    struct NFClass *isa;
    uint32_t retain_count;
    char * _name;
    int _hp;
    int _maxHp;
    int _attackPower;
    int _potions;
};
typedef struct Hero Hero;
struct nopa_Hero_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    NFObject * (*initWithName_hp_attack_)(NFObject *, SEL, char *, int, int);
    void (*displayStatus)(NFObject *, SEL);
    void (*takeDamage_)(NFObject *, SEL, int);
    void (*attack_)(NFObject *, SEL, NFObject *);
    char * (*name)(NFObject *, SEL);
    void (*setName_)(NFObject *, SEL, char *);
    int (*hp)(NFObject *, SEL);
    void (*setHp_)(NFObject *, SEL, int);
    int (*maxHp)(NFObject *, SEL);
    void (*setMaxHp_)(NFObject *, SEL, int);
    int (*attackPower)(NFObject *, SEL);
    void (*setAttackPower_)(NFObject *, SEL, int);
    void (*usePotion)(NFObject *, SEL);
    int (*potions)(NFObject *, SEL);
    void (*setPotions_)(NFObject *, SEL, int);
};
struct nopa_Hero_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
struct Dragon {
    struct NFClass *isa;
    uint32_t retain_count;
    char * _name;
    int _hp;
    int _maxHp;
    int _attackPower;
    int _rage;
};
typedef struct Dragon Dragon;
struct nopa_Dragon_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    NFObject * (*initWithName_hp_attack_)(NFObject *, SEL, char *, int, int);
    void (*displayStatus)(NFObject *, SEL);
    void (*takeDamage_)(NFObject *, SEL, int);
    void (*attack_)(NFObject *, SEL, NFObject *);
    char * (*name)(NFObject *, SEL);
    void (*setName_)(NFObject *, SEL, char *);
    int (*hp)(NFObject *, SEL);
    void (*setHp_)(NFObject *, SEL, int);
    int (*maxHp)(NFObject *, SEL);
    void (*setMaxHp_)(NFObject *, SEL, int);
    int (*attackPower)(NFObject *, SEL);
    void (*setAttackPower_)(NFObject *, SEL, int);
    void (*breatheFire_)(NFObject *, SEL, NFObject *);
    int (*rage)(NFObject *, SEL);
    void (*setRage_)(NFObject *, SEL, int);
};
struct nopa_Dragon_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return nopa_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = nopa_alloc(self);
    return nopa_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return nopa_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &nopa_NFObject_class;
}

NFObject * nopa_alloc(struct NFClass * cls);
NFObject * nopa_init(NFObject * );
NFObject * GameEntity_initWithName_hp_attack_(NFObject * self, SEL _cmd, char * name, int hp, int attack) {
    struct GameEntity * _self = ((struct GameEntity *)(self));
    {
        self = NFObject_init(self, __nopa_sel_init);
        if (self) {
            {
                ((struct GameEntity *)(self))->_name = name;
                ((struct GameEntity *)(self))->_hp = hp;
                ((struct GameEntity *)(self))->_maxHp = hp;
                ((struct GameEntity *)(self))->_attackPower = attack;
            }
        }
        return self;
    }
}

void GameEntity_displayStatus(NFObject * self, SEL _cmd) {
    struct GameEntity * _self = ((struct GameEntity *)(self));
    {
        printf(" [%s] HP: %d/%d | 基础ATK: %d\n", ((struct GameEntity *)(self))->_name, ((struct GameEntity *)(self))->_hp, ((struct GameEntity *)(self))->_maxHp, ((struct GameEntity *)(self))->_attackPower);
    }
}

void GameEntity_takeDamage_(NFObject * self, SEL _cmd, int amount) {
    struct GameEntity * _self = ((struct GameEntity *)(self));
    {
        ((struct GameEntity *)(self))->_hp = ((struct GameEntity *)(self))->_hp - amount;
        if (((struct GameEntity *)(self))->_hp < 0) {
            ((struct GameEntity *)(self))->_hp = 0;
        }
        printf(" 💥 [%s] 受到 %d 点伤害！(剩余生命: %d/%d)\n", ((struct GameEntity *)(self))->_name, amount, ((struct GameEntity *)(self))->_hp, ((struct GameEntity *)(self))->_maxHp);
    }
}

void GameEntity_attack_(NFObject * self, SEL _cmd, NFObject * target) {
    struct GameEntity * _self = ((struct GameEntity *)(self));
    {
        printf(" ⚔️ [%s] 发动普通攻击，砍向 [%s]！\n", ((struct GameEntity *)(self))->_name, ((struct nopa_GameEntity_vtable *)target->isa->vtable)->name(target, __nopa_sel_name));
        ((struct nopa_GameEntity_vtable *)target->isa->vtable)->takeDamage_(target, __nopa_sel_takeDamage_, ((struct GameEntity *)(self))->_attackPower);
    }
}

void GameEntity_dealloc(NFObject * self, SEL _cmd) {
    struct GameEntity * _self = ((struct GameEntity *)(self));
    {
        printf(" 👻 [%s] 倒在了竞技场的沙尘之中...\n", ((struct GameEntity *)(self))->_name);
    }
}

char * GameEntity_name(NFObject * self, SEL _cmd) {
    return ((struct GameEntity *)(self))->_name;
}

void GameEntity_setName_(NFObject * self, SEL _cmd, char * value) {
    ((struct GameEntity *)(self))->_name = value;
}

int GameEntity_hp(NFObject * self, SEL _cmd) {
    return ((struct GameEntity *)(self))->_hp;
}

void GameEntity_setHp_(NFObject * self, SEL _cmd, int value) {
    ((struct GameEntity *)(self))->_hp = value;
}

int GameEntity_maxHp(NFObject * self, SEL _cmd) {
    return ((struct GameEntity *)(self))->_maxHp;
}

void GameEntity_setMaxHp_(NFObject * self, SEL _cmd, int value) {
    ((struct GameEntity *)(self))->_maxHp = value;
}

int GameEntity_attackPower(NFObject * self, SEL _cmd) {
    return ((struct GameEntity *)(self))->_attackPower;
}

void GameEntity_setAttackPower_(NFObject * self, SEL _cmd, int value) {
    ((struct GameEntity *)(self))->_attackPower = value;
}

NFClass * GameEntity_getClass(NFClass * self, SEL _cmd) {
    return &nopa_GameEntity_class;
}

void Hero_usePotion(NFObject * self, SEL _cmd) {
    struct Hero * _self = ((struct Hero *)(self));
    {
        if (((struct Hero *)(self))->_potions <= 0) {
            {
                printf(" ❌ 药水已经用尽了！\n");
                return;
            }
        }
        ((struct Hero *)(self))->_potions--;
        int healAmount = 40;
        int currentHp = ((struct nopa_GameEntity_vtable *)self->isa->vtable)->hp(self, __nopa_sel_hp);
        int maxHp = ((struct nopa_GameEntity_vtable *)self->isa->vtable)->maxHp(self, __nopa_sel_maxHp);
        int newHp = currentHp + healAmount;
        if (newHp > maxHp) {
            newHp = maxHp;
        }
        ((struct nopa_GameEntity_vtable *)self->isa->vtable)->setHp_(self, __nopa_sel_setHp_, newHp);
        printf(" 🧪 [%s] 喝下圣光药水！恢复 %d 点生命值！(剩余药水: %d, 当前HP: %d/%d)\n", ((struct nopa_GameEntity_vtable *)self->isa->vtable)->name(self, __nopa_sel_name), healAmount, ((struct Hero *)(self))->_potions, ((struct nopa_GameEntity_vtable *)self->isa->vtable)->hp(self, __nopa_sel_hp), ((struct nopa_GameEntity_vtable *)self->isa->vtable)->maxHp(self, __nopa_sel_maxHp));
    }
}

int Hero_potions(NFObject * self, SEL _cmd) {
    return ((struct Hero *)(self))->_potions;
}

void Hero_setPotions_(NFObject * self, SEL _cmd, int value) {
    ((struct Hero *)(self))->_potions = value;
}

NFClass * Hero_getClass(NFClass * self, SEL _cmd) {
    return &nopa_Hero_class;
}

void Dragon_breatheFire_(NFObject * self, SEL _cmd, NFObject * target) {
    struct Dragon * _self = ((struct Dragon *)(self));
    {
        printf(" 🔥🔥🔥 [%s] 狂暴！对 [%s] 喷射出毁灭龙息！\n", ((struct nopa_GameEntity_vtable *)self->isa->vtable)->name(self, __nopa_sel_name), ((struct nopa_GameEntity_vtable *)target->isa->vtable)->name(target, __nopa_sel_name));
        int fireDamage = ((struct nopa_GameEntity_vtable *)self->isa->vtable)->attackPower(self, __nopa_sel_attackPower) + ((struct Dragon *)(self))->_rage;
        ((struct nopa_GameEntity_vtable *)target->isa->vtable)->takeDamage_(target, __nopa_sel_takeDamage_, fireDamage);
        ((struct Dragon *)(self))->_rage = 0;
    }
}

void Dragon_attack_(NFObject * self, SEL _cmd, NFObject * target) {
    struct Dragon * _self = ((struct Dragon *)(self));
    {
        ((struct Dragon *)(self))->_rage = ((struct Dragon *)(self))->_rage + 10;
        printf(" 👹 [%s] 用巨爪横扫 [%s]！(积攒怒气: +10, 当前怒气: %d)\n", ((struct nopa_GameEntity_vtable *)self->isa->vtable)->name(self, __nopa_sel_name), ((struct nopa_GameEntity_vtable *)target->isa->vtable)->name(target, __nopa_sel_name), ((struct Dragon *)(self))->_rage);
        ((struct nopa_GameEntity_vtable *)target->isa->vtable)->takeDamage_(target, __nopa_sel_takeDamage_, ((struct nopa_GameEntity_vtable *)self->isa->vtable)->attackPower(self, __nopa_sel_attackPower));
    }
}

int Dragon_rage(NFObject * self, SEL _cmd) {
    return ((struct Dragon *)(self))->_rage;
}

void Dragon_setRage_(NFObject * self, SEL _cmd, int value) {
    ((struct Dragon *)(self))->_rage = value;
}

NFClass * Dragon_getClass(NFClass * self, SEL _cmd) {
    return &nopa_Dragon_class;
}

int main(int argc, const char * * argv) {
    nopa_autoreleasepool_t *__pool = nopa_autoreleasepool_push();
    nopa_meta_init();
    {
        nopa_autoreleasepool_t * __pool = nopa_autoreleasepool_push();
        {
            srand(((int)(time(NULL))));
            printf("\n======================================================\n");
            printf("       🏟️ 欢迎来到 Micrit 静态面向对象竞技场 🏟️\n");
            printf("======================================================\n\n");
            char inputBuffer[64];
            printf(" 请输入你的勇士名字: ");
            if (scanf("%63s", inputBuffer) != 1) {
                {
                    strcpy(inputBuffer, "无名英雄");
                }
            }
            NFObject *__nopa_tmp_0 = (NFObject_alloc(&nopa_Hero_class, __nopa_sel_alloc));
            Hero * hero = ((struct nopa_GameEntity_vtable *)__nopa_tmp_0->isa->vtable)->initWithName_hp_attack_(__nopa_tmp_0, __nopa_sel_initWithName_hp_attack_, inputBuffer, 150, 20);
            ((struct nopa_Hero_vtable *)hero->isa->vtable)->setPotions_(hero, __nopa_sel_setPotions_, 3);
            NFObject *__nopa_tmp_1 = (NFObject_alloc(&nopa_Dragon_class, __nopa_sel_alloc));
            Dragon * boss = ((struct nopa_GameEntity_vtable *)__nopa_tmp_1->isa->vtable)->initWithName_hp_attack_(__nopa_tmp_1, __nopa_sel_initWithName_hp_attack_, "红莲劫火·萨卡", 200, 15);
            ((struct nopa_Dragon_vtable *)boss->isa->vtable)->setRage_(boss, __nopa_sel_setRage_, 0);
            printf("\n ⚔️ 宿命的对决即将开始！\n");
            printf(" -----------------------------------------------------\n");
            ((struct nopa_GameEntity_vtable *)hero->isa->vtable)->displayStatus(hero, __nopa_sel_displayStatus);
            ((struct nopa_GameEntity_vtable *)boss->isa->vtable)->displayStatus(boss, __nopa_sel_displayStatus);
            printf(" -----------------------------------------------------\n\n");
            int turn = 1;
            while (((struct nopa_GameEntity_vtable *)hero->isa->vtable)->hp(hero, __nopa_sel_hp) > 0 && ((struct nopa_GameEntity_vtable *)boss->isa->vtable)->hp(boss, __nopa_sel_hp) > 0) {
                {
                    printf("\n--- 【第 %d 回合】 ---\n", turn);
                    ((struct nopa_GameEntity_vtable *)hero->isa->vtable)->displayStatus(hero, __nopa_sel_displayStatus);
                    ((struct nopa_GameEntity_vtable *)boss->isa->vtable)->displayStatus(boss, __nopa_sel_displayStatus);
                    printf("----------------------\n");
                    printf("请做出你的抉择:\n");
                    printf(" [1] 奋力一击 (普通攻击, ATK: %d)\n", ((struct nopa_GameEntity_vtable *)hero->isa->vtable)->attackPower(hero, __nopa_sel_attackPower));
                    printf(" [2] 圣光治愈 (回复40点HP, 剩余药水: %d瓶)\n", ((struct nopa_Hero_vtable *)hero->isa->vtable)->potions(hero, __nopa_sel_potions));
                    printf(" [3] 极意·苍穹破 (蓄力爆发, 捕获战局倍率!)\n");
                    printf("请输入指令 (1-3): ");
                    int choice = 0;
                    if (scanf("%d", &choice) != 1) {
                        {
                            while (getchar() != 10) {
                                ;
                            }
                            choice = 1;
                        }
                    }
                    if (choice == 1) {
                        {
                            ((struct nopa_GameEntity_vtable *)hero->isa->vtable)->attack_(hero, __nopa_sel_attack_, boss);
                        }
                    } else {
                        if (choice == 2) {
                            {
                                ((struct nopa_Hero_vtable *)hero->isa->vtable)->usePotion(hero, __nopa_sel_usePotion);
                            }
                        } else {
                            if (choice == 3) {
                                {
                                    int turn_bonus = turn;
                                    int base_multiplier = 2;
                                    int (^megaSlash)(int dmg) = ^int(int dmg) {
    int final_multiplier = base_multiplier + turn_bonus / 2;
    printf(" 🔥 [极意·苍穹破] 战意爆发！捕获当前回合加成！(倍率: x%d)\n", final_multiplier);
    return dmg * final_multiplier;
}
;
                                    int finalDamage = megaSlash(((struct nopa_GameEntity_vtable *)hero->isa->vtable)->attackPower(hero, __nopa_sel_attackPower));
                                    printf(" 💥 苍穹破碎！对 [%s] 造成了巨大的 %d 点伤害！\n", ((struct nopa_GameEntity_vtable *)boss->isa->vtable)->name(boss, __nopa_sel_name), finalDamage);
                                    ((struct nopa_GameEntity_vtable *)boss->isa->vtable)->takeDamage_(boss, __nopa_sel_takeDamage_, finalDamage);
                                }
                            } else {
                                {
                                    printf(" ❓ 犹豫不决让动作迟缓，你白白浪费了一回合！\n");
                                }
                            }
                        }
                    }
                    if (((struct nopa_GameEntity_vtable *)boss->isa->vtable)->hp(boss, __nopa_sel_hp) <= 0) {
                        {
                            break;
                        }
                    }
                    printf("\n 🐉 [%s] 的回合行动: \n", ((struct nopa_GameEntity_vtable *)boss->isa->vtable)->name(boss, __nopa_sel_name));
                    if (((struct nopa_Dragon_vtable *)boss->isa->vtable)->rage(boss, __nopa_sel_rage) >= 20) {
                        {
                            ((struct nopa_Dragon_vtable *)boss->isa->vtable)->breatheFire_(boss, __nopa_sel_breatheFire_, hero);
                        }
                    } else {
                        {
                            ((struct nopa_Dragon_vtable *)boss->isa->vtable)->attack_(boss, __nopa_sel_attack_, hero);
                        }
                    }
                    turn++;
                }
            }
            printf("\n======================================================\n");
            printf("                      战役终结\n");
            printf("======================================================\n\n");
            if (((struct nopa_GameEntity_vtable *)hero->isa->vtable)->hp(hero, __nopa_sel_hp) > 0) {
                {
                    printf(" 🎉 凯旋！[%s] 成功弑龙，成为了竞技场的传说！\n", ((struct nopa_GameEntity_vtable *)hero->isa->vtable)->name(hero, __nopa_sel_name));
                }
            } else {
                {
                    printf(" 💀 终局。[%s] 还是倒在了红莲龙息之下，竞技场归于死寂...\n", ((struct nopa_GameEntity_vtable *)hero->isa->vtable)->name(hero, __nopa_sel_name));
                }
            }
            printf("\n 感谢游玩 Micrit 纯静态自研引擎小游戏！\n\n");
        }
        nopa_autoreleasepool_pop(__pool);
    }
    return 0;
    nopa_autoreleasepool_pop(__pool);
}


// ─── Protocol metadata ─────────────────────────────────

extern NFProtocol nopa_protocol_Fighter;

NFProtocol nopa_protocol_Fighter = {
    .name = "Fighter",
    .parent_count = 0,
    .required_methods = (NFProtocolMethod[]){
        { .name = "takeDamage_", .encoding = "@" },
        { .name = "attack_", .encoding = "@" },
    },
    .required_count = 2,
    .optional_count = 0,
};


// ─── Class metadata ─────────────────────────────────────

struct nopa_NFObject_vtable nopa_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct nopa_GameEntity_vtable nopa_GameEntity_vtable_inst = {
    .init = NFObject_init,
    .dealloc = GameEntity_dealloc,
    .initWithName_hp_attack_ = GameEntity_initWithName_hp_attack_,
    .displayStatus = GameEntity_displayStatus,
    .takeDamage_ = GameEntity_takeDamage_,
    .attack_ = GameEntity_attack_,
    .name = GameEntity_name,
    .setName_ = GameEntity_setName_,
    .hp = GameEntity_hp,
    .setHp_ = GameEntity_setHp_,
    .maxHp = GameEntity_maxHp,
    .setMaxHp_ = GameEntity_setMaxHp_,
    .attackPower = GameEntity_attackPower,
    .setAttackPower_ = GameEntity_setAttackPower_,
};

struct nopa_Hero_vtable nopa_Hero_vtable_inst = {
    .init = NFObject_init,
    .dealloc = GameEntity_dealloc,
    .initWithName_hp_attack_ = GameEntity_initWithName_hp_attack_,
    .displayStatus = GameEntity_displayStatus,
    .takeDamage_ = GameEntity_takeDamage_,
    .attack_ = GameEntity_attack_,
    .name = GameEntity_name,
    .setName_ = GameEntity_setName_,
    .hp = GameEntity_hp,
    .setHp_ = GameEntity_setHp_,
    .maxHp = GameEntity_maxHp,
    .setMaxHp_ = GameEntity_setMaxHp_,
    .attackPower = GameEntity_attackPower,
    .setAttackPower_ = GameEntity_setAttackPower_,
    .usePotion = Hero_usePotion,
    .potions = Hero_potions,
    .setPotions_ = Hero_setPotions_,
};

struct nopa_Dragon_vtable nopa_Dragon_vtable_inst = {
    .init = NFObject_init,
    .dealloc = GameEntity_dealloc,
    .initWithName_hp_attack_ = GameEntity_initWithName_hp_attack_,
    .displayStatus = GameEntity_displayStatus,
    .takeDamage_ = GameEntity_takeDamage_,
    .attack_ = Dragon_attack_,
    .name = GameEntity_name,
    .setName_ = GameEntity_setName_,
    .hp = GameEntity_hp,
    .setHp_ = GameEntity_setHp_,
    .maxHp = GameEntity_maxHp,
    .setMaxHp_ = GameEntity_setMaxHp_,
    .attackPower = GameEntity_attackPower,
    .setAttackPower_ = GameEntity_setAttackPower_,
    .breatheFire_ = Dragon_breatheFire_,
    .rage = Dragon_rage,
    .setRage_ = Dragon_setRage_,
};

struct nopa_NFObject_meta_vtable nopa_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct nopa_GameEntity_meta_vtable nopa_GameEntity_meta_vtable_inst = {
    .class = GameEntity_getClass,
};

struct nopa_Hero_meta_vtable nopa_Hero_meta_vtable_inst = {
    .class = Hero_getClass,
};

struct nopa_Dragon_meta_vtable nopa_Dragon_meta_vtable_inst = {
    .class = Dragon_getClass,
};

NFClass nopa_NFObject_class;
NFClass nopa_GameEntity_class;
NFClass nopa_Hero_class;
NFClass nopa_Dragon_class;

void nopa_meta_init(void) {
    nopa_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &nopa_NFObject_vtable_inst,
        .class_vtable = &nopa_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_GameEntity_class = (NFClass){
        .name = "GameEntity",
        .superclass = &nopa_NFObject_class,
        .instance_size = sizeof(struct GameEntity),
        .vtable = &nopa_GameEntity_vtable_inst,
        .class_vtable = &nopa_GameEntity_meta_vtable_inst,
        .protocols = (NFProtocol *[]){
        },
        .protocol_count = 1,
    };
    nopa_Hero_class = (NFClass){
        .name = "Hero",
        .superclass = &nopa_GameEntity_class,
        .instance_size = sizeof(struct Hero),
        .vtable = &nopa_Hero_vtable_inst,
        .class_vtable = &nopa_Hero_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Dragon_class = (NFClass){
        .name = "Dragon",
        .superclass = &nopa_GameEntity_class,
        .instance_size = sizeof(struct Dragon),
        .vtable = &nopa_Dragon_vtable_inst,
        .class_vtable = &nopa_Dragon_meta_vtable_inst,
        .protocol_count = 0,
    };
}
