// Generated by ovicc
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "ovic/runtime.h"
struct ovic_NPObject_vtable;
struct ovic_NPObject_meta_vtable;
struct ovic_Engine__Physics__Collider_vtable;
struct ovic_Engine__Physics__Collider_meta_vtable;
struct ovic_GameWorld_vtable;
struct ovic_GameWorld_meta_vtable;
struct ovic_Engine__Core__Transform_vtable;
struct ovic_Engine__Core__Transform_meta_vtable;
struct ovic_Render__Sprite_vtable;
struct ovic_Render__Sprite_meta_vtable;

static const SEL __ovic_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __ovic_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __ovic_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __ovic_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __ovic_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __ovic_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __ovic_sel_initWithX_y_ = {.name = "initWithX:y:", .hash = 0x2B77CF8E};
static const SEL __ovic_sel_translateByX_y_ = {.name = "translateByX:y:", .hash = 0x81D89549};
static const SEL __ovic_sel_initWithType_callback_ = {.name = "initWithType:callback:", .hash = 0x68FB1D5A};
static const SEL __ovic_sel_triggerCollisionWithForce_ = {.name = "triggerCollisionWithForce:", .hash = 0xA6CFA916};
static const SEL __ovic_sel_initWithTexture_ = {.name = "initWithTexture:", .hash = 0xC81128D0};
static const SEL __ovic_sel_drawAtX_y_ = {.name = "drawAtX:y:", .hash = 0xBFBC1653};
static const SEL __ovic_sel_runLoop = {.name = "runLoop", .hash = 0x90B524F8};

typedef struct NPObject NPObject;
typedef struct Engine__Physics__Collider Engine__Physics__Collider;
typedef struct GameWorld GameWorld;
typedef struct Engine__Core__Transform Engine__Core__Transform;
typedef struct Render__Sprite Render__Sprite;

typedef void (^CollisionCallback)(int) ;
typedef void (^Engine__Physics__CollisionCallback)(int) ;

NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
void NPObject_release(NPObject * self, SEL _cmd);
NPObject * NPObject_retain(NPObject * self, SEL _cmd);
NPObject * Engine__Core__Transform_initWithX_y_(NPObject * self, SEL _cmd, int posX, int posY);
void Engine__Core__Transform_translateByX_y_(NPObject * self, SEL _cmd, int dx, int dy);
NPObject * Engine__Physics__Collider_initWithType_callback_(NPObject * self, SEL _cmd, const char * type, Engine__Physics__CollisionCallback cb);
void Engine__Physics__Collider_triggerCollisionWithForce_(NPObject * self, SEL _cmd, int force);
NPObject * Render__Sprite_initWithTexture_(NPObject * self, SEL _cmd, const char * tex);
void Render__Sprite_drawAtX_y_(NPObject * self, SEL _cmd, int x, int y);
void GameWorld_runLoop(NPObject * self, SEL _cmd);
NPObject * ovic_alloc(struct NPClass * cls);
NPObject * ovic_init(NPObject * self);
void ovic_release(NPObject * obj);
NPObject * ovic_retain(NPObject * obj);
int main(int argc, const char * argv[]);

NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPClass * Engine__Physics__Collider_getClass(NPClass * self, SEL _cmd);
NPClass * GameWorld_getClass(NPClass * self, SEL _cmd);
NPClass * Engine__Core__Transform_getClass(NPClass * self, SEL _cmd);
NPClass * Render__Sprite_getClass(NPClass * self, SEL _cmd);

struct ovic_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
};
struct ovic_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct ovic_Engine__Physics__Collider_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    NPObject * (*initWithType_callback_)(NPObject *, SEL, const char *, Engine__Physics__CollisionCallback);
    void (*triggerCollisionWithForce_)(NPObject *, SEL, int);
};
struct ovic_Engine__Physics__Collider_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct ovic_GameWorld_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    void (*runLoop)(NPObject *, SEL);
};
struct ovic_GameWorld_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct ovic_Engine__Core__Transform_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    NPObject * (*initWithX_y_)(NPObject *, SEL, int, int);
    void (*translateByX_y_)(NPObject *, SEL, int, int);
};
struct ovic_Engine__Core__Transform_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct ovic_Render__Sprite_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    NPObject * (*initWithTexture_)(NPObject *, SEL, const char *);
    void (*drawAtX_y_)(NPObject *, SEL, int, int);
};
struct ovic_Render__Sprite_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};

struct Engine__Physics__Collider {
    struct NPClass *isa;
    uint32_t retain_count;
    const char * typeName;
    CollisionCallback onCollision;
};
typedef struct Engine__Physics__Collider Engine__Physics__Collider;

struct GameWorld {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct GameWorld GameWorld;

struct Engine__Core__Transform {
    struct NPClass *isa;
    uint32_t retain_count;
    int x;
    int y;
};
typedef struct Engine__Core__Transform Engine__Core__Transform;

struct Render__Sprite {
    struct NPClass *isa;
    uint32_t retain_count;
    const char * textureName;
};
typedef struct Render__Sprite Render__Sprite;

extern NPClass ovic_NPObject_class;
extern NPClass ovic_Engine__Physics__Collider_class;
extern NPClass ovic_GameWorld_class;
extern NPClass ovic_Engine__Core__Transform_class;
extern NPClass ovic_Render__Sprite_class;
void ovic_meta_init(void);

struct ovic_NPObject_vtable ovic_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
};

struct ovic_Engine__Physics__Collider_vtable ovic_Engine__Physics__Collider_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .initWithType_callback_ = Engine__Physics__Collider_initWithType_callback_,
    .triggerCollisionWithForce_ = Engine__Physics__Collider_triggerCollisionWithForce_,
};

struct ovic_GameWorld_vtable ovic_GameWorld_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .runLoop = GameWorld_runLoop,
};

struct ovic_Engine__Core__Transform_vtable ovic_Engine__Core__Transform_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .initWithX_y_ = Engine__Core__Transform_initWithX_y_,
    .translateByX_y_ = Engine__Core__Transform_translateByX_y_,
};

struct ovic_Render__Sprite_vtable ovic_Render__Sprite_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .initWithTexture_ = Render__Sprite_initWithTexture_,
    .drawAtX_y_ = Render__Sprite_drawAtX_y_,
};

struct ovic_NPObject_meta_vtable ovic_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct ovic_Engine__Physics__Collider_meta_vtable ovic_Engine__Physics__Collider_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Engine__Physics__Collider_getClass,
};

struct ovic_GameWorld_meta_vtable ovic_GameWorld_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = GameWorld_getClass,
};

struct ovic_Engine__Core__Transform_meta_vtable ovic_Engine__Core__Transform_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Engine__Core__Transform_getClass,
};

struct ovic_Render__Sprite_meta_vtable ovic_Render__Sprite_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Render__Sprite_getClass,
};

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Engine__Physics__Collider_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * GameWorld_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Engine__Core__Transform_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Render__Sprite_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass ovic_NPObject_class;
NPClass ovic_Engine__Physics__Collider_class;
NPClass ovic_GameWorld_class;
NPClass ovic_Engine__Core__Transform_class;
NPClass ovic_Render__Sprite_class;

void ovic_meta_init(void) {
    ovic_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &ovic_NPObject_vtable_inst,
        .class_vtable = &ovic_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    ovic_Engine__Physics__Collider_class = (NPClass){
        .name = "Engine::Physics::Collider",
        .superclass = &ovic_NPObject_class,
        .instance_size = sizeof(struct Engine__Physics__Collider),
        .vtable = &ovic_Engine__Physics__Collider_vtable_inst,
        .class_vtable = &ovic_Engine__Physics__Collider_meta_vtable_inst,
        .protocol_count = 0,
    };
    ovic_GameWorld_class = (NPClass){
        .name = "GameWorld",
        .superclass = &ovic_NPObject_class,
        .instance_size = sizeof(struct GameWorld),
        .vtable = &ovic_GameWorld_vtable_inst,
        .class_vtable = &ovic_GameWorld_meta_vtable_inst,
        .protocol_count = 0,
    };
    ovic_Engine__Core__Transform_class = (NPClass){
        .name = "Engine::Core::Transform",
        .superclass = &ovic_NPObject_class,
        .instance_size = sizeof(struct Engine__Core__Transform),
        .vtable = &ovic_Engine__Core__Transform_vtable_inst,
        .class_vtable = &ovic_Engine__Core__Transform_meta_vtable_inst,
        .protocol_count = 0,
    };
    ovic_Render__Sprite_class = (NPClass){
        .name = "Render::Sprite",
        .superclass = &ovic_NPObject_class,
        .instance_size = sizeof(struct Render__Sprite),
        .vtable = &ovic_Render__Sprite_vtable_inst,
        .class_vtable = &ovic_Render__Sprite_meta_vtable_inst,
        .protocol_count = 0,
    };
}
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
  return ovic_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
  NPObject * obj = ovic_alloc(self);
  return ovic_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return ovic_init(self);
  }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return;
  }
}

void NPObject_release(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    ovic_release(self);
  }
}

NPObject * NPObject_retain(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return ovic_retain(self);
  }
}

NPObject * Engine__Core__Transform_initWithX_y_(NPObject * self, SEL _cmd, int posX, int posY) {
  struct Engine__Core__Transform * _self = (struct Engine__Core__Transform *)self;
  {
    self = NPObject_init(self, sel_registerName("init"));
    if (self)     {
      _self->x = posX;
      _self->y = posY;
    }
    return self;
  }
}

void Engine__Core__Transform_translateByX_y_(NPObject * self, SEL _cmd, int dx, int dy) {
  struct Engine__Core__Transform * _self = (struct Engine__Core__Transform *)self;
  {
    (_self->x += dx);
    (_self->y += dy);
  }
}

NPObject * Engine__Physics__Collider_initWithType_callback_(NPObject * self, SEL _cmd, const char * type, Engine__Physics__CollisionCallback cb) {
  struct Engine__Physics__Collider * _self = (struct Engine__Physics__Collider *)self;
  {
    self = NPObject_init(self, sel_registerName("init"));
    if (self)     {
      _self->typeName = type;
      _self->onCollision = cb;
    }
    return self;
  }
}

void Engine__Physics__Collider_triggerCollisionWithForce_(NPObject * self, SEL _cmd, int force) {
  struct Engine__Physics__Collider * _self = (struct Engine__Physics__Collider *)self;
  {
    if (_self->onCollision)     {
      _self->onCollision(force);
    }
  }
}

NPObject * Render__Sprite_initWithTexture_(NPObject * self, SEL _cmd, const char * tex) {
  struct Render__Sprite * _self = (struct Render__Sprite *)self;
  {
    self = NPObject_init(self, sel_registerName("init"));
    if (self)     {
      _self->textureName = tex;
    }
    return self;
  }
}

void Render__Sprite_drawAtX_y_(NPObject * self, SEL _cmd, int x, int y) {
  struct Render__Sprite * _self = (struct Render__Sprite *)self;
  {
    printf("[渲染器] 在坐标 (%d, %d) 绘制贴图: %s\n", x, y, _self->textureName);
  }
}

void GameWorld_runLoop(NPObject * self, SEL _cmd) {
  struct GameWorld * _self = (struct GameWorld *)self;
  {
    printf("[游戏世界] 初始化游戏对象...\n");
    NPObject *__ovic_tmp_1 = (NPObject_alloc(&ovic_Engine__Core__Transform_class, sel_registerName("alloc")));
    Engine__Core__Transform * position = ((struct ovic_Engine__Core__Transform_vtable *)__ovic_tmp_1->isa->vtable)->initWithX_y_(__ovic_tmp_1, sel_registerName("initWithX:y:"), 10, 20);
    NPObject *__ovic_tmp_2 = (NPObject_alloc(&ovic_Engine__Physics__Collider_class, sel_registerName("alloc")));
    Engine__Physics__Collider * boxCollider = ((struct ovic_Engine__Physics__Collider_vtable *)__ovic_tmp_2->isa->vtable)->initWithType_callback_(__ovic_tmp_2, sel_registerName("initWithType:callback:"), "Box", ^void(int velocity) {
  printf("[碰撞警告] 触发碰撞！撞击速度: %d\n", velocity);
  ((struct ovic_Engine__Core__Transform_vtable *)(position)->isa->vtable)->translateByX_y_(position, sel_registerName("translateByX:y:"), 5, -5);
}
);
    NPObject *__ovic_tmp_3 = (NPObject_alloc(&ovic_Render__Sprite_class, sel_registerName("alloc")));
    Render__Sprite * heroSprite = ((struct ovic_Render__Sprite_vtable *)__ovic_tmp_3->isa->vtable)->initWithTexture_(__ovic_tmp_3, sel_registerName("initWithTexture:"), "hero_idle.png");
    printf("\n--- [第 1 帧] 初始状态渲染 ---\n");
    ((struct ovic_Render__Sprite_vtable *)(heroSprite)->isa->vtable)->drawAtX_y_(heroSprite, sel_registerName("drawAtX:y:"), position->x, position->y);
    printf("\n--- [第 2 帧] 触发碰撞物理事件 (预期会修改坐标) ---\n");
    ((struct ovic_Engine__Physics__Collider_vtable *)(boxCollider)->isa->vtable)->triggerCollisionWithForce_(boxCollider, sel_registerName("triggerCollisionWithForce:"), 80);
    printf("\n--- [第 3 帧] 碰撞后的重新渲染 ---\n");
    ((struct ovic_Render__Sprite_vtable *)(heroSprite)->isa->vtable)->drawAtX_y_(heroSprite, sel_registerName("drawAtX:y:"), position->x, position->y);
    ((struct ovic_NPObject_vtable *)(position)->isa->vtable)->release(position, sel_registerName("release"));
    ((struct ovic_NPObject_vtable *)(boxCollider)->isa->vtable)->release(boxCollider, sel_registerName("release"));
    ((struct ovic_NPObject_vtable *)(heroSprite)->isa->vtable)->release(heroSprite, sel_registerName("release"));
  }
}

NPObject * ovic_alloc(struct NPClass * cls);

NPObject * ovic_init(NPObject * self);

void ovic_release(NPObject * obj);

NPObject * ovic_retain(NPObject * obj);

typedef void (^CollisionCallback)(int) ;

typedef void (^Engine__Physics__CollisionCallback)(int) ;

int main(int argc, const char * argv[]) {
  ovic_meta_init();
  {
    printf("==================================================\n");
    printf(">>>    ovicc 编译器「@namespace & @using」新特性压测  <<<\n");
    printf("==================================================\n\n");
    NPObject *__ovic_tmp_4 = (NPObject_alloc(&ovic_GameWorld_class, sel_registerName("alloc")));
    GameWorld * world = ((struct ovic_NPObject_vtable *)__ovic_tmp_4->isa->vtable)->init(__ovic_tmp_4, sel_registerName("init"));
    ((struct ovic_GameWorld_vtable *)(world)->isa->vtable)->runLoop(world, sel_registerName("runLoop"));
    ((struct ovic_NPObject_vtable *)(world)->isa->vtable)->release(world, sel_registerName("release"));
    printf("\n==================================================\n");
    printf(">>>        恭喜！新命名空间与导入系统跑通！        <<<\n");
    printf("==================================================\n");
  }
  return 0;
}

