// Generated by jetic
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdint.h>
#include <stddef.h>
#include "jeti/runtime.h"


#include <string.h>

struct jeti_NPObject_vtable;
struct jeti_AI__Compute__TensorMatrix_vtable;
struct jeti_Network__Pipeline__ModelDispatcher_vtable;

#define jeti_NPObject_vtable_index_init 2
#define jeti_NPObject_vtable_index_dealloc 3
#define jeti_AI__Compute__TensorMatrix_vtable_index_initWithLabel_dimension_ 6
#define jeti_AI__Compute__TensorMatrix_vtable_index_evaluateLossWithBlock_ 7
#define jeti_Network__Pipeline__ModelDispatcher_vtable_index_initPipelineWithId_ 4
#define jeti_Network__Pipeline__ModelDispatcher_vtable_index_dispatchForwardPassWithGlobalLoss_ 5
#define jeti_Network__Pipeline__ModelDispatcher_vtable_index_dealloc 3

static const SEL __jeti_sel_initWithLabel_dimension_ = {.name = "initWithLabel_dimension_", .hash = 0x1C3E7725};
static const SEL __jeti_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __jeti_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __jeti_sel_createStandardMatrix = {.name = "createStandardMatrix", .hash = 0xEBA10409};
static const SEL __jeti_sel_createDeepQuantumMatrix = {.name = "createDeepQuantumMatrix", .hash = 0x2C0584D5};
static const SEL __jeti_sel_evaluateLossWithBlock_ = {.name = "evaluateLossWithBlock_", .hash = 0x985C6C0B};
static const SEL __jeti_sel_tensorLabel = {.name = "tensorLabel", .hash = 0x76F02EE2};
static const SEL __jeti_sel_matrixDim = {.name = "matrixDim", .hash = 0x6AECEFEA};
static const SEL __jeti_sel_initPipelineWithId_ = {.name = "initPipelineWithId_", .hash = 0x6F5BD571};
static const SEL __jeti_sel_pipelineId = {.name = "pipelineId", .hash = 0x0E72CA6E};
static const SEL __jeti_sel_inputLayer = {.name = "inputLayer", .hash = 0x4CCFB314};
static const SEL __jeti_sel_outputLayer = {.name = "outputLayer", .hash = 0x6AEA6591};
static const SEL __jeti_sel_dispatchForwardPassWithGlobalLoss_ = {.name = "dispatchForwardPassWithGlobalLoss_", .hash = 0x7F5E3862};

typedef struct NPObject NPObject;
typedef struct AI__Compute__TensorMatrix AI__Compute__TensorMatrix;
typedef struct Network__Pipeline__ModelDispatcher Network__Pipeline__ModelDispatcher;


typedef int (^LossCalculatorBlock)(int);

NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
AI__Compute__TensorMatrix * AI__Compute__TensorMatrix_createStandardMatrix(NPClass * self, SEL _cmd);
AI__Compute__TensorMatrix * AI__Compute__TensorMatrix_createDeepQuantumMatrix(NPClass * self, SEL _cmd);
NPObject * AI__Compute__TensorMatrix_initWithLabel_dimension_(NPObject * self, SEL _cmd, const char * label, int dim);
int AI__Compute__TensorMatrix_evaluateLossWithBlock_(NPObject * self, SEL _cmd, AI__Compute__LossCalculatorBlock lossBlock);
int AI__Compute__TensorMatrix_matrixDim(NPObject * self, SEL _cmd);
void AI__Compute__TensorMatrix_setMatrixDim_(NPObject * self, SEL _cmd, int value);
const char * AI__Compute__TensorMatrix_tensorLabel(NPObject * self, SEL _cmd);
NPClass * AI__Compute__TensorMatrix_getClass(NPClass * self, SEL _cmd);
NPObject * Network__Pipeline__ModelDispatcher_initPipelineWithId_(NPObject * self, SEL _cmd, const char * pid);
void Network__Pipeline__ModelDispatcher_dispatchForwardPassWithGlobalLoss_(NPObject * self, SEL _cmd, AI__Compute__LossCalculatorBlock globalLoss);
void Network__Pipeline__ModelDispatcher_dealloc(NPObject * self, SEL _cmd);
const char * Network__Pipeline__ModelDispatcher_pipelineId(NPObject * self, SEL _cmd);
AI__Compute__TensorMatrix * Network__Pipeline__ModelDispatcher_inputLayer(NPObject * self, SEL _cmd);
void Network__Pipeline__ModelDispatcher_setInputLayer_(NPObject * self, SEL _cmd, AI__Compute__TensorMatrix * value);
AI__Compute__TensorMatrix * Network__Pipeline__ModelDispatcher_outputLayer(NPObject * self, SEL _cmd);
void Network__Pipeline__ModelDispatcher_setOutputLayer_(NPObject * self, SEL _cmd, AI__Compute__TensorMatrix * value);
NPClass * Network__Pipeline__ModelDispatcher_getClass(NPClass * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NPClass jeti_NPObject_class;
extern NPClass jeti_AI__Compute__TensorMatrix_class;
extern NPClass jeti_Network__Pipeline__ModelDispatcher_class;
void jeti_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct jeti_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct jeti_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
typedef int (^LossCalculatorBlock)(int);
struct AI__Compute__TensorMatrix {
    struct NPClass *isa;
    uint32_t retain_count;
    int _matrixDim;
    const char * _tensorLabel;
};
typedef struct AI__Compute__TensorMatrix AI__Compute__TensorMatrix;
struct jeti_AI__Compute__TensorMatrix_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithLabel_dimension_)(NPObject *, SEL, const char *, int);
    int (*evaluateLossWithBlock_)(NPObject *, SEL, AI__Compute__LossCalculatorBlock);
    int (*matrixDim)(NPObject *, SEL);
    void (*setMatrixDim_)(NPObject *, SEL, int);
    const char * (*tensorLabel)(NPObject *, SEL);
};
struct jeti_AI__Compute__TensorMatrix_meta_vtable {
    AI__Compute__TensorMatrix * (*createStandardMatrix)(NPClass *, SEL);
    AI__Compute__TensorMatrix * (*createDeepQuantumMatrix)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Network__Pipeline__ModelDispatcher {
    struct NPClass *isa;
    uint32_t retain_count;
    const char * _pipelineId;
    AI__Compute__TensorMatrix * _inputLayer;
    AI__Compute__TensorMatrix * _outputLayer;
};
typedef struct Network__Pipeline__ModelDispatcher Network__Pipeline__ModelDispatcher;
struct jeti_Network__Pipeline__ModelDispatcher_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initPipelineWithId_)(NPObject *, SEL, const char *);
    void (*dispatchForwardPassWithGlobalLoss_)(NPObject *, SEL, AI__Compute__LossCalculatorBlock);
    const char * (*pipelineId)(NPObject *, SEL);
    AI__Compute__TensorMatrix * (*inputLayer)(NPObject *, SEL);
    void (*setInputLayer_)(NPObject *, SEL, AI__Compute__TensorMatrix *);
    AI__Compute__TensorMatrix * (*outputLayer)(NPObject *, SEL);
    void (*setOutputLayer_)(NPObject *, SEL, AI__Compute__TensorMatrix *);
};
struct jeti_Network__Pipeline__ModelDispatcher_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return jeti_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = jeti_alloc(self);
    return jeti_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return jeti_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &jeti_NPObject_class;
}

NPObject * jeti_alloc(struct NPClass * cls);
NPObject * jeti_init(NPObject * );
AI__Compute__TensorMatrix * AI__Compute__TensorMatrix_createStandardMatrix(NPClass * self, SEL _cmd) {
    return ({ NPObject *__jeti_tmp_0 = (NPObject_alloc(&jeti_AI__Compute__TensorMatrix_class, __jeti_sel_alloc)); ((struct jeti_AI__Compute__TensorMatrix_vtable *)__jeti_tmp_0->isa->vtable)->initWithLabel_dimension_(__jeti_tmp_0, __jeti_sel_initWithLabel_dimension_, "Dense_Layer_Tensor", 128); });
}

AI__Compute__TensorMatrix * AI__Compute__TensorMatrix_createDeepQuantumMatrix(NPClass * self, SEL _cmd) {
    return ({ NPObject *__jeti_tmp_1 = (NPObject_alloc(&jeti_AI__Compute__TensorMatrix_class, __jeti_sel_alloc)); ((struct jeti_AI__Compute__TensorMatrix_vtable *)__jeti_tmp_1->isa->vtable)->initWithLabel_dimension_(__jeti_tmp_1, __jeti_sel_initWithLabel_dimension_, "Quantum_Attention_Tensor", 1024); });
}

NPObject * AI__Compute__TensorMatrix_initWithLabel_dimension_(NPObject * self, SEL _cmd, const char * label, int dim) {
    struct AI__Compute__TensorMatrix * _self = ((struct AI__Compute__TensorMatrix *)(self));
    {
        self = NPObject_init(self, __jeti_sel_init);
        if (self) {
            {
                ((struct AI__Compute__TensorMatrix *)(self))->_tensorLabel = label;
                ((struct AI__Compute__TensorMatrix *)(self))->_matrixDim = dim;
            }
        }
        return self;
    }
}

int AI__Compute__TensorMatrix_evaluateLossWithBlock_(NPObject * self, SEL _cmd, AI__Compute__LossCalculatorBlock lossBlock) {
    struct AI__Compute__TensorMatrix * _self = ((struct AI__Compute__TensorMatrix *)(self));
    {
        if (lossBlock) {
            {
                return lossBlock(((struct AI__Compute__TensorMatrix *)(self))->_matrixDim);
            }
        }
        return ((struct AI__Compute__TensorMatrix *)(self))->_matrixDim;
    }
}

int AI__Compute__TensorMatrix_matrixDim(NPObject * self, SEL _cmd) {
    return ((struct AI::Compute::TensorMatrix *)(self))->_matrixDim;
}

void AI__Compute__TensorMatrix_setMatrixDim_(NPObject * self, SEL _cmd, int value) {
    ((struct AI__Compute__TensorMatrix *)(self))->_matrixDim = value;
}

const char * AI__Compute__TensorMatrix_tensorLabel(NPObject * self, SEL _cmd) {
    return ((struct AI::Compute::TensorMatrix *)(self))->_tensorLabel;
}

NPClass * AI__Compute__TensorMatrix_getClass(NPClass * self, SEL _cmd) {
    return &jeti_AI__Compute__TensorMatrix_class;
}

NPObject * Network__Pipeline__ModelDispatcher_initPipelineWithId_(NPObject * self, SEL _cmd, const char * pid) {
    struct Network__Pipeline__ModelDispatcher * _self = ((struct Network__Pipeline__ModelDispatcher *)(self));
    {
        self = NPObject_init(self, __jeti_sel_init);
        if (self) {
            {
                ((struct Network__Pipeline__ModelDispatcher *)(self))->_pipelineId = pid;
                ((struct Network__Pipeline__ModelDispatcher *)(self))->_inputLayer = AI__Compute__TensorMatrix_createStandardMatrix(&jeti_AI__Compute__TensorMatrix_class, __jeti_sel_createStandardMatrix);
                ((struct Network__Pipeline__ModelDispatcher *)(self))->_outputLayer = AI__Compute__TensorMatrix_createDeepQuantumMatrix(&jeti_AI__Compute__TensorMatrix_class, __jeti_sel_createDeepQuantumMatrix);
            }
        }
        return self;
    }
}

void Network__Pipeline__ModelDispatcher_dispatchForwardPassWithGlobalLoss_(NPObject * self, SEL _cmd, AI__Compute__LossCalculatorBlock globalLoss) {
    struct Network__Pipeline__ModelDispatcher * _self = ((struct Network__Pipeline__ModelDispatcher *)(self));
    {
        printf("[管线调度] 模型流水线「%s」前向传播激活：\n", ((struct Network__Pipeline__ModelDispatcher *)(self))->_pipelineId);
        int inputLoss = ((struct jeti_AI__Compute__TensorMatrix_vtable *)((struct Network__Pipeline__ModelDispatcher *)(self))->_inputLayer->isa->vtable)->evaluateLossWithBlock_(((struct Network__Pipeline__ModelDispatcher *)(self))->_inputLayer, __jeti_sel_evaluateLossWithBlock_, globalLoss);
        int outputLoss = ((struct jeti_AI__Compute__TensorMatrix_vtable *)((struct Network__Pipeline__ModelDispatcher *)(self))->_outputLayer->isa->vtable)->evaluateLossWithBlock_(((struct Network__Pipeline__ModelDispatcher *)(self))->_outputLayer, __jeti_sel_evaluateLossWithBlock_, globalLoss);
        printf("          -> 输入层张量 [%s] 计算损耗: %d\n", ((struct jeti_AI__Compute__TensorMatrix_vtable *)((struct Network__Pipeline__ModelDispatcher *)(self))->_inputLayer->isa->vtable)->tensorLabel(((struct Network__Pipeline__ModelDispatcher *)(self))->_inputLayer, __jeti_sel_tensorLabel), inputLoss);
        printf("          -> 输出层张量 [%s] 计算损耗: %d\n", ((struct jeti_AI__Compute__TensorMatrix_vtable *)((struct Network__Pipeline__ModelDispatcher *)(self))->_outputLayer->isa->vtable)->tensorLabel(((struct Network__Pipeline__ModelDispatcher *)(self))->_outputLayer, __jeti_sel_tensorLabel), outputLoss);
        printf("          -> 流水线当前收敛总残差: %d 归一化单位\n", inputLoss + outputLoss);
    }
}

void Network__Pipeline__ModelDispatcher_dealloc(NPObject * self, SEL _cmd) {
    struct Network__Pipeline__ModelDispatcher * _self = ((struct Network__Pipeline__ModelDispatcher *)(self));
    {
        jeti_release(((struct Network__Pipeline__ModelDispatcher *)(self))->_inputLayer);
        jeti_release(((struct Network__Pipeline__ModelDispatcher *)(self))->_outputLayer);
        jeti_object_dealloc(self);
    }
}

const char * Network__Pipeline__ModelDispatcher_pipelineId(NPObject * self, SEL _cmd) {
    return ((struct Network::Pipeline::ModelDispatcher *)(self))->_pipelineId;
}

AI__Compute__TensorMatrix * Network__Pipeline__ModelDispatcher_inputLayer(NPObject * self, SEL _cmd) {
    return ((struct Network::Pipeline::ModelDispatcher *)(self))->_inputLayer;
}

void Network__Pipeline__ModelDispatcher_setInputLayer_(NPObject * self, SEL _cmd, AI__Compute__TensorMatrix * value) {
    ((struct Network__Pipeline__ModelDispatcher *)(self))->_inputLayer = value;
}

AI__Compute__TensorMatrix * Network__Pipeline__ModelDispatcher_outputLayer(NPObject * self, SEL _cmd) {
    return ((struct Network::Pipeline::ModelDispatcher *)(self))->_outputLayer;
}

void Network__Pipeline__ModelDispatcher_setOutputLayer_(NPObject * self, SEL _cmd, AI__Compute__TensorMatrix * value) {
    ((struct Network__Pipeline__ModelDispatcher *)(self))->_outputLayer = value;
}

NPClass * Network__Pipeline__ModelDispatcher_getClass(NPClass * self, SEL _cmd) {
    return &jeti_Network__Pipeline__ModelDispatcher_class;
}

int main(int argc, const char * * argv) {
    jeti_autoreleasepool_t *__pool = jeti_autoreleasepool_push();
    jeti_meta_init();
    {
        jeti_autoreleasepool_t * __pool = jeti_autoreleasepool_push();
        {
            printf("====================================================================\n");
            printf(">>> jetic 编译器「全称 :: 类方法 & 复合边界表达式」回归校验大测试 <<<\n");
            printf("====================================================================\n\n");
            printf("--- 1. 测试顶级作用域直接调用全称类方法 (+ Method) ---\n");
            AI__Compute__TensorMatrix * orphanTensor = AI__Compute__TensorMatrix_createStandardMatrix(&jeti_AI__Compute__TensorMatrix_class, __jeti_sel_createStandardMatrix);
            printf("[张量工厂断言] 独立制造张量成功: %s, 维度: %d\n", ((struct jeti_AI__Compute__TensorMatrix_vtable *)orphanTensor->isa->vtable)->tensorLabel(orphanTensor, __jeti_sel_tensorLabel), ((struct jeti_AI__Compute__TensorMatrix_vtable *)orphanTensor->isa->vtable)->matrixDim(orphanTensor, __jeti_sel_matrixDim));
            printf("\n--- 2. 测试内部级联类方法的对象初始化（Dispatcher 内部装配 Tensor） ---\n");
            NPObject *__jeti_tmp_2 = (NPObject_alloc(&jeti_Network__Pipeline__ModelDispatcher_class, __jeti_sel_alloc));
            Network__Pipeline__ModelDispatcher * neuralPipeline = ((struct jeti_Network__Pipeline__ModelDispatcher_vtable *)__jeti_tmp_2->isa->vtable)->initPipelineWithId_(__jeti_tmp_2, __jeti_sel_initPipelineWithId_, "GPT-Jeti-Core-V3");
            printf("[调度报告] 管线ID: %s\n", ((struct jeti_Network__Pipeline__ModelDispatcher_vtable *)neuralPipeline->isa->vtable)->pipelineId(neuralPipeline, __jeti_sel_pipelineId));
            printf("[调度报告] 自动初始化输入节点: %s\n", ({ NPObject *__jeti_tmp_3 = (((struct jeti_Network__Pipeline__ModelDispatcher_vtable *)neuralPipeline->isa->vtable)->inputLayer(neuralPipeline, __jeti_sel_inputLayer)); ((struct jeti_AI__Compute__TensorMatrix_vtable *)__jeti_tmp_3->isa->vtable)->tensorLabel(__jeti_tmp_3, __jeti_sel_tensorLabel); }));
            printf("[调度报告] 自动初始化输出节点: %s\n", ({ NPObject *__jeti_tmp_4 = (((struct jeti_Network__Pipeline__ModelDispatcher_vtable *)neuralPipeline->isa->vtable)->outputLayer(neuralPipeline, __jeti_sel_outputLayer)); ((struct jeti_AI__Compute__TensorMatrix_vtable *)__jeti_tmp_4->isa->vtable)->tensorLabel(__jeti_tmp_4, __jeti_sel_tensorLabel); }));
            printf("\n--- 3. 测试 Block 进行跨空间多层拓扑投递 ---\n");
            AI__Compute__LossCalculatorBlock optimizerBlock = ^int(int dim) {
    if (dim > 500) {
        {
            return dim / 3 + 200;
        }
    } else {
        {
            return dim * 3;
        }
    }
}
;
            ((struct jeti_Network__Pipeline__ModelDispatcher_vtable *)neuralPipeline->isa->vtable)->dispatchForwardPassWithGlobalLoss_(neuralPipeline, __jeti_sel_dispatchForwardPassWithGlobalLoss_, optimizerBlock);
            printf("\n[闭包状态断言] 经过深度传递执行后的闭包状态：\n");
            printf("          -> 闭包内部无捕获变量（C99 兼容模式）\n");
            printf("\n--- 4. 极限边界回归：将全称类方法嵌套于三元表达式中 ---\n");
            int runTrainingFlag = 1;
            AI__Compute__TensorMatrix * evilClonedTensor = runTrainingFlag > 0 ? AI__Compute__TensorMatrix_createDeepQuantumMatrix(&jeti_AI__Compute__TensorMatrix_class, __jeti_sel_createDeepQuantumMatrix) : NULL;
            printf("[极限语法断言] 三元表达式中的类方法调用完美解析！\n");
            printf("          -> 动态回归生产的张量标签: %s\n", ((struct jeti_AI__Compute__TensorMatrix_vtable *)evilClonedTensor->isa->vtable)->tensorLabel(evilClonedTensor, __jeti_sel_tensorLabel));
            printf("\n--- 5. 正在释放 AI 神经网络计算拓扑流内存... ---\n");
            jeti_release(orphanTensor);
            jeti_release(neuralPipeline);
            jeti_release(evilClonedTensor);
            printf("\n====================================================================\n");
            printf(">>> 恭喜！回归压测大获全胜，你刚才修复的 Bug 已经彻底稳固了！ <<<\n");
            printf("====================================================================\n");
        }
        jeti_autoreleasepool_pop(__pool);
    }
    return 0;
    jeti_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct jeti_NPObject_vtable jeti_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct jeti_AI__Compute__TensorMatrix_vtable jeti_AI__Compute__TensorMatrix_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithLabel_dimension_ = AI__Compute__TensorMatrix_initWithLabel_dimension_,
    .evaluateLossWithBlock_ = AI__Compute__TensorMatrix_evaluateLossWithBlock_,
    .matrixDim = AI__Compute__TensorMatrix_matrixDim,
    .setMatrixDim_ = AI__Compute__TensorMatrix_setMatrixDim_,
    .tensorLabel = AI__Compute__TensorMatrix_tensorLabel,
};

struct jeti_Network__Pipeline__ModelDispatcher_vtable jeti_Network__Pipeline__ModelDispatcher_vtable_inst = {
    .init = NPObject_init,
    .dealloc = Network__Pipeline__ModelDispatcher_dealloc,
    .initPipelineWithId_ = Network__Pipeline__ModelDispatcher_initPipelineWithId_,
    .dispatchForwardPassWithGlobalLoss_ = Network__Pipeline__ModelDispatcher_dispatchForwardPassWithGlobalLoss_,
    .pipelineId = Network__Pipeline__ModelDispatcher_pipelineId,
    .inputLayer = Network__Pipeline__ModelDispatcher_inputLayer,
    .setInputLayer_ = Network__Pipeline__ModelDispatcher_setInputLayer_,
    .outputLayer = Network__Pipeline__ModelDispatcher_outputLayer,
    .setOutputLayer_ = Network__Pipeline__ModelDispatcher_setOutputLayer_,
};

struct jeti_NPObject_meta_vtable jeti_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct jeti_AI__Compute__TensorMatrix_meta_vtable jeti_AI__Compute__TensorMatrix_meta_vtable_inst = {
    .createStandardMatrix = AI__Compute__TensorMatrix_createStandardMatrix,
    .createDeepQuantumMatrix = AI__Compute__TensorMatrix_createDeepQuantumMatrix,
    .class = AI__Compute__TensorMatrix_getClass,
};

struct jeti_Network__Pipeline__ModelDispatcher_meta_vtable jeti_Network__Pipeline__ModelDispatcher_meta_vtable_inst = {
    .class = Network__Pipeline__ModelDispatcher_getClass,
};

NPClass jeti_NPObject_class;
NPClass jeti_AI__Compute__TensorMatrix_class;
NPClass jeti_Network__Pipeline__ModelDispatcher_class;

void jeti_meta_init(void) {
    jeti_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &jeti_NPObject_vtable_inst,
        .class_vtable = &jeti_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_AI__Compute__TensorMatrix_class = (NPClass){
        .name = "AI__Compute__TensorMatrix",
        .superclass = &jeti_NPObject_class,
        .instance_size = sizeof(struct AI__Compute__TensorMatrix),
        .vtable = &jeti_AI__Compute__TensorMatrix_vtable_inst,
        .class_vtable = &jeti_AI__Compute__TensorMatrix_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_Network__Pipeline__ModelDispatcher_class = (NPClass){
        .name = "Network__Pipeline__ModelDispatcher",
        .superclass = &jeti_NPObject_class,
        .instance_size = sizeof(struct Network__Pipeline__ModelDispatcher),
        .vtable = &jeti_Network__Pipeline__ModelDispatcher_vtable_inst,
        .class_vtable = &jeti_Network__Pipeline__ModelDispatcher_meta_vtable_inst,
        .protocol_count = 0,
    };
}
