// Generated by galdc
#include <stdint.h>
#include <stddef.h>
#include "gald/runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define _NF_INT_CODING   "i"
#define _NF_STR_CODING   "*"
#define _NF_OBJ_CODING   "@"


#include <string.h>

struct gald_NFObject_vtable;
struct gald_NFException_vtable;
struct gald_NFJsonNode_vtable;
struct gald_NFJsonStringNode_vtable;
struct gald_NFJsonNumberNode_vtable;
struct gald_NFJsonParser_vtable;

#define gald_NFObject_vtable_index_init 2
#define gald_NFObject_vtable_index_dealloc 3
#define gald_NFException_vtable_index_initWithName_reason_ 4
#define gald_NFJsonNode_vtable_index_typeSignature 5
#define gald_NFJsonNode_vtable_index_asString 6
#define gald_NFJsonNode_vtable_index_asInteger 7
#define gald_NFJsonStringNode_vtable_index_initWithString_ 8
#define gald_NFJsonStringNode_vtable_index_typeSignature 5
#define gald_NFJsonStringNode_vtable_index_asString 6
#define gald_NFJsonStringNode_vtable_index_asInteger 7
#define gald_NFJsonNumberNode_vtable_index_initWithInteger_ 8
#define gald_NFJsonNumberNode_vtable_index_typeSignature 5
#define gald_NFJsonNumberNode_vtable_index_asInteger 7
#define gald_NFJsonNumberNode_vtable_index_asString 6
#define gald_NFJsonParser_vtable_index_parseRawTokens_node_ 4

static const SEL __gald_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __gald_sel_initWithString_ = {.name = "initWithString_", .hash = 0x5515BD13};
static const SEL __gald_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __gald_sel_initWithName_reason_ = {.name = "initWithName_reason_", .hash = 0x6A6B47FA};
static const SEL __gald_sel_typeSignature = {.name = "typeSignature", .hash = 0x8BEE1745};
static const SEL __gald_sel_asString = {.name = "asString", .hash = 0xC22E4BE0};
static const SEL __gald_sel_name = {.name = "name", .hash = 0x8D39BDE6};
static const SEL __gald_sel_reason = {.name = "reason", .hash = 0xF8A35E19};
static const SEL __gald_sel_nodeWithSerializableObject_ = {.name = "nodeWithSerializableObject_", .hash = 0xC5F1E166};
static const SEL __gald_sel_initWithInteger_ = {.name = "initWithInteger_", .hash = 0x28D4726C};
static const SEL __gald_sel_parseRawTokens_node_ = {.name = "parseRawTokens_node_", .hash = 0xE23634CA};

typedef struct NFObject NFObject;
typedef struct NFException NFException;
typedef struct NFJsonNode NFJsonNode;
typedef struct NFJsonStringNode NFJsonStringNode;
typedef struct NFJsonNumberNode NFJsonNumberNode;
typedef struct NFJsonParser NFJsonParser;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
NFObject * NFException_initWithName_reason_(NFObject * self, SEL _cmd, const char * aName, const char * aReason);
const char * NFException_name(NFObject * self, SEL _cmd);
const char * NFException_reason(NFObject * self, SEL _cmd);
NFClass * NFException_getClass(NFClass * self, SEL _cmd);
NFJsonNode * NFJsonNode_nodeWithSerializableObject_(NFClass * self, SEL _cmd, NFObject * obj);
const char * NFJsonNode_typeSignature(NFObject * self, SEL _cmd);
const char * NFJsonNode_asString(NFObject * self, SEL _cmd);
int NFJsonNode_asInteger(NFObject * self, SEL _cmd);
NFClass * NFJsonNode_getClass(NFClass * self, SEL _cmd);
NFObject * NFJsonStringNode_initWithString_(NFObject * self, SEL _cmd, const char * str);
const char * NFJsonStringNode_typeSignature(NFObject * self, SEL _cmd);
const char * NFJsonStringNode_asString(NFObject * self, SEL _cmd);
int NFJsonStringNode_asInteger(NFObject * self, SEL _cmd);
NFClass * NFJsonStringNode_getClass(NFClass * self, SEL _cmd);
NFObject * NFJsonNumberNode_initWithInteger_(NFObject * self, SEL _cmd, int val);
const char * NFJsonNumberNode_typeSignature(NFObject * self, SEL _cmd);
int NFJsonNumberNode_asInteger(NFObject * self, SEL _cmd);
const char * NFJsonNumberNode_asString(NFObject * self, SEL _cmd);
NFClass * NFJsonNumberNode_getClass(NFClass * self, SEL _cmd);
void NFJsonParser_parseRawTokens_node_(NFObject * self, SEL _cmd, const char * tokens, NFJsonNode * node);
NFClass * NFJsonParser_getClass(NFClass * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NFClass gald_NFObject_class;
extern NFClass gald_NFException_class;
extern NFClass gald_NFJsonNode_class;
extern NFClass gald_NFJsonStringNode_class;
extern NFClass gald_NFJsonNumberNode_class;
extern NFClass gald_NFJsonParser_class;
void gald_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct gald_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct gald_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct NFException {
    struct NFClass *isa;
    uint32_t retain_count;
    const char * _name;
    const char * _reason;
    NFObject * _userInfo;
};
typedef struct NFException NFException;
struct gald_NFException_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    NFObject * (*initWithName_reason_)(NFObject *, SEL, const char *, const char *);
    const char * (*name)(NFObject *, SEL);
    const char * (*reason)(NFObject *, SEL);
};
struct gald_NFException_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
struct NFJsonNode {
    struct NFClass *isa;
    uint32_t retain_count;
    int _nodeType;
};
typedef struct NFJsonNode NFJsonNode;
struct gald_NFJsonNode_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    const char * (*typeSignature)(NFObject *, SEL);
    const char * (*asString)(NFObject *, SEL);
    int (*asInteger)(NFObject *, SEL);
};
struct gald_NFJsonNode_meta_vtable {
    NFJsonNode * (*nodeWithSerializableObject_)(NFClass *, SEL, NFObject *);
    NFClass * (*class)(NFClass *, SEL);
};
struct NFJsonStringNode {
    struct NFClass *isa;
    uint32_t retain_count;
    int _nodeType;
    const char * _stringValue;
};
typedef struct NFJsonStringNode NFJsonStringNode;
struct gald_NFJsonStringNode_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    const char * (*typeSignature)(NFObject *, SEL);
    const char * (*asString)(NFObject *, SEL);
    int (*asInteger)(NFObject *, SEL);
    NFObject * (*initWithString_)(NFObject *, SEL, const char *);
};
struct gald_NFJsonStringNode_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
struct NFJsonNumberNode {
    struct NFClass *isa;
    uint32_t retain_count;
    int _nodeType;
    int _intValue;
};
typedef struct NFJsonNumberNode NFJsonNumberNode;
struct gald_NFJsonNumberNode_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    const char * (*typeSignature)(NFObject *, SEL);
    const char * (*asString)(NFObject *, SEL);
    int (*asInteger)(NFObject *, SEL);
    NFObject * (*initWithInteger_)(NFObject *, SEL, int);
};
struct gald_NFJsonNumberNode_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
struct NFJsonParser {
    struct NFClass *isa;
    uint32_t retain_count;
    int parseState;
};
typedef struct NFJsonParser NFJsonParser;
struct gald_NFJsonParser_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    void (*parseRawTokens_node_)(NFObject *, SEL, const char *, NFJsonNode *);
};
struct gald_NFJsonParser_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return gald_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = gald_alloc(self);
    return gald_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return gald_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFObject_class;
}

NFObject * gald_alloc(struct NFClass * cls);
NFObject * gald_init(NFObject * );
NFObject * NFException_initWithName_reason_(NFObject * self, SEL _cmd, const char * aName, const char * aReason) {
    struct NFException * _self = ((struct NFException *)(self));
    {
        self = NFObject_init(self, __gald_sel_init);
        if (self) {
            {
                ((struct NFException *)(self))->_name = aName;
                ((struct NFException *)(self))->_reason = aReason;
                ((struct NFException *)(self))->_userInfo = NULL;
            }
        }
        return self;
    }
}

const char * NFException_name(NFObject * self, SEL _cmd) {
    return ((struct NFException *)(self))->_name;
}

const char * NFException_reason(NFObject * self, SEL _cmd) {
    return ((struct NFException *)(self))->_reason;
}

NFClass * NFException_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFException_class;
}

NFJsonNode * NFJsonNode_nodeWithSerializableObject_(NFClass * self, SEL _cmd, NFObject * obj) {
    if (obj == NULL) {
        return NULL;
    }
    return ({ NFObject *__gald_tmp_0 = (NFObject_alloc(&gald_NFJsonStringNode_class, __gald_sel_alloc)); ((struct gald_NFJsonStringNode_vtable *)__gald_tmp_0->isa->vtable)->initWithString_(__gald_tmp_0, __gald_sel_initWithString_, ((const char *)(obj))); });
}

const char * NFJsonNode_typeSignature(NFObject * self, SEL _cmd) {
    struct NFJsonNode * _self = ((struct NFJsonNode *)(self));
    {
        return _NF_OBJ_CODING;
    }
}

const char * NFJsonNode_asString(NFObject * self, SEL _cmd) {
    struct NFJsonNode * _self = ((struct NFJsonNode *)(self));
    {
        return "";
    }
}

int NFJsonNode_asInteger(NFObject * self, SEL _cmd) {
    struct NFJsonNode * _self = ((struct NFJsonNode *)(self));
    {
        return 0;
    }
}

NFClass * NFJsonNode_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFJsonNode_class;
}

NFObject * NFJsonStringNode_initWithString_(NFObject * self, SEL _cmd, const char * str) {
    struct NFJsonStringNode * _self = ((struct NFJsonStringNode *)(self));
    {
        self = NFObject_init(self, __gald_sel_init);
        if (self) {
            {
                ((struct NFJsonStringNode *)(self))->_nodeType = 1;
                ((struct NFJsonStringNode *)(self))->_stringValue = str;
            }
        }
        return self;
    }
}

const char * NFJsonStringNode_typeSignature(NFObject * self, SEL _cmd) {
    struct NFJsonStringNode * _self = ((struct NFJsonStringNode *)(self));
    {
        return _NF_STR_CODING;
    }
}

const char * NFJsonStringNode_asString(NFObject * self, SEL _cmd) {
    struct NFJsonStringNode * _self = ((struct NFJsonStringNode *)(self));
    {
        return ((struct NFJsonStringNode *)(self))->_stringValue;
    }
}

int NFJsonStringNode_asInteger(NFObject * self, SEL _cmd) {
    struct NFJsonStringNode * _self = ((struct NFJsonStringNode *)(self));
    {
        return atoi(((struct NFJsonStringNode *)(self))->_stringValue);
    }
}

NFClass * NFJsonStringNode_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFJsonStringNode_class;
}

NFObject * NFJsonNumberNode_initWithInteger_(NFObject * self, SEL _cmd, int val) {
    struct NFJsonNumberNode * _self = ((struct NFJsonNumberNode *)(self));
    {
        self = NFObject_init(self, __gald_sel_init);
        if (self) {
            {
                ((struct NFJsonNumberNode *)(self))->_nodeType = 2;
                ((struct NFJsonNumberNode *)(self))->_intValue = val;
            }
        }
        return self;
    }
}

const char * NFJsonNumberNode_typeSignature(NFObject * self, SEL _cmd) {
    struct NFJsonNumberNode * _self = ((struct NFJsonNumberNode *)(self));
    {
        return _NF_INT_CODING;
    }
}

int NFJsonNumberNode_asInteger(NFObject * self, SEL _cmd) {
    struct NFJsonNumberNode * _self = ((struct NFJsonNumberNode *)(self));
    {
        return ((struct NFJsonNumberNode *)(self))->_intValue;
    }
}

const char * NFJsonNumberNode_asString(NFObject * self, SEL _cmd) {
    struct NFJsonNumberNode * _self = ((struct NFJsonNumberNode *)(self));
    {
        char buf[16];
        sprintf(buf, "%d", ((struct NFJsonNumberNode *)(self))->_intValue);
        return buf;
    }
}

NFClass * NFJsonNumberNode_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFJsonNumberNode_class;
}

void NFJsonParser_parseRawTokens_node_(NFObject * self, SEL _cmd, const char * tokens, NFJsonNode * node) {
    struct NFJsonParser * _self = ((struct NFJsonParser *)(self));
    {
        printf("[解析器] 开始解析 Token 序列: %s\n", tokens);
        {
            id __gald_exception_0 = NULL;
            __gald_try_0:
            {
                ((struct NFJsonParser *)(self))->parseState = 1;
                if (tokens == NULL || strlen(tokens) == 0) {
                    {
                        NFObject *__gald_tmp_1 = (NFObject_alloc(&gald_NFException_class, __gald_sel_alloc));
                        NFException * ex = ((struct gald_NFException_vtable *)__gald_tmp_1->isa->vtable)->initWithName_reason_(__gald_tmp_1, __gald_sel_initWithName_reason_, "NFJsonParseException", "Token 序列为空，无法解析结构");
                        {
                            __gald_exception_0 = ex;
                            goto __gald_catch_0;
                        }
                    }
                }
                if (strcmp(((struct gald_NFJsonNode_vtable *)node->isa->vtable)->typeSignature(node, __gald_sel_typeSignature), _NF_STR_CODING) == 0) {
                    {
                        printf("[解析器断言] 目标是一个字符串类簇节点，安全转换值: %s\n", ((struct gald_NFJsonNode_vtable *)node->isa->vtable)->asString(node, __gald_sel_asString));
                    }
                } else {
                    {
                        NFObject *__gald_tmp_2 = (NFObject_alloc(&gald_NFException_class, __gald_sel_alloc));
                        NFException * ex = ((struct gald_NFException_vtable *)__gald_tmp_2->isa->vtable)->initWithName_reason_(__gald_tmp_2, __gald_sel_initWithName_reason_, "NFMismatchTypeException", "预期需要 String 类型节点，但收到了不匹配的节点签名");
                        {
                            __gald_exception_0 = ex;
                            goto __gald_catch_0;
                        }
                    }
                }
            }
            goto __gald_finally_0;
            __gald_catch_0:
            id exception;
            exception = __gald_exception_0;
            {
                printf("\n【@catch 捕获异常】\n");
                printf("异常名称: %s\n", ((struct gald_NFException_vtable *)exception->isa->vtable)->name(exception, __gald_sel_name));
                printf("错误原因: %s\n", ((struct gald_NFException_vtable *)exception->isa->vtable)->reason(exception, __gald_sel_reason));
                ((struct NFJsonParser *)(self))->parseState = -1;
                gald_release(exception);
            }
            goto __gald_finally_0;
            __gald_catch_0_1:
            id unknownException;
            unknownException = __gald_exception_0;
            {
                printf("【@catch 捕获未知错误】\n");
                ((struct NFJsonParser *)(self))->parseState = -2;
            }
            goto __gald_finally_0;
            __gald_finally_0:
            ;
        }
    }
}

NFClass * NFJsonParser_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFJsonParser_class;
}

int main(int argc, const char * * argv) {
    gald_autoreleasepool_t *__pool = gald_autoreleasepool_push();
    gald_meta_init();
    {
        gald_autoreleasepool_t * __pool = gald_autoreleasepool_push();
        {
            printf(">>> 开始 NFFoundation 终极运行时与异常黑魔法测试 <<<\n\n");
            NFObject *__gald_tmp_3 = (NFObject_alloc(&gald_NFJsonParser_class, __gald_sel_alloc));
            NFJsonParser * parser = ((struct gald_NFObject_vtable *)__gald_tmp_3->isa->vtable)->init(__gald_tmp_3, __gald_sel_init);
            printf("--- 测试点 1: 类簇动态工厂创建 ---\n");
            NFJsonNode * strNode = NFJsonNode_nodeWithSerializableObject_(&gald_NFJsonNode_class, __gald_sel_nodeWithSerializableObject_, "2026-Spaceship");
            NFObject *__gald_tmp_4 = (NFObject_alloc(&gald_NFJsonNumberNode_class, __gald_sel_alloc));
            NFJsonNode * numNode = ((struct gald_NFJsonNumberNode_vtable *)__gald_tmp_4->isa->vtable)->initWithInteger_(__gald_tmp_4, __gald_sel_initWithInteger_, 888);
            printf("\n--- 测试点 2: 正常解析（匹配签名） ---\n");
            ((struct gald_NFJsonParser_vtable *)parser->isa->vtable)->parseRawTokens_node_(parser, __gald_sel_parseRawTokens_node_, "{\"ship\": \"2026-Spaceship\"}", strNode);
            printf("\n--- 测试点 3: 异常触发（将数字节点送入需要字符串的解析器） ---\n");
            ((struct gald_NFJsonParser_vtable *)parser->isa->vtable)->parseRawTokens_node_(parser, __gald_sel_parseRawTokens_node_, "{\"count\": 888}", numNode);
            printf("\n--- 测试点 4: 异常触发（送入空字符串，测试 @throw 逻辑） ---\n");
            ((struct gald_NFJsonParser_vtable *)parser->isa->vtable)->parseRawTokens_node_(parser, __gald_sel_parseRawTokens_node_, NULL, strNode);
            printf("\n>>> 正在注销运行时上下文并回收内存... <<<\n");
            gald_release(strNode);
            gald_release(numNode);
            gald_release(parser);
            printf(">>> 终极编译测试圆满完成！ <<<\n");
        }
        gald_autoreleasepool_pop(__pool);
    }
    return 0;
    gald_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct gald_NFObject_vtable gald_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct gald_NFException_vtable gald_NFException_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .initWithName_reason_ = NFException_initWithName_reason_,
    .name = NFException_name,
    .reason = NFException_reason,
};

struct gald_NFJsonNode_vtable gald_NFJsonNode_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .typeSignature = NFJsonNode_typeSignature,
    .asString = NFJsonNode_asString,
    .asInteger = NFJsonNode_asInteger,
};

struct gald_NFJsonStringNode_vtable gald_NFJsonStringNode_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .typeSignature = NFJsonStringNode_typeSignature,
    .asString = NFJsonStringNode_asString,
    .asInteger = NFJsonStringNode_asInteger,
    .initWithString_ = NFJsonStringNode_initWithString_,
};

struct gald_NFJsonNumberNode_vtable gald_NFJsonNumberNode_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .typeSignature = NFJsonNumberNode_typeSignature,
    .asString = NFJsonNumberNode_asString,
    .asInteger = NFJsonNumberNode_asInteger,
    .initWithInteger_ = NFJsonNumberNode_initWithInteger_,
};

struct gald_NFJsonParser_vtable gald_NFJsonParser_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .parseRawTokens_node_ = NFJsonParser_parseRawTokens_node_,
};

struct gald_NFObject_meta_vtable gald_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct gald_NFException_meta_vtable gald_NFException_meta_vtable_inst = {
    .class = NFException_getClass,
};

struct gald_NFJsonNode_meta_vtable gald_NFJsonNode_meta_vtable_inst = {
    .nodeWithSerializableObject_ = NFJsonNode_nodeWithSerializableObject_,
    .class = NFJsonNode_getClass,
};

struct gald_NFJsonStringNode_meta_vtable gald_NFJsonStringNode_meta_vtable_inst = {
    .class = NFJsonStringNode_getClass,
};

struct gald_NFJsonNumberNode_meta_vtable gald_NFJsonNumberNode_meta_vtable_inst = {
    .class = NFJsonNumberNode_getClass,
};

struct gald_NFJsonParser_meta_vtable gald_NFJsonParser_meta_vtable_inst = {
    .class = NFJsonParser_getClass,
};

NFClass gald_NFObject_class;
NFClass gald_NFException_class;
NFClass gald_NFJsonNode_class;
NFClass gald_NFJsonStringNode_class;
NFClass gald_NFJsonNumberNode_class;
NFClass gald_NFJsonParser_class;

void gald_meta_init(void) {
    gald_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &gald_NFObject_vtable_inst,
        .class_vtable = &gald_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_NFException_class = (NFClass){
        .name = "NFException",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct NFException),
        .vtable = &gald_NFException_vtable_inst,
        .class_vtable = &gald_NFException_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_NFJsonNode_class = (NFClass){
        .name = "NFJsonNode",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct NFJsonNode),
        .vtable = &gald_NFJsonNode_vtable_inst,
        .class_vtable = &gald_NFJsonNode_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_NFJsonStringNode_class = (NFClass){
        .name = "NFJsonStringNode",
        .superclass = &gald_NFJsonNode_class,
        .instance_size = sizeof(struct NFJsonStringNode),
        .vtable = &gald_NFJsonStringNode_vtable_inst,
        .class_vtable = &gald_NFJsonStringNode_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_NFJsonNumberNode_class = (NFClass){
        .name = "NFJsonNumberNode",
        .superclass = &gald_NFJsonNode_class,
        .instance_size = sizeof(struct NFJsonNumberNode),
        .vtable = &gald_NFJsonNumberNode_vtable_inst,
        .class_vtable = &gald_NFJsonNumberNode_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_NFJsonParser_class = (NFClass){
        .name = "NFJsonParser",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct NFJsonParser),
        .vtable = &gald_NFJsonParser_vtable_inst,
        .class_vtable = &gald_NFJsonParser_meta_vtable_inst,
        .protocol_count = 0,
    };
}
