// Generated by ovicc
#include <stdint.h>
#include <stddef.h>
#include "ovic/runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#include <string.h>

struct ovic_NPObject_vtable;
struct ovic_NPShadowGhost_vtable;
struct ovic_NPScopeMixer_vtable;

#define ovic_NPObject_vtable_index_init 2
#define ovic_NPObject_vtable_index_dealloc 3
#define ovic_NPShadowGhost_vtable_index_initWithId_ 4
#define ovic_NPShadowGhost_vtable_index_dealloc 3
#define ovic_NPScopeMixer_vtable_index_triggerScopeChaos 4

static const SEL __ovic_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __ovic_sel_initWithId_ = {.name = "initWithId_", .hash = 0x8CE5C4CB};
static const SEL __ovic_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __ovic_sel_triggerScopeChaos = {.name = "triggerScopeChaos", .hash = 0xBC5E90F3};

typedef struct NPObject NPObject;
typedef struct NPShadowGhost NPShadowGhost;
typedef struct NPScopeMixer NPScopeMixer;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * NPShadowGhost_initWithId_(NPObject * self, SEL _cmd, int gid);
void NPShadowGhost_dealloc(NPObject * self, SEL _cmd);
NPClass * NPShadowGhost_getClass(NPClass * self, SEL _cmd);
NPObject * NPScopeMixer_triggerScopeChaos(NPObject * self, SEL _cmd);
NPClass * NPScopeMixer_getClass(NPClass * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NPClass ovic_NPObject_class;
extern NPClass ovic_NPShadowGhost_class;
extern NPClass ovic_NPScopeMixer_class;
void ovic_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct ovic_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct ovic_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct NPShadowGhost {
    struct NPClass *isa;
    uint32_t retain_count;
    int ghostId;
};
typedef struct NPShadowGhost NPShadowGhost;
struct ovic_NPShadowGhost_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithId_)(NPObject *, SEL, int);
};
struct ovic_NPShadowGhost_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPScopeMixer {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct NPScopeMixer NPScopeMixer;
struct ovic_NPScopeMixer_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*triggerScopeChaos)(NPObject *, SEL);
};
struct ovic_NPScopeMixer_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return ovic_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = ovic_alloc(self);
    return ovic_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return ovic_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &ovic_NPObject_class;
}

NPObject * ovic_alloc(struct NPClass * cls);
NPObject * ovic_init(NPObject * );
NPObject * NPShadowGhost_initWithId_(NPObject * self, SEL _cmd, int gid) {
    struct NPShadowGhost * _self = ((struct NPShadowGhost *)(self));
    {
        self = NPObject_init(self, __ovic_sel_init);
        if (self) {
            {
                ((struct NPShadowGhost *)(self))->ghostId = gid;
            }
        }
        return self;
    }
}

void NPShadowGhost_dealloc(NPObject * self, SEL _cmd) {
    struct NPShadowGhost * _self = ((struct NPShadowGhost *)(self));
    {
        printf("[生命周期日志] Ghost-%d 顺利触发 dealloc 彻底销毁。\n", ((struct NPShadowGhost *)(self))->ghostId);
        ovic_object_dealloc(self);
    }
}

NPClass * NPShadowGhost_getClass(NPClass * self, SEL _cmd) {
    return &ovic_NPShadowGhost_class;
}

NPObject * NPScopeMixer_triggerScopeChaos(NPObject * self, SEL _cmd) {
    struct NPScopeMixer * _self = ((struct NPScopeMixer *)(self));
    {
        printf("[作用域测试] 启动顶级作用域环境...\n");
        int x = 100;
        NPObject * escapedObject = NULL;
        {
            ovic_autoreleasepool_t * __pool = ovic_autoreleasepool_push();
            {
                NPObject *__ovic_tmp_0 = (NPObject_alloc(&ovic_NPShadowGhost_class, __ovic_sel_alloc));
                NPShadowGhost * x = ((struct ovic_NPShadowGhost_vtable *)__ovic_tmp_0->isa->vtable)->initWithId_(__ovic_tmp_0, __ovic_sel_initWithId_, 1);
                printf("[一层遮蔽内] 局部对象 x 的 ghostId = %d (顶级整型 x 此时被隐藏)\n", ((struct NPShadowGhost *)(x))->ghostId);
                if (((struct NPShadowGhost *)(x))->ghostId > 0) {
                    {
                        {
                            ovic_autoreleasepool_t * __pool = ovic_autoreleasepool_push();
                            {
                                const char * x = "GHOST_STRING_MARKER";
                                printf("[二层遮蔽内] 嵌套字符串 x = %s\n", x);
                                NPObject *__ovic_tmp_1 = (NPObject_alloc(&ovic_NPShadowGhost_class, __ovic_sel_alloc));
                                NPShadowGhost * ghost2 = ((struct ovic_NPShadowGhost_vtable *)__ovic_tmp_1->isa->vtable)->initWithId_(__ovic_tmp_1, __ovic_sel_initWithId_, 999);
                                escapedObject = ghost2;
                            }
                            ovic_autoreleasepool_pop(__pool);
                        }
                        printf("[退出二层pool] 成功回到一层作用域。\n");
                    }
                }
                ovic_release(x);
            }
            ovic_autoreleasepool_pop(__pool);
        }
        printf("[回到顶级作用域] 遮蔽解除，整型 x 重新复活，值 = %d\n", x);
        return escapedObject;
    }
}

NPClass * NPScopeMixer_getClass(NPClass * self, SEL _cmd) {
    return &ovic_NPScopeMixer_class;
}

int main(int argc, const char * * argv) {
    ovic_autoreleasepool_t *__pool = ovic_autoreleasepool_push();
    ovic_meta_init();
    {
        ovic_autoreleasepool_t * __pool = ovic_autoreleasepool_push();
        {
            printf("==================================================\n");
            printf(">>>    ovicc 编译器「阴阳作用域遮蔽与逃逸」压测    <<<\n");
            printf("==================================================\n\n");
            NPObject *__ovic_tmp_2 = (NPObject_alloc(&ovic_NPScopeMixer_class, __ovic_sel_alloc));
            NPScopeMixer * mixer = ((struct ovic_NPObject_vtable *)__ovic_tmp_2->isa->vtable)->init(__ovic_tmp_2, __ovic_sel_init);
            printf("--- 开始执行多层遮蔽与逃逸混淆逻辑 ---\n");
            NPObject * resultGhost = ((struct ovic_NPScopeMixer_vtable *)mixer->isa->vtable)->triggerScopeChaos(mixer, __ovic_sel_triggerScopeChaos);
            printf("\n--- 检查逃逸对象的存活状态 ---\n");
            if (resultGhost != NULL) {
                {
                    NPShadowGhost * finalGhost = ((NPShadowGhost *)(resultGhost));
                    printf("[主程序验证] 逃逸对象成功被顶层捕获！GhostID: %d\n", ((struct NPShadowGhost *)(finalGhost))->ghostId);
                    printf("[主程序销毁] 手动释放逃逸对象...\n");
                    ovic_release(finalGhost);
                }
            }
            ovic_release(mixer);
            printf("\n==================================================\n");
            printf(">>>      神了！同名变量多类型遮蔽完全难不倒你！    <<<\n");
            printf("==================================================\n");
        }
        ovic_autoreleasepool_pop(__pool);
    }
    return 0;
    ovic_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct ovic_NPObject_vtable ovic_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct ovic_NPShadowGhost_vtable ovic_NPShadowGhost_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPShadowGhost_dealloc,
    .initWithId_ = NPShadowGhost_initWithId_,
};

struct ovic_NPScopeMixer_vtable ovic_NPScopeMixer_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .triggerScopeChaos = NPScopeMixer_triggerScopeChaos,
};

struct ovic_NPObject_meta_vtable ovic_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct ovic_NPShadowGhost_meta_vtable ovic_NPShadowGhost_meta_vtable_inst = {
    .class = NPShadowGhost_getClass,
};

struct ovic_NPScopeMixer_meta_vtable ovic_NPScopeMixer_meta_vtable_inst = {
    .class = NPScopeMixer_getClass,
};

NPClass ovic_NPObject_class;
NPClass ovic_NPShadowGhost_class;
NPClass ovic_NPScopeMixer_class;

void ovic_meta_init(void) {
    ovic_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &ovic_NPObject_vtable_inst,
        .class_vtable = &ovic_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    ovic_NPShadowGhost_class = (NPClass){
        .name = "NPShadowGhost",
        .superclass = &ovic_NPObject_class,
        .instance_size = sizeof(struct NPShadowGhost),
        .vtable = &ovic_NPShadowGhost_vtable_inst,
        .class_vtable = &ovic_NPShadowGhost_meta_vtable_inst,
        .protocol_count = 0,
    };
    ovic_NPScopeMixer_class = (NPClass){
        .name = "NPScopeMixer",
        .superclass = &ovic_NPObject_class,
        .instance_size = sizeof(struct NPScopeMixer),
        .vtable = &ovic_NPScopeMixer_vtable_inst,
        .class_vtable = &ovic_NPScopeMixer_meta_vtable_inst,
        .protocol_count = 0,
    };
}
