// Generated by nepac
#include <stdint.h>
#include <stddef.h>
#include "nepa/runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>


#include <string.h>

struct nepa_NPObject_vtable;
struct nepa_NPShadowGhost_vtable;
struct nepa_NPScopeMixer_vtable;

#define nepa_NPObject_vtable_index_init 2
#define nepa_NPObject_vtable_index_dealloc 3
#define nepa_NPShadowGhost_vtable_index_initWithId_ 4
#define nepa_NPShadowGhost_vtable_index_dealloc 3
#define nepa_NPScopeMixer_vtable_index_triggerScopeChaos 4

static const SEL __nepa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nepa_sel_initWithId_ = {.name = "initWithId_", .hash = 0x8CE5C4CB};
static const SEL __nepa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nepa_sel_triggerScopeChaos = {.name = "triggerScopeChaos", .hash = 0xBC5E90F3};

typedef struct NPObject NPObject;
typedef struct NPShadowGhost NPShadowGhost;
typedef struct NPScopeMixer NPScopeMixer;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * NPShadowGhost_initWithId_(NPObject * self, SEL _cmd, int gid);
void NPShadowGhost_dealloc(NPObject * self, SEL _cmd);
NPClass * NPShadowGhost_getClass(NPClass * self, SEL _cmd);
NPObject * NPScopeMixer_triggerScopeChaos(NPObject * self, SEL _cmd);
NPClass * NPScopeMixer_getClass(NPClass * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NPClass nepa_NPObject_class;
extern NPClass nepa_NPShadowGhost_class;
extern NPClass nepa_NPScopeMixer_class;
void nepa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nepa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nepa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct NPShadowGhost {
    struct NPClass *isa;
    uint32_t retain_count;
    int ghostId;
};
typedef struct NPShadowGhost NPShadowGhost;
struct nepa_NPShadowGhost_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithId_)(NPObject *, SEL, int);
};
struct nepa_NPShadowGhost_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPScopeMixer {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct NPScopeMixer NPScopeMixer;
struct nepa_NPScopeMixer_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*triggerScopeChaos)(NPObject *, SEL);
};
struct nepa_NPScopeMixer_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nepa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nepa_alloc(self);
    return nepa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nepa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nepa_NPObject_class;
}

NPObject * nepa_alloc(struct NPClass * cls);
NPObject * nepa_init(NPObject * );
NPObject * NPShadowGhost_initWithId_(NPObject * self, SEL _cmd, int gid) {
    struct NPShadowGhost * _self = ((struct NPShadowGhost *)(self));
    {
        self = NPObject_init(self, __nepa_sel_init);
        if (self) {
            {
                ((struct NPShadowGhost *)(self))->ghostId = gid;
            }
        }
        return self;
    }
}

void NPShadowGhost_dealloc(NPObject * self, SEL _cmd) {
    struct NPShadowGhost * _self = ((struct NPShadowGhost *)(self));
    {
        printf("[生命周期日志] Ghost-%d 顺利触发 dealloc 彻底销毁。\n", ((struct NPShadowGhost *)(self))->ghostId);
        nepa_object_dealloc(self);
    }
}

NPClass * NPShadowGhost_getClass(NPClass * self, SEL _cmd) {
    return &nepa_NPShadowGhost_class;
}

NPObject * NPScopeMixer_triggerScopeChaos(NPObject * self, SEL _cmd) {
    struct NPScopeMixer * _self = ((struct NPScopeMixer *)(self));
    {
        printf("[作用域测试] 启动顶级作用域环境...\n");
        int x = 100;
        NPObject * escapedObject = NULL;
        {
            nepa_autoreleasepool_t * __pool = nepa_autoreleasepool_push();
            {
                NPObject *__nepa_tmp_0 = (NPObject_alloc(&nepa_NPShadowGhost_class, __nepa_sel_alloc));
                NPShadowGhost * x = ((struct nepa_NPShadowGhost_vtable *)__nepa_tmp_0->isa->vtable)->initWithId_(__nepa_tmp_0, __nepa_sel_initWithId_, 1);
                printf("[一层遮蔽内] 局部对象 x 的 ghostId = %d (顶级整型 x 此时被隐藏)\n", ((struct NPShadowGhost *)(x))->ghostId);
                if (((struct NPShadowGhost *)(x))->ghostId > 0) {
                    {
                        {
                            nepa_autoreleasepool_t * __pool = nepa_autoreleasepool_push();
                            {
                                const char * x = "GHOST_STRING_MARKER";
                                printf("[二层遮蔽内] 嵌套字符串 x = %s\n", x);
                                NPObject *__nepa_tmp_1 = (NPObject_alloc(&nepa_NPShadowGhost_class, __nepa_sel_alloc));
                                NPShadowGhost * ghost2 = ((struct nepa_NPShadowGhost_vtable *)__nepa_tmp_1->isa->vtable)->initWithId_(__nepa_tmp_1, __nepa_sel_initWithId_, 999);
                                escapedObject = ghost2;
                            }
                            nepa_autoreleasepool_pop(__pool);
                        }
                        printf("[退出二层pool] 成功回到一层作用域。\n");
                    }
                }
                nepa_release(x);
            }
            nepa_autoreleasepool_pop(__pool);
        }
        printf("[回到顶级作用域] 遮蔽解除，整型 x 重新复活，值 = %d\n", x);
        return escapedObject;
    }
}

NPClass * NPScopeMixer_getClass(NPClass * self, SEL _cmd) {
    return &nepa_NPScopeMixer_class;
}

int main(int argc, const char * * argv) {
    nepa_autoreleasepool_t *__pool = nepa_autoreleasepool_push();
    nepa_meta_init();
    {
        nepa_autoreleasepool_t * __pool = nepa_autoreleasepool_push();
        {
            printf("==================================================\n");
            printf(">>>    nepac 编译器「阴阳作用域遮蔽与逃逸」压测    <<<\n");
            printf("==================================================\n\n");
            NPObject *__nepa_tmp_2 = (NPObject_alloc(&nepa_NPScopeMixer_class, __nepa_sel_alloc));
            NPScopeMixer * mixer = ((struct nepa_NPObject_vtable *)__nepa_tmp_2->isa->vtable)->init(__nepa_tmp_2, __nepa_sel_init);
            printf("--- 开始执行多层遮蔽与逃逸混淆逻辑 ---\n");
            NPObject * resultGhost = ((struct nepa_NPScopeMixer_vtable *)mixer->isa->vtable)->triggerScopeChaos(mixer, __nepa_sel_triggerScopeChaos);
            printf("\n--- 检查逃逸对象的存活状态 ---\n");
            if (resultGhost != NULL) {
                {
                    NPShadowGhost * finalGhost = ((NPShadowGhost *)(resultGhost));
                    printf("[主程序验证] 逃逸对象成功被顶层捕获！GhostID: %d\n", ((struct NPShadowGhost *)(finalGhost))->ghostId);
                    printf("[主程序销毁] 手动释放逃逸对象...\n");
                    nepa_release(finalGhost);
                }
            }
            nepa_release(mixer);
            printf("\n==================================================\n");
            printf(">>>      神了！同名变量多类型遮蔽完全难不倒你！    <<<\n");
            printf("==================================================\n");
        }
        nepa_autoreleasepool_pop(__pool);
    }
    return 0;
    nepa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nepa_NPObject_vtable nepa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nepa_NPShadowGhost_vtable nepa_NPShadowGhost_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPShadowGhost_dealloc,
    .initWithId_ = NPShadowGhost_initWithId_,
};

struct nepa_NPScopeMixer_vtable nepa_NPScopeMixer_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .triggerScopeChaos = NPScopeMixer_triggerScopeChaos,
};

struct nepa_NPObject_meta_vtable nepa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nepa_NPShadowGhost_meta_vtable nepa_NPShadowGhost_meta_vtable_inst = {
    .class = NPShadowGhost_getClass,
};

struct nepa_NPScopeMixer_meta_vtable nepa_NPScopeMixer_meta_vtable_inst = {
    .class = NPScopeMixer_getClass,
};

NPClass nepa_NPObject_class;
NPClass nepa_NPShadowGhost_class;
NPClass nepa_NPScopeMixer_class;

void nepa_meta_init(void) {
    nepa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nepa_NPObject_vtable_inst,
        .class_vtable = &nepa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nepa_NPShadowGhost_class = (NPClass){
        .name = "NPShadowGhost",
        .superclass = &nepa_NPObject_class,
        .instance_size = sizeof(struct NPShadowGhost),
        .vtable = &nepa_NPShadowGhost_vtable_inst,
        .class_vtable = &nepa_NPShadowGhost_meta_vtable_inst,
        .protocol_count = 0,
    };
    nepa_NPScopeMixer_class = (NPClass){
        .name = "NPScopeMixer",
        .superclass = &nepa_NPObject_class,
        .instance_size = sizeof(struct NPScopeMixer),
        .vtable = &nepa_NPScopeMixer_vtable_inst,
        .class_vtable = &nepa_NPScopeMixer_meta_vtable_inst,
        .protocol_count = 0,
    };
}
