// Generated by galdc
#import <stdio.h>
#import <stdlib.h>
#import <string.h>
#import <time.h>
#import <termios.h>
#import <unistd.h>
#import <sys/select.h>
#include <stdint.h>
#include <stddef.h>
#include "gald/runtime.h"


#include <string.h>

struct gald_NFObject_vtable;
struct gald_Obstacle_vtable;
struct gald_SpaceEngine_vtable;

#define gald_NFObject_vtable_index_init 2
#define gald_NFObject_vtable_index_dealloc 3
#define gald_Obstacle_vtable_index_init 2
#define gald_Obstacle_vtable_index_x 4
#define gald_Obstacle_vtable_index_setX_ 5
#define gald_Obstacle_vtable_index_y 6
#define gald_Obstacle_vtable_index_setY_ 7
#define gald_Obstacle_vtable_index_active 8
#define gald_Obstacle_vtable_index_setActive_ 9
#define gald_Obstacle_vtable_index_resetWithWidth_ 10
#define gald_SpaceEngine_vtable_index_initWithWidth_height_ 4
#define gald_SpaceEngine_vtable_index_gameOver 5
#define gald_SpaceEngine_vtable_index_score 6
#define gald_SpaceEngine_vtable_index_processInfut_ 7
#define gald_SpaceEngine_vtable_index_update 8
#define gald_SpaceEngine_vtable_index_renderWithScoreBlock_ 9
#define gald_SpaceEngine_vtable_index_dealloc 3

static const SEL __gald_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __gald_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __gald_sel_resetWithWidth_ = {.name = "resetWithWidth_", .hash = 0xA7073231};
static const SEL __gald_sel_setY_ = {.name = "setY_", .hash = 0x8D375163};
static const SEL __gald_sel_setActive_ = {.name = "setActive_", .hash = 0xA10E1076};
static const SEL __gald_sel_active = {.name = "active", .hash = 0xD975992F};
static const SEL __gald_sel_y = {.name = "y", .hash = 0xFC0C4EF4};
static const SEL __gald_sel_x = {.name = "x", .hash = 0xFD0C5087};
static const SEL __gald_sel_initWithWidth_height_ = {.name = "initWithWidth_height_", .hash = 0xF532BC76};
static const SEL __gald_sel_gameOver = {.name = "gameOver", .hash = 0x9087973D};
static const SEL __gald_sel_renderWithScoreBlock_ = {.name = "renderWithScoreBlock_", .hash = 0xCD23C083};
static const SEL __gald_sel_processInfut_ = {.name = "processInfut_", .hash = 0xB4C50C83};
static const SEL __gald_sel_update = {.name = "update", .hash = 0x280F9474};
static const SEL __gald_sel_score = {.name = "score", .hash = 0xD22F9095};

typedef struct NFObject NFObject;
typedef struct Obstacle Obstacle;
typedef struct SpaceEngine SpaceEngine;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
void disableRawMode();
void enableRawMode();
int kbhit();
NFObject * Obstacle_init(NFObject * self, SEL _cmd);
int Obstacle_x(NFObject * self, SEL _cmd);
void Obstacle_setX_(NFObject * self, SEL _cmd, int x);
int Obstacle_y(NFObject * self, SEL _cmd);
void Obstacle_setY_(NFObject * self, SEL _cmd, int y);
_Bool Obstacle_active(NFObject * self, SEL _cmd);
void Obstacle_setActive_(NFObject * self, SEL _cmd, _Bool active);
void Obstacle_resetWithWidth_(NFObject * self, SEL _cmd, int width);
NFClass * Obstacle_getClass(NFClass * self, SEL _cmd);
NFObject * SpaceEngine_initWithWidth_height_(NFObject * self, SEL _cmd, int w, int h);
_Bool SpaceEngine_gameOver(NFObject * self, SEL _cmd);
int SpaceEngine_score(NFObject * self, SEL _cmd);
void SpaceEngine_processInfut_(NFObject * self, SEL _cmd, char ch);
void SpaceEngine_update(NFObject * self, SEL _cmd);
void SpaceEngine_renderWithScoreBlock_(NFObject * self, SEL _cmd, int (^scoreBlock)(int));
void SpaceEngine_dealloc(NFObject * self, SEL _cmd);
NFClass * SpaceEngine_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass gald_NFObject_class;
extern NFClass gald_Obstacle_class;
extern NFClass gald_SpaceEngine_class;
void gald_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct gald_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct gald_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct Obstacle {
    struct NFClass *isa;
    uint32_t retain_count;
    int _x;
    int _y;
    _Bool _active;
};
typedef struct Obstacle Obstacle;
struct gald_Obstacle_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    int (*x)(NFObject *, SEL);
    void (*setX_)(NFObject *, SEL, int);
    int (*y)(NFObject *, SEL);
    void (*setY_)(NFObject *, SEL, int);
    _Bool (*active)(NFObject *, SEL);
    void (*setActive_)(NFObject *, SEL, _Bool);
    void (*resetWithWidth_)(NFObject *, SEL, int);
};
struct gald_Obstacle_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
struct SpaceEngine {
    struct NFClass *isa;
    uint32_t retain_count;
    int _width;
    int _height;
    int _playerX;
    int _score;
    _Bool _gameOver;
    Obstacle * _obs1;
    Obstacle * _obs2;
    Obstacle * _obs3;
};
typedef struct SpaceEngine SpaceEngine;
struct gald_SpaceEngine_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    NFObject * (*initWithWidth_height_)(NFObject *, SEL, int, int);
    _Bool (*gameOver)(NFObject *, SEL);
    int (*score)(NFObject *, SEL);
    void (*processInfut_)(NFObject *, SEL, char);
    void (*update)(NFObject *, SEL);
    void (*renderWithScoreBlock_)(NFObject *, SEL, int (^)(int));
};
struct gald_SpaceEngine_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return gald_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = gald_alloc(self);
    return gald_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return gald_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFObject_class;
}

NFObject * gald_alloc(struct NFClass * cls);
NFObject * gald_init(NFObject * );
struct termios orig_termios;
void disableRawMode() {
    tcsetattr(STDIN_FILENO, TCSAFLUSH, &orig_termios);
    printf("\033[?25h");
    fflush(stdout);
}

void enableRawMode() {
    tcgetattr(STDIN_FILENO, &orig_termios);
    atexit(disableRawMode);
    struct termios raw = orig_termios;
    raw.c_lflag = raw.c_lflag & ~(ECHO | ICANON);
    tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw);
    printf("\033[?25l");
    fflush(stdout);
}

int kbhit() {
    struct timeval tv = {0, 100000};
    fd_set fds;
    FD_ZERO(&fds);
    FD_SET(STDIN_FILENO, &fds);
    return select(STDIN_FILENO + 1, &fds, NULL, NULL, &tv);
}

NFObject * Obstacle_init(NFObject * self, SEL _cmd) {
    struct Obstacle * _self = ((struct Obstacle *)(self));
    {
        self = NFObject_init(self, __gald_sel_init);
        if (self) {
            {
                ((struct Obstacle *)(self))->_x = 0;
                ((struct Obstacle *)(self))->_y = 0;
                ((struct Obstacle *)(self))->_active = 0;
            }
        }
        return self;
    }
}

int Obstacle_x(NFObject * self, SEL _cmd) {
    struct Obstacle * _self = ((struct Obstacle *)(self));
    {
        return ((struct Obstacle *)(self))->_x;
    }
}

void Obstacle_setX_(NFObject * self, SEL _cmd, int x) {
    struct Obstacle * _self = ((struct Obstacle *)(self));
    {
        ((struct Obstacle *)(self))->_x = x;
    }
}

int Obstacle_y(NFObject * self, SEL _cmd) {
    struct Obstacle * _self = ((struct Obstacle *)(self));
    {
        return ((struct Obstacle *)(self))->_y;
    }
}

void Obstacle_setY_(NFObject * self, SEL _cmd, int y) {
    struct Obstacle * _self = ((struct Obstacle *)(self));
    {
        ((struct Obstacle *)(self))->_y = y;
    }
}

_Bool Obstacle_active(NFObject * self, SEL _cmd) {
    struct Obstacle * _self = ((struct Obstacle *)(self));
    {
        return ((struct Obstacle *)(self))->_active;
    }
}

void Obstacle_setActive_(NFObject * self, SEL _cmd, _Bool active) {
    struct Obstacle * _self = ((struct Obstacle *)(self));
    {
        ((struct Obstacle *)(self))->_active = active;
    }
}

void Obstacle_resetWithWidth_(NFObject * self, SEL _cmd, int width) {
    struct Obstacle * _self = ((struct Obstacle *)(self));
    {
        ((struct Obstacle *)(self))->_x = rand() % width - 2 + 1;
        ((struct Obstacle *)(self))->_y = 0;
        ((struct Obstacle *)(self))->_active = 1;
    }
}

NFClass * Obstacle_getClass(NFClass * self, SEL _cmd) {
    return &gald_Obstacle_class;
}

NFObject * SpaceEngine_initWithWidth_height_(NFObject * self, SEL _cmd, int w, int h) {
    struct SpaceEngine * _self = ((struct SpaceEngine *)(self));
    {
        self = NFObject_init(self, __gald_sel_init);
        if (self) {
            {
                ((struct SpaceEngine *)(self))->_width = w;
                ((struct SpaceEngine *)(self))->_height = h;
                ((struct SpaceEngine *)(self))->_playerX = w / 2;
                ((struct SpaceEngine *)(self))->_score = 0;
                ((struct SpaceEngine *)(self))->_gameOver = 0;
                ((struct SpaceEngine *)(self))->_obs1 = ({ NFObject *__gald_tmp_0 = (NFObject_alloc(&gald_Obstacle_class, __gald_sel_alloc)); ((struct gald_Obstacle_vtable *)__gald_tmp_0->isa->vtable)->init(__gald_tmp_0, __gald_sel_init); });
                ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->resetWithWidth_(((struct SpaceEngine *)(self))->_obs1, __gald_sel_resetWithWidth_, ((struct SpaceEngine *)(self))->_width);
                ((struct SpaceEngine *)(self))->_obs2 = ({ NFObject *__gald_tmp_1 = (NFObject_alloc(&gald_Obstacle_class, __gald_sel_alloc)); ((struct gald_Obstacle_vtable *)__gald_tmp_1->isa->vtable)->init(__gald_tmp_1, __gald_sel_init); });
                ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->resetWithWidth_(((struct SpaceEngine *)(self))->_obs2, __gald_sel_resetWithWidth_, ((struct SpaceEngine *)(self))->_width);
                ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->setY_(((struct SpaceEngine *)(self))->_obs2, __gald_sel_setY_, -4);
                ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->setActive_(((struct SpaceEngine *)(self))->_obs2, __gald_sel_setActive_, 1);
                ((struct SpaceEngine *)(self))->_obs3 = ({ NFObject *__gald_tmp_2 = (NFObject_alloc(&gald_Obstacle_class, __gald_sel_alloc)); ((struct gald_Obstacle_vtable *)__gald_tmp_2->isa->vtable)->init(__gald_tmp_2, __gald_sel_init); });
                ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->resetWithWidth_(((struct SpaceEngine *)(self))->_obs3, __gald_sel_resetWithWidth_, ((struct SpaceEngine *)(self))->_width);
                ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->setY_(((struct SpaceEngine *)(self))->_obs3, __gald_sel_setY_, -8);
                ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->setActive_(((struct SpaceEngine *)(self))->_obs3, __gald_sel_setActive_, 1);
            }
        }
        return self;
    }
}

_Bool SpaceEngine_gameOver(NFObject * self, SEL _cmd) {
    struct SpaceEngine * _self = ((struct SpaceEngine *)(self));
    {
        return ((struct SpaceEngine *)(self))->_gameOver;
    }
}

int SpaceEngine_score(NFObject * self, SEL _cmd) {
    struct SpaceEngine * _self = ((struct SpaceEngine *)(self));
    {
        return ((struct SpaceEngine *)(self))->_score;
    }
}

void SpaceEngine_processInfut_(NFObject * self, SEL _cmd, char ch) {
    struct SpaceEngine * _self = ((struct SpaceEngine *)(self));
    {
        if (ch == 97 || ch == 65) {
            {
                if (((struct SpaceEngine *)(self))->_playerX > 1) {
                    ((struct SpaceEngine *)(self))->_playerX--;
                }
            }
        } else {
            if (ch == 100 || ch == 68) {
                {
                    if (((struct SpaceEngine *)(self))->_playerX < ((struct SpaceEngine *)(self))->_width - 2) {
                        ((struct SpaceEngine *)(self))->_playerX++;
                    }
                }
            } else {
                if (ch == 113 || ch == 81) {
                    {
                        ((struct SpaceEngine *)(self))->_gameOver = 1;
                    }
                }
            }
        }
    }
}

void SpaceEngine_update(NFObject * self, SEL _cmd) {
    struct SpaceEngine * _self = ((struct SpaceEngine *)(self));
    {
        if (((struct SpaceEngine *)(self))->_gameOver) {
            return;
        }
        if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->active(((struct SpaceEngine *)(self))->_obs1, __gald_sel_active)) {
            {
                ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->setY_(((struct SpaceEngine *)(self))->_obs1, __gald_sel_setY_, ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs1, __gald_sel_y) + 1);
                if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs1, __gald_sel_y) == ((struct SpaceEngine *)(self))->_height - 2 && ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->x(((struct SpaceEngine *)(self))->_obs1, __gald_sel_x) == ((struct SpaceEngine *)(self))->_playerX) {
                    {
                        ((struct SpaceEngine *)(self))->_gameOver = 1;
                    }
                }
                if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs1, __gald_sel_y) >= ((struct SpaceEngine *)(self))->_height - 1) {
                    {
                        ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->resetWithWidth_(((struct SpaceEngine *)(self))->_obs1, __gald_sel_resetWithWidth_, ((struct SpaceEngine *)(self))->_width);
                        ((struct SpaceEngine *)(self))->_score = ((struct SpaceEngine *)(self))->_score + 10;
                    }
                }
            }
        }
        if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->active(((struct SpaceEngine *)(self))->_obs2, __gald_sel_active)) {
            {
                ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->setY_(((struct SpaceEngine *)(self))->_obs2, __gald_sel_setY_, ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs2, __gald_sel_y) + 1);
                if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs2, __gald_sel_y) == ((struct SpaceEngine *)(self))->_height - 2 && ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->x(((struct SpaceEngine *)(self))->_obs2, __gald_sel_x) == ((struct SpaceEngine *)(self))->_playerX) {
                    {
                        ((struct SpaceEngine *)(self))->_gameOver = 1;
                    }
                }
                if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs2, __gald_sel_y) >= ((struct SpaceEngine *)(self))->_height - 1) {
                    {
                        ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->resetWithWidth_(((struct SpaceEngine *)(self))->_obs2, __gald_sel_resetWithWidth_, ((struct SpaceEngine *)(self))->_width);
                        ((struct SpaceEngine *)(self))->_score = ((struct SpaceEngine *)(self))->_score + 10;
                    }
                }
            }
        }
        if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->active(((struct SpaceEngine *)(self))->_obs3, __gald_sel_active)) {
            {
                ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->setY_(((struct SpaceEngine *)(self))->_obs3, __gald_sel_setY_, ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs3, __gald_sel_y) + 1);
                if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs3, __gald_sel_y) == ((struct SpaceEngine *)(self))->_height - 2 && ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->x(((struct SpaceEngine *)(self))->_obs3, __gald_sel_x) == ((struct SpaceEngine *)(self))->_playerX) {
                    {
                        ((struct SpaceEngine *)(self))->_gameOver = 1;
                    }
                }
                if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs3, __gald_sel_y) >= ((struct SpaceEngine *)(self))->_height - 1) {
                    {
                        ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->resetWithWidth_(((struct SpaceEngine *)(self))->_obs3, __gald_sel_resetWithWidth_, ((struct SpaceEngine *)(self))->_width);
                        ((struct SpaceEngine *)(self))->_score = ((struct SpaceEngine *)(self))->_score + 10;
                    }
                }
            }
        }
    }
}

void SpaceEngine_renderWithScoreBlock_(NFObject * self, SEL _cmd, int (^scoreBlock)(int)) {
    struct SpaceEngine * _self = ((struct SpaceEngine *)(self));
    {
        printf("\033[H");
        printf("====================================================\n");
        printf("          MICRIT 终端星际避障 (Space Dodge)        \n");
        printf("====================================================\n");
        for (int i = 0; i < ((struct SpaceEngine *)(self))->_height; i++) {
            {
                for (int j = 0; j < ((struct SpaceEngine *)(self))->_width; j++) {
                    {
                        if (i == 0 || i == ((struct SpaceEngine *)(self))->_height - 1 || j == 0 || j == ((struct SpaceEngine *)(self))->_width - 1) {
                            {
                                printf("#");
                            }
                        } else {
                            if (i == ((struct SpaceEngine *)(self))->_height - 2 && j == ((struct SpaceEngine *)(self))->_playerX) {
                                {
                                    printf("▲");
                                }
                            } else {
                                if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->active(((struct SpaceEngine *)(self))->_obs1, __gald_sel_active) && i == ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs1, __gald_sel_y) && j == ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs1->isa->vtable)->x(((struct SpaceEngine *)(self))->_obs1, __gald_sel_x)) {
                                    {
                                        printf("★");
                                    }
                                } else {
                                    if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->active(((struct SpaceEngine *)(self))->_obs2, __gald_sel_active) && i == ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs2, __gald_sel_y) && j == ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs2->isa->vtable)->x(((struct SpaceEngine *)(self))->_obs2, __gald_sel_x)) {
                                        {
                                            printf("☠");
                                        }
                                    } else {
                                        if (((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->active(((struct SpaceEngine *)(self))->_obs3, __gald_sel_active) && i == ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->y(((struct SpaceEngine *)(self))->_obs3, __gald_sel_y) && j == ((struct gald_Obstacle_vtable *)((struct SpaceEngine *)(self))->_obs3->isa->vtable)->x(((struct SpaceEngine *)(self))->_obs3, __gald_sel_x)) {
                                            {
                                                printf("☄");
                                            }
                                        } else {
                                            {
                                                printf(" ");
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                printf("\n");
            }
        }
        int finalDisplayScore = scoreBlock(((struct SpaceEngine *)(self))->_score);
        printf(" [SCORE]: %d | (Press 'A/D' to Move, 'Q' to Quit)\n", finalDisplayScore);
        printf("====================================================\n");
    }
}

void SpaceEngine_dealloc(NFObject * self, SEL _cmd) {
    struct SpaceEngine * _self = ((struct SpaceEngine *)(self));
    {
        if (((struct SpaceEngine *)(self))->_obs1) {
            NFObject_release(((struct SpaceEngine *)(self))->_obs1);
        }
        if (((struct SpaceEngine *)(self))->_obs2) {
            NFObject_release(((struct SpaceEngine *)(self))->_obs2);
        }
        if (((struct SpaceEngine *)(self))->_obs3) {
            NFObject_release(((struct SpaceEngine *)(self))->_obs3);
        }
        gald_object_dealloc(self);
    }
}

NFClass * SpaceEngine_getClass(NFClass * self, SEL _cmd) {
    return &gald_SpaceEngine_class;
}

int main() {
    gald_autoreleasepool_t *__pool = gald_autoreleasepool_push();
    gald_meta_init();
    {
        gald_autoreleasepool_t * __pool = gald_autoreleasepool_push();
        {
            srand(time(NULL));
            enableRawMode();
            printf("\033[2J\033[H");
            NFObject *__gald_tmp_3 = (NFObject_alloc(&gald_SpaceEngine_class, __gald_sel_alloc));
            SpaceEngine * engine = ((struct gald_SpaceEngine_vtable *)__gald_tmp_3->isa->vtable)->initWithWidth_height_(__gald_tmp_3, __gald_sel_initWithWidth_height_, 24, 16);
            int multiplier = 5;
            int (^hyperScoreCalculator)(int baseScore) = ^int(int baseScore) {
    return baseScore * multiplier;
}
;
            while (!((struct gald_SpaceEngine_vtable *)engine->isa->vtable)->gameOver(engine, __gald_sel_gameOver)) {
                {
                    ((struct gald_SpaceEngine_vtable *)engine->isa->vtable)->renderWithScoreBlock_(engine, __gald_sel_renderWithScoreBlock_, hyperScoreCalculator);
                    if (kbhit()) {
                        {
                            char ch;
                            if (read(STDIN_FILENO, &ch, 1) == 1) {
                                {
                                    ((struct gald_SpaceEngine_vtable *)engine->isa->vtable)->processInfut_(engine, __gald_sel_processInfut_, ch);
                                }
                            }
                        }
                    }
                    ((struct gald_SpaceEngine_vtable *)engine->isa->vtable)->update(engine, __gald_sel_update);
                }
            }
            disableRawMode();
            printf("\n======================================================\n");
            printf("                      Game Over!                      \n");
            printf("======================================================\n");
            printf(" 警告：飞船不幸被陨石击碎，机毁人亡！\n");
            printf(" 最终星际狂暴得分 (Bonus x5): %d 点！\n", ((struct gald_SpaceEngine_vtable *)engine->isa->vtable)->score(engine, __gald_sel_score) * multiplier);
            printf("======================================================\n");
            if (engine) {
                NFObject_release(engine);
            }
        }
        gald_autoreleasepool_pop(__pool);
    }
    return 0;
    gald_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct gald_NFObject_vtable gald_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct gald_Obstacle_vtable gald_Obstacle_vtable_inst = {
    .init = Obstacle_init,
    .dealloc = NFObject_dealloc,
    .x = Obstacle_x,
    .setX_ = Obstacle_setX_,
    .y = Obstacle_y,
    .setY_ = Obstacle_setY_,
    .active = Obstacle_active,
    .setActive_ = Obstacle_setActive_,
    .resetWithWidth_ = Obstacle_resetWithWidth_,
};

struct gald_SpaceEngine_vtable gald_SpaceEngine_vtable_inst = {
    .init = NFObject_init,
    .dealloc = SpaceEngine_dealloc,
    .initWithWidth_height_ = SpaceEngine_initWithWidth_height_,
    .gameOver = SpaceEngine_gameOver,
    .score = SpaceEngine_score,
    .processInfut_ = SpaceEngine_processInfut_,
    .update = SpaceEngine_update,
    .renderWithScoreBlock_ = SpaceEngine_renderWithScoreBlock_,
};

struct gald_NFObject_meta_vtable gald_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct gald_Obstacle_meta_vtable gald_Obstacle_meta_vtable_inst = {
    .class = Obstacle_getClass,
};

struct gald_SpaceEngine_meta_vtable gald_SpaceEngine_meta_vtable_inst = {
    .class = SpaceEngine_getClass,
};

NFClass gald_NFObject_class;
NFClass gald_Obstacle_class;
NFClass gald_SpaceEngine_class;

void gald_meta_init(void) {
    gald_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &gald_NFObject_vtable_inst,
        .class_vtable = &gald_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_Obstacle_class = (NFClass){
        .name = "Obstacle",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct Obstacle),
        .vtable = &gald_Obstacle_vtable_inst,
        .class_vtable = &gald_Obstacle_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_SpaceEngine_class = (NFClass){
        .name = "SpaceEngine",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct SpaceEngine),
        .vtable = &gald_SpaceEngine_vtable_inst,
        .class_vtable = &gald_SpaceEngine_meta_vtable_inst,
        .protocol_count = 0,
    };
}
