// Generated by jetic
#include <stdint.h>
#include <stddef.h>
#include "jeti/runtime.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define STRESS_LOOP_COUNT 10000
#define MAKE_PROPERTY(name) @property (nonatomic, retain) id macro_##name;


#include <string.h>

struct jeti_NPObject_vtable;
struct jeti_NPLayer1_vtable;
struct jeti_NPLayer2_vtable;
struct jeti_NPLayer3_vtable;
struct jeti_NPLayer4_vtable;
struct jeti_NPStressNode_vtable;
struct jeti_NPStressTester_vtable;

#define jeti_NPObject_vtable_index_init 2
#define jeti_NPObject_vtable_index_dealloc 3
#define jeti_NPLayer1_vtable_index_init 2
#define jeti_NPLayer2_vtable_index_init 2
#define jeti_NPLayer3_vtable_index_init 2
#define jeti_NPLayer4_vtable_index_init 2
#define jeti_NPStressNode_vtable_index_initWithId_ 3
#define jeti_NPStressNode_vtable_index_getDeepNext 4
#define jeti_NPStressNode_vtable_index_doA 5
#define jeti_NPStressNode_vtable_index_doB 6
#define jeti_NPStressNode_vtable_index_doC 7
#define jeti_NPStressNode_vtable_index_doD 8
#define jeti_NPStressNode_vtable_index_dealloc 9
#define jeti_NPStressTester_vtable_index_runHeavyMemoryTest 4
#define jeti_NPStressTester_vtable_index_runCrazyBracketTest 5

static const SEL __jeti_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __jeti_sel_doA = {.name = "doA", .hash = 0xC8688DCF};
static const SEL __jeti_sel_doB = {.name = "doB", .hash = 0xC9688F62};
static const SEL __jeti_sel_doC = {.name = "doC", .hash = 0xCA6890F5};
static const SEL __jeti_sel_initWithId_ = {.name = "initWithId_", .hash = 0x8CE5C4CB};
static const SEL __jeti_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __jeti_sel_setPayload_ = {.name = "setPayload_", .hash = 0x246D79E4};
static const SEL __jeti_sel_doD = {.name = "doD", .hash = 0xC36885F0};
static const SEL __jeti_sel_setNextNode_ = {.name = "setNextNode_", .hash = 0x19D6554B};
static const SEL __jeti_sel_setPrevNode_ = {.name = "setPrevNode_", .hash = 0x4F5E66BF};
static const SEL __jeti_sel_nodeId = {.name = "nodeId", .hash = 0x181E12B8};
static const SEL __jeti_sel_prevNode = {.name = "prevNode", .hash = 0x437E115C};
static const SEL __jeti_sel_getDeepNext = {.name = "getDeepNext", .hash = 0x12C4C704};
static const SEL __jeti_sel_runHeavyMemoryTest = {.name = "runHeavyMemoryTest", .hash = 0xB862B512};
static const SEL __jeti_sel_runCrazyBracketTest = {.name = "runCrazyBracketTest", .hash = 0xE40FDA69};

typedef struct NPObject NPObject;
typedef struct NPLayer1 NPLayer1;
typedef struct NPLayer2 NPLayer2;
typedef struct NPLayer3 NPLayer3;
typedef struct NPLayer4 NPLayer4;
typedef struct NPStressNode NPStressNode;
typedef struct NPStressTester NPStressTester;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * NPLayer1_init(NPObject * self, SEL _cmd);
NPClass * NPLayer1_getClass(NPClass * self, SEL _cmd);
NPObject * NPLayer2_init(NPObject * self, SEL _cmd);
NPClass * NPLayer2_getClass(NPClass * self, SEL _cmd);
NPObject * NPLayer3_init(NPObject * self, SEL _cmd);
NPClass * NPLayer3_getClass(NPClass * self, SEL _cmd);
NPObject * NPLayer4_init(NPObject * self, SEL _cmd);
NPClass * NPLayer4_getClass(NPClass * self, SEL _cmd);
NPObject * NPStressNode_initWithId_(NPObject * self, SEL _cmd, int nid);
NPStressNode * NPStressNode_getDeepNext(NPObject * self, SEL _cmd);
void NPStressNode_doA(NPObject * self, SEL _cmd);
void NPStressNode_doB(NPObject * self, SEL _cmd);
void NPStressNode_doC(NPObject * self, SEL _cmd);
void NPStressNode_doD(NPObject * self, SEL _cmd);
void NPStressNode_dealloc(NPObject * self, SEL _cmd);
NPStressNode * NPStressNode_nextNode(NPObject * self, SEL _cmd);
void NPStressNode_setNextNode_(NPObject * self, SEL _cmd, NPStressNode * value);
NPStressNode * NPStressNode_prevNode(NPObject * self, SEL _cmd);
void NPStressNode_setPrevNode_(NPObject * self, SEL _cmd, NPStressNode * value);
NPObject * NPStressNode_payload(NPObject * self, SEL _cmd);
void NPStressNode_setPayload_(NPObject * self, SEL _cmd, NPObject * value);
int NPStressNode_nodeId(NPObject * self, SEL _cmd);
void NPStressNode_setNodeId_(NPObject * self, SEL _cmd, int value);
NPClass * NPStressNode_getClass(NPClass * self, SEL _cmd);
void NPStressTester_runHeavyMemoryTest(NPObject * self, SEL _cmd);
void NPStressTester_runCrazyBracketTest(NPObject * self, SEL _cmd);
NPClass * NPStressTester_getClass(NPClass * self, SEL _cmd);
int main(int argc, const char * * argv);

extern NPClass jeti_NPObject_class;
extern NPClass jeti_NPLayer1_class;
extern NPClass jeti_NPLayer2_class;
extern NPClass jeti_NPLayer3_class;
extern NPClass jeti_NPLayer4_class;
extern NPClass jeti_NPStressNode_class;
extern NPClass jeti_NPStressTester_class;
void jeti_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct jeti_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct jeti_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct NPLayer1 {
    struct NPClass *isa;
    uint32_t retain_count;
    int v1;
};
typedef struct NPLayer1 NPLayer1;
struct jeti_NPLayer1_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct jeti_NPLayer1_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPLayer2 {
    struct NPClass *isa;
    uint32_t retain_count;
    int v1;
    int v2;
};
typedef struct NPLayer2 NPLayer2;
struct jeti_NPLayer2_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct jeti_NPLayer2_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPLayer3 {
    struct NPClass *isa;
    uint32_t retain_count;
    int v1;
    int v2;
    int v3;
};
typedef struct NPLayer3 NPLayer3;
struct jeti_NPLayer3_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct jeti_NPLayer3_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPLayer4 {
    struct NPClass *isa;
    uint32_t retain_count;
    int v1;
    int v2;
    int v3;
    int v4;
};
typedef struct NPLayer4 NPLayer4;
struct jeti_NPLayer4_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct jeti_NPLayer4_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPStressNode {
    struct NPClass *isa;
    uint32_t retain_count;
    int v1;
    int v2;
    int v3;
    int v4;
    NPStressNode * _nextNode;
    NPStressNode * _prevNode;
    NPObject * _payload;
    int _nodeId;
};
typedef struct NPStressNode NPStressNode;
struct jeti_NPStressNode_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithId_)(NPObject *, SEL, int);
    NPStressNode * (*getDeepNext)(NPObject *, SEL);
    void (*doA)(NPObject *, SEL);
    void (*doB)(NPObject *, SEL);
    void (*doC)(NPObject *, SEL);
    void (*doD)(NPObject *, SEL);
    NPStressNode * (*nextNode)(NPObject *, SEL);
    void (*setNextNode_)(NPObject *, SEL, NPStressNode *);
    NPStressNode * (*prevNode)(NPObject *, SEL);
    void (*setPrevNode_)(NPObject *, SEL, NPStressNode *);
    NPObject * (*payload)(NPObject *, SEL);
    void (*setPayload_)(NPObject *, SEL, NPObject *);
    int (*nodeId)(NPObject *, SEL);
    void (*setNodeId_)(NPObject *, SEL, int);
};
struct jeti_NPStressNode_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct NPStressTester {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct NPStressTester NPStressTester;
struct jeti_NPStressTester_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*runHeavyMemoryTest)(NPObject *, SEL);
    void (*runCrazyBracketTest)(NPObject *, SEL);
};
struct jeti_NPStressTester_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return jeti_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = jeti_alloc(self);
    return jeti_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return jeti_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &jeti_NPObject_class;
}

NPObject * jeti_alloc(struct NPClass * cls);
NPObject * jeti_init(NPObject * );
NPObject * NPLayer1_init(NPObject * self, SEL _cmd) {
    struct NPLayer1 * _self = ((struct NPLayer1 *)(self));
    {
        self = NPObject_init(self, __jeti_sel_init);
        if (self) {
            {
                ((struct NPLayer1 *)(self))->v1 = 1;
            }
        }
        return self;
    }
}

NPClass * NPLayer1_getClass(NPClass * self, SEL _cmd) {
    return &jeti_NPLayer1_class;
}

NPObject * NPLayer2_init(NPObject * self, SEL _cmd) {
    struct NPLayer2 * _self = ((struct NPLayer2 *)(self));
    {
        self = NPLayer1_init(self, __jeti_sel_init);
        if (self) {
            {
                ((struct NPLayer2 *)(self))->v2 = 2;
            }
        }
        return self;
    }
}

NPClass * NPLayer2_getClass(NPClass * self, SEL _cmd) {
    return &jeti_NPLayer2_class;
}

NPObject * NPLayer3_init(NPObject * self, SEL _cmd) {
    struct NPLayer3 * _self = ((struct NPLayer3 *)(self));
    {
        self = NPLayer2_init(self, __jeti_sel_init);
        if (self) {
            {
                ((struct NPLayer3 *)(self))->v3 = 3;
            }
        }
        return self;
    }
}

NPClass * NPLayer3_getClass(NPClass * self, SEL _cmd) {
    return &jeti_NPLayer3_class;
}

NPObject * NPLayer4_init(NPObject * self, SEL _cmd) {
    struct NPLayer4 * _self = ((struct NPLayer4 *)(self));
    {
        self = NPLayer3_init(self, __jeti_sel_init);
        if (self) {
            {
                ((struct NPLayer4 *)(self))->v4 = 4;
            }
        }
        return self;
    }
}

NPClass * NPLayer4_getClass(NPClass * self, SEL _cmd) {
    return &jeti_NPLayer4_class;
}

NPObject * NPStressNode_initWithId_(NPObject * self, SEL _cmd, int nid) {
    struct NPStressNode * _self = ((struct NPStressNode *)(self));
    {
        self = NPLayer4_init(self, __jeti_sel_init);
        if (self) {
            {
                ((struct NPStressNode *)(self))->_nodeId = nid;
                ((struct NPStressNode *)(self))->_nextNode = NULL;
                ((struct NPStressNode *)(self))->_prevNode = NULL;
                ((struct NPStressNode *)(self))->_payload = NULL;
            }
        }
        return self;
    }
}

NPStressNode * NPStressNode_getDeepNext(NPObject * self, SEL _cmd) {
    struct NPStressNode * _self = ((struct NPStressNode *)(self));
    {
        return ((struct NPStressNode *)(self))->_nextNode;
    }
}

void NPStressNode_doA(NPObject * self, SEL _cmd) {
    struct NPStressNode * _self = ((struct NPStressNode *)(self));
    {
        ((struct NPStressNode *)(self))->v1 = ((struct NPStressNode *)(self))->v1 + 1;
    }
}

void NPStressNode_doB(NPObject * self, SEL _cmd) {
    struct NPStressNode * _self = ((struct NPStressNode *)(self));
    {
        ((struct NPStressNode *)(self))->v2 = ((struct NPStressNode *)(self))->v2 + 2;
    }
}

void NPStressNode_doC(NPObject * self, SEL _cmd) {
    struct NPStressNode * _self = ((struct NPStressNode *)(self));
    {
        ((struct NPStressNode *)(self))->v3 = ((struct NPStressNode *)(self))->v3 + 3;
    }
}

void NPStressNode_doD(NPObject * self, SEL _cmd) {
    struct NPStressNode * _self = ((struct NPStressNode *)(self));
    {
        ((struct jeti_NPStressNode_vtable *)self->isa->vtable)->doA(self, __jeti_sel_doA);
        ((struct jeti_NPStressNode_vtable *)self->isa->vtable)->doB(self, __jeti_sel_doB);
        ((struct jeti_NPStressNode_vtable *)self->isa->vtable)->doC(self, __jeti_sel_doC);
        ((struct NPStressNode *)(self))->v4 = ((struct NPStressNode *)(self))->v4 + 4;
    }
}

void NPStressNode_dealloc(NPObject * self, SEL _cmd) {
    struct NPStressNode * _self = ((struct NPStressNode *)(self));
    {
        if (((struct NPStressNode *)(self))->_payload) {
            jeti_release(((struct NPStressNode *)(self))->_payload);
        }
        jeti_object_dealloc(self);
    }
}

NPStressNode * NPStressNode_nextNode(NPObject * self, SEL _cmd) {
    return ((struct NPStressNode *)(self))->_nextNode;
}

void NPStressNode_setNextNode_(NPObject * self, SEL _cmd, NPStressNode * value) {
    ((struct NPStressNode *)(self))->_nextNode = value;
}

NPStressNode * NPStressNode_prevNode(NPObject * self, SEL _cmd) {
    return ((struct NPStressNode *)(self))->_prevNode;
}

void NPStressNode_setPrevNode_(NPObject * self, SEL _cmd, NPStressNode * value) {
    ((struct NPStressNode *)(self))->_prevNode = value;
}

NPObject * NPStressNode_payload(NPObject * self, SEL _cmd) {
    return ((struct NPStressNode *)(self))->_payload;
}

void NPStressNode_setPayload_(NPObject * self, SEL _cmd, NPObject * value) {
    ((struct NPStressNode *)(self))->_payload = value;
}

int NPStressNode_nodeId(NPObject * self, SEL _cmd) {
    return ((struct NPStressNode *)(self))->_nodeId;
}

void NPStressNode_setNodeId_(NPObject * self, SEL _cmd, int value) {
    ((struct NPStressNode *)(self))->_nodeId = value;
}

NPClass * NPStressNode_getClass(NPClass * self, SEL _cmd) {
    return &jeti_NPStressNode_class;
}

void NPStressTester_runHeavyMemoryTest(NPObject * self, SEL _cmd) {
    struct NPStressTester * _self = ((struct NPStressTester *)(self));
    {
        printf("[压测] 启动第一阶段：10,000次双向链表瞬时开辟与内存释放...\n");
        NPObject *__jeti_tmp_0 = (NPObject_alloc(&jeti_NPStressNode_class, __jeti_sel_alloc));
        NPStressNode * root = ((struct jeti_NPStressNode_vtable *)__jeti_tmp_0->isa->vtable)->initWithId_(__jeti_tmp_0, __jeti_sel_initWithId_, 0);
        NPStressNode * current = root;
        for (int i = 1; i <= STRESS_LOOP_COUNT; i++) {
            {
                {
                    jeti_autoreleasepool_t * __pool = jeti_autoreleasepool_push();
                    {
                        NPObject *__jeti_tmp_1 = (NPObject_alloc(&jeti_NPStressNode_class, __jeti_sel_alloc));
                        NPStressNode * newNode = ((struct jeti_NPStressNode_vtable *)__jeti_tmp_1->isa->vtable)->initWithId_(__jeti_tmp_1, __jeti_sel_initWithId_, i);
                        NPObject *__jeti_tmp_2 = (NPObject_alloc(&jeti_NPObject_class, __jeti_sel_alloc));
                        NPObject * data = ((struct jeti_NPObject_vtable *)__jeti_tmp_2->isa->vtable)->init(__jeti_tmp_2, __jeti_sel_init);
                        ((struct jeti_NPStressNode_vtable *)newNode->isa->vtable)->setPayload_(newNode, __jeti_sel_setPayload_, data);
                        jeti_release(data);
                        ((struct jeti_NPStressNode_vtable *)newNode->isa->vtable)->doD(newNode, __jeti_sel_doD);
                        ((struct jeti_NPStressNode_vtable *)current->isa->vtable)->setNextNode_(current, __jeti_sel_setNextNode_, newNode);
                        ((struct jeti_NPStressNode_vtable *)newNode->isa->vtable)->setPrevNode_(newNode, __jeti_sel_setPrevNode_, current);
                        current = newNode;
                    }
                    jeti_autoreleasepool_pop(__pool);
                }
            }
        }
        printf("[压测] 链表构建完毕，当前尾节点ID: %d\n", ((struct jeti_NPStressNode_vtable *)current->isa->vtable)->nodeId(current, __jeti_sel_nodeId));
        printf("[压测] 开始逆向解构并回收到期内存...\n");
        NPStressNode * tail = current;
        int releaseCount = 0;
        while (tail != root && tail != NULL) {
            {
                NPStressNode * parent = ((struct jeti_NPStressNode_vtable *)tail->isa->vtable)->prevNode(tail, __jeti_sel_prevNode);
                if (parent) {
                    {
                        ((struct jeti_NPStressNode_vtable *)parent->isa->vtable)->setNextNode_(parent, __jeti_sel_setNextNode_, NULL);
                    }
                }
                jeti_release(tail);
                releaseCount++;
                tail = parent;
            }
        }
        jeti_release(root);
        printf("[压测] 成功释放 %d 个高密度节点，无僵尸对象。\n", releaseCount + 1);
    }
}

void NPStressTester_runCrazyBracketTest(NPObject * self, SEL _cmd) {
    struct NPStressTester * _self = ((struct NPStressTester *)(self));
    {
        printf("[压测] 启动第二阶段：疯狂方括号嵌套语法解析测试...\n");
        NPObject *__jeti_tmp_3 = (NPObject_alloc(&jeti_NPStressNode_class, __jeti_sel_alloc));
        NPStressNode * n1 = ((struct jeti_NPStressNode_vtable *)__jeti_tmp_3->isa->vtable)->initWithId_(__jeti_tmp_3, __jeti_sel_initWithId_, 1);
        NPObject *__jeti_tmp_4 = (NPObject_alloc(&jeti_NPStressNode_class, __jeti_sel_alloc));
        NPStressNode * n2 = ((struct jeti_NPStressNode_vtable *)__jeti_tmp_4->isa->vtable)->initWithId_(__jeti_tmp_4, __jeti_sel_initWithId_, 2);
        NPObject *__jeti_tmp_5 = (NPObject_alloc(&jeti_NPStressNode_class, __jeti_sel_alloc));
        NPStressNode * n3 = ((struct jeti_NPStressNode_vtable *)__jeti_tmp_5->isa->vtable)->initWithId_(__jeti_tmp_5, __jeti_sel_initWithId_, 3);
        NPObject *__jeti_tmp_6 = (NPObject_alloc(&jeti_NPStressNode_class, __jeti_sel_alloc));
        NPStressNode * n4 = ((struct jeti_NPStressNode_vtable *)__jeti_tmp_6->isa->vtable)->initWithId_(__jeti_tmp_6, __jeti_sel_initWithId_, 4);
        ((struct jeti_NPStressNode_vtable *)n1->isa->vtable)->setNextNode_(n1, __jeti_sel_setNextNode_, n2);
        ((struct jeti_NPStressNode_vtable *)n2->isa->vtable)->setNextNode_(n2, __jeti_sel_setNextNode_, n3);
        ((struct jeti_NPStressNode_vtable *)n3->isa->vtable)->setNextNode_(n3, __jeti_sel_setNextNode_, n4);
        NPObject *__jeti_tmp_7 = (({ NPObject *__jeti_tmp_8 = (({ NPObject *__jeti_tmp_9 = (((struct jeti_NPStressNode_vtable *)n1->isa->vtable)->getDeepNext(n1, __jeti_sel_getDeepNext)); ((struct jeti_NPStressNode_vtable *)__jeti_tmp_9->isa->vtable)->getDeepNext(__jeti_tmp_9, __jeti_sel_getDeepNext); })); ((struct jeti_NPStressNode_vtable *)__jeti_tmp_8->isa->vtable)->getDeepNext(__jeti_tmp_8, __jeti_sel_getDeepNext); }));
        int targetId = ((struct jeti_NPStressNode_vtable *)__jeti_tmp_7->isa->vtable)->nodeId(__jeti_tmp_7, __jeti_sel_nodeId);
        printf("[解析断言] 7层嵌套调用成功解析！目标尾节点ID预期为 4 => 实际为: %d\n", targetId);
        jeti_release(n1);
        jeti_release(n2);
        jeti_release(n3);
        jeti_release(n4);
    }
}

NPClass * NPStressTester_getClass(NPClass * self, SEL _cmd) {
    return &jeti_NPStressTester_class;
}

int main(int argc, const char * * argv) {
    jeti_autoreleasepool_t *__pool = jeti_autoreleasepool_push();
    jeti_meta_init();
    {
        jeti_autoreleasepool_t * __pool = jeti_autoreleasepool_push();
        {
            printf("==================================================\n");
            printf(">>>  jetic 编译器「符号与内存」极限暴力压测开始  <<<\n");
            printf("==================================================\n\n");
            NPObject *__jeti_tmp_10 = (NPObject_alloc(&jeti_NPStressTester_class, __jeti_sel_alloc));
            NPStressTester * tester = ((struct jeti_NPObject_vtable *)__jeti_tmp_10->isa->vtable)->init(__jeti_tmp_10, __jeti_sel_init);
            ((struct jeti_NPStressTester_vtable *)tester->isa->vtable)->runHeavyMemoryTest(tester, __jeti_sel_runHeavyMemoryTest);
            printf("\n");
            ((struct jeti_NPStressTester_vtable *)tester->isa->vtable)->runCrazyBracketTest(tester, __jeti_sel_runCrazyBracketTest);
            jeti_release(tester);
            printf("\n==================================================\n");
            printf(">>>          恭喜！暴力压测全部通关！          <<<\n");
            printf("==================================================\n");
        }
        jeti_autoreleasepool_pop(__pool);
    }
    return 0;
    jeti_autoreleasepool_pop(__pool);
}


// ─── Protocol metadata ─────────────────────────────────

extern NPProtocol jeti_protocol_NPProtocolA;
extern NPProtocol jeti_protocol_NPProtocolB;
extern NPProtocol jeti_protocol_NPProtocolC;
extern NPProtocol jeti_protocol_NPProtocolD;

NPProtocol jeti_protocol_NPProtocolA = {
    .name = "NPProtocolA",
    .parents = (NPProtocol *[]){
    },
    .parent_count = 1,
    .required_methods = (NPProtocolMethod[]){
        { .name = "doA", .encoding = "@" },
    },
    .required_count = 1,
    .optional_count = 0,
};

NPProtocol jeti_protocol_NPProtocolB = {
    .name = "NPProtocolB",
    .parents = (NPProtocol *[]){
    },
    .parent_count = 1,
    .required_methods = (NPProtocolMethod[]){
        { .name = "doB", .encoding = "@" },
    },
    .required_count = 1,
    .optional_count = 0,
};

NPProtocol jeti_protocol_NPProtocolC = {
    .name = "NPProtocolC",
    .parents = (NPProtocol *[]){
    },
    .parent_count = 1,
    .required_methods = (NPProtocolMethod[]){
        { .name = "doC", .encoding = "@" },
    },
    .required_count = 1,
    .optional_count = 0,
};

NPProtocol jeti_protocol_NPProtocolD = {
    .name = "NPProtocolD",
    .parents = (NPProtocol *[]){
        &jeti_protocol_NPProtocolA,
        &jeti_protocol_NPProtocolB,
        &jeti_protocol_NPProtocolC,
    },
    .parent_count = 3,
    .required_methods = (NPProtocolMethod[]){
        { .name = "doD", .encoding = "@" },
    },
    .required_count = 1,
    .optional_count = 0,
};


// ─── Class metadata ─────────────────────────────────────

struct jeti_NPObject_vtable jeti_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct jeti_NPLayer1_vtable jeti_NPLayer1_vtable_inst = {
    .init = NPLayer1_init,
    .dealloc = NPObject_dealloc,
};

struct jeti_NPLayer2_vtable jeti_NPLayer2_vtable_inst = {
    .init = NPLayer2_init,
    .dealloc = NPObject_dealloc,
};

struct jeti_NPLayer3_vtable jeti_NPLayer3_vtable_inst = {
    .init = NPLayer3_init,
    .dealloc = NPObject_dealloc,
};

struct jeti_NPLayer4_vtable jeti_NPLayer4_vtable_inst = {
    .init = NPLayer4_init,
    .dealloc = NPObject_dealloc,
};

struct jeti_NPStressNode_vtable jeti_NPStressNode_vtable_inst = {
    .init = NPLayer4_init,
    .dealloc = NPStressNode_dealloc,
    .initWithId_ = NPStressNode_initWithId_,
    .getDeepNext = NPStressNode_getDeepNext,
    .doA = NPStressNode_doA,
    .doB = NPStressNode_doB,
    .doC = NPStressNode_doC,
    .doD = NPStressNode_doD,
    .nextNode = NPStressNode_nextNode,
    .setNextNode_ = NPStressNode_setNextNode_,
    .prevNode = NPStressNode_prevNode,
    .setPrevNode_ = NPStressNode_setPrevNode_,
    .payload = NPStressNode_payload,
    .setPayload_ = NPStressNode_setPayload_,
    .nodeId = NPStressNode_nodeId,
    .setNodeId_ = NPStressNode_setNodeId_,
};

struct jeti_NPStressTester_vtable jeti_NPStressTester_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .runHeavyMemoryTest = NPStressTester_runHeavyMemoryTest,
    .runCrazyBracketTest = NPStressTester_runCrazyBracketTest,
};

struct jeti_NPObject_meta_vtable jeti_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct jeti_NPLayer1_meta_vtable jeti_NPLayer1_meta_vtable_inst = {
    .class = NPLayer1_getClass,
};

struct jeti_NPLayer2_meta_vtable jeti_NPLayer2_meta_vtable_inst = {
    .class = NPLayer2_getClass,
};

struct jeti_NPLayer3_meta_vtable jeti_NPLayer3_meta_vtable_inst = {
    .class = NPLayer3_getClass,
};

struct jeti_NPLayer4_meta_vtable jeti_NPLayer4_meta_vtable_inst = {
    .class = NPLayer4_getClass,
};

struct jeti_NPStressNode_meta_vtable jeti_NPStressNode_meta_vtable_inst = {
    .class = NPStressNode_getClass,
};

struct jeti_NPStressTester_meta_vtable jeti_NPStressTester_meta_vtable_inst = {
    .class = NPStressTester_getClass,
};

NPClass jeti_NPObject_class;
NPClass jeti_NPLayer1_class;
NPClass jeti_NPLayer2_class;
NPClass jeti_NPLayer3_class;
NPClass jeti_NPLayer4_class;
NPClass jeti_NPStressNode_class;
NPClass jeti_NPStressTester_class;

void jeti_meta_init(void) {
    jeti_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &jeti_NPObject_vtable_inst,
        .class_vtable = &jeti_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_NPLayer1_class = (NPClass){
        .name = "NPLayer1",
        .superclass = &jeti_NPObject_class,
        .instance_size = sizeof(struct NPLayer1),
        .vtable = &jeti_NPLayer1_vtable_inst,
        .class_vtable = &jeti_NPLayer1_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_NPLayer2_class = (NPClass){
        .name = "NPLayer2",
        .superclass = &jeti_NPLayer1_class,
        .instance_size = sizeof(struct NPLayer2),
        .vtable = &jeti_NPLayer2_vtable_inst,
        .class_vtable = &jeti_NPLayer2_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_NPLayer3_class = (NPClass){
        .name = "NPLayer3",
        .superclass = &jeti_NPLayer2_class,
        .instance_size = sizeof(struct NPLayer3),
        .vtable = &jeti_NPLayer3_vtable_inst,
        .class_vtable = &jeti_NPLayer3_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_NPLayer4_class = (NPClass){
        .name = "NPLayer4",
        .superclass = &jeti_NPLayer3_class,
        .instance_size = sizeof(struct NPLayer4),
        .vtable = &jeti_NPLayer4_vtable_inst,
        .class_vtable = &jeti_NPLayer4_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_NPStressNode_class = (NPClass){
        .name = "NPStressNode",
        .superclass = &jeti_NPLayer4_class,
        .instance_size = sizeof(struct NPStressNode),
        .vtable = &jeti_NPStressNode_vtable_inst,
        .class_vtable = &jeti_NPStressNode_meta_vtable_inst,
        .protocols = (NPProtocol *[]){
        },
        .protocol_count = 1,
    };
    jeti_NPStressTester_class = (NPClass){
        .name = "NPStressTester",
        .superclass = &jeti_NPObject_class,
        .instance_size = sizeof(struct NPStressTester),
        .vtable = &jeti_NPStressTester_vtable_inst,
        .class_vtable = &jeti_NPStressTester_meta_vtable_inst,
        .protocol_count = 0,
    };
}
