// Generated by galdc
#import <stdio.h>
#import <stdlib.h>
#import <string.h>
#import <time.h>
#import <termios.h>
#import <unistd.h>
#import <sys/select.h>
#include <stdint.h>
#include <stddef.h>
#include "gald/runtime.h"


#include <string.h>

struct gald_NFObject_vtable;
struct gald_TicTacToeEngine_vtable;

#define gald_NFObject_vtable_index_init 2
#define gald_NFObject_vtable_index_dealloc 3
#define gald_TicTacToeEngine_vtable_index_init 2
#define gald_TicTacToeEngine_vtable_index_gameOver 4
#define gald_TicTacToeEngine_vtable_index_winner 5
#define gald_TicTacToeEngine_vtable_index_processInfut_ 6
#define gald_TicTacToeEngine_vtable_index_updateAndCheckWinWithBlock_ 7
#define gald_TicTacToeEngine_vtable_index_render 8

static const SEL __gald_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __gald_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __gald_sel_gameOver = {.name = "gameOver", .hash = 0x9087973D};
static const SEL __gald_sel_render = {.name = "render", .hash = 0xEEF97A0D};
static const SEL __gald_sel_processInfut_ = {.name = "processInfut_", .hash = 0xB4C50C83};
static const SEL __gald_sel_updateAndCheckWinWithBlock_ = {.name = "updateAndCheckWinWithBlock_", .hash = 0xE3BBA5C5};

typedef struct NFObject NFObject;
typedef struct TicTacToeEngine TicTacToeEngine;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
void disableRawMode();
void enableRawMode();
int kbhit();
NFObject * TicTacToeEngine_init(NFObject * self, SEL _cmd);
_Bool TicTacToeEngine_gameOver(NFObject * self, SEL _cmd);
char TicTacToeEngine_winner(NFObject * self, SEL _cmd);
void TicTacToeEngine_processInfut_(NFObject * self, SEL _cmd, char ch);
void TicTacToeEngine_updateAndCheckWinWithBlock_(NFObject * self, SEL _cmd, void (^resultBlock)(char));
void TicTacToeEngine_render(NFObject * self, SEL _cmd);
NFClass * TicTacToeEngine_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass gald_NFObject_class;
extern NFClass gald_TicTacToeEngine_class;
void gald_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct gald_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct gald_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct TicTacToeEngine {
    struct NFClass *isa;
    uint32_t retain_count;
    char _board[9];
    int _cursorX;
    int _cursorY;
    char _currentTurn;
    _Bool _gameOver;
    char _winner;
    char _logMessage[64];
};
typedef struct TicTacToeEngine TicTacToeEngine;
struct gald_TicTacToeEngine_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    _Bool (*gameOver)(NFObject *, SEL);
    char (*winner)(NFObject *, SEL);
    void (*processInfut_)(NFObject *, SEL, char);
    void (*updateAndCheckWinWithBlock_)(NFObject *, SEL, void (^)(char));
    void (*render)(NFObject *, SEL);
};
struct gald_TicTacToeEngine_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return gald_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = gald_alloc(self);
    return gald_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return gald_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFObject_class;
}

NFObject * gald_alloc(struct NFClass * cls);
NFObject * gald_init(NFObject * );
struct termios orig_termios;
void disableRawMode() {
    tcsetattr(STDIN_FILENO, TCSAFLUSH, &orig_termios);
    printf("\033[?25h");
    fflush(stdout);
}

void enableRawMode() {
    tcgetattr(STDIN_FILENO, &orig_termios);
    atexit(disableRawMode);
    struct termios raw = orig_termios;
    raw.c_lflag = raw.c_lflag & ~(ECHO | ICANON);
    tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw);
    printf("\033[?25l");
    fflush(stdout);
}

int kbhit() {
    struct timeval tv = {0, 100000};
    fd_set fds;
    FD_ZERO(&fds);
    FD_SET(STDIN_FILENO, &fds);
    return select(STDIN_FILENO + 1, &fds, NULL, NULL, &tv);
}

NFObject * TicTacToeEngine_init(NFObject * self, SEL _cmd) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        self = NFObject_init(self, __gald_sel_init);
        if (self) {
            {
                for (int i = 0; i < 9; i++) {
                    {
                        ((struct TicTacToeEngine *)(self))->_board[i] = 32;
                    }
                }
                ((struct TicTacToeEngine *)(self))->_cursorX = 1;
                ((struct TicTacToeEngine *)(self))->_cursorY = 1;
                ((struct TicTacToeEngine *)(self))->_currentTurn = 88;
                ((struct TicTacToeEngine *)(self))->_gameOver = 0;
                ((struct TicTacToeEngine *)(self))->_winner = 32;
                strcpy(((struct TicTacToeEngine *)(self))->_logMessage, "游戏开始！请使用 WASD 移动光标，[空格键]落子。");
            }
        }
        return self;
    }
}

_Bool TicTacToeEngine_gameOver(NFObject * self, SEL _cmd) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        return ((struct TicTacToeEngine *)(self))->_gameOver;
    }
}

char TicTacToeEngine_winner(NFObject * self, SEL _cmd) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        return ((struct TicTacToeEngine *)(self))->_winner;
    }
}

void TicTacToeEngine_processInfut_(NFObject * self, SEL _cmd, char ch) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        if (((struct TicTacToeEngine *)(self))->_gameOver) {
            return;
        }
        if (ch == 119 || ch == 87) {
            {
                if (((struct TicTacToeEngine *)(self))->_cursorY > 0) {
                    ((struct TicTacToeEngine *)(self))->_cursorY--;
                }
            }
        } else {
            if (ch == 115 || ch == 83) {
                {
                    if (((struct TicTacToeEngine *)(self))->_cursorY < 2) {
                        ((struct TicTacToeEngine *)(self))->_cursorY++;
                    }
                }
            } else {
                if (ch == 97 || ch == 65) {
                    {
                        if (((struct TicTacToeEngine *)(self))->_cursorX > 0) {
                            ((struct TicTacToeEngine *)(self))->_cursorX--;
                        }
                    }
                } else {
                    if (ch == 100 || ch == 68) {
                        {
                            if (((struct TicTacToeEngine *)(self))->_cursorX < 2) {
                                ((struct TicTacToeEngine *)(self))->_cursorX++;
                            }
                        }
                    } else {
                        if (ch == 32) {
                            {
                                int idx = ((struct TicTacToeEngine *)(self))->_cursorY * 3 + ((struct TicTacToeEngine *)(self))->_cursorX;
                                if (((struct TicTacToeEngine *)(self))->_board[idx] == 32) {
                                    {
                                        ((struct TicTacToeEngine *)(self))->_board[idx] = ((struct TicTacToeEngine *)(self))->_currentTurn;
                                        snprintf(((struct TicTacToeEngine *)(self))->_logMessage, sizeof(((struct TicTacToeEngine *)(self))->_logMessage), "玩家 %c 成功在棋盘 (%d, %d) 落子！", ((struct TicTacToeEngine *)(self))->_currentTurn, ((struct TicTacToeEngine *)(self))->_cursorX + 1, ((struct TicTacToeEngine *)(self))->_cursorY + 1);
                                        ((struct TicTacToeEngine *)(self))->_currentTurn = ((struct TicTacToeEngine *)(self))->_currentTurn == 88 ? 79 : 88;
                                    }
                                } else {
                                    {
                                        strcpy(((struct TicTacToeEngine *)(self))->_logMessage, "⚠️ 警告：该位置已有棋子，请移动光标另选格子！");
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

void TicTacToeEngine_updateAndCheckWinWithBlock_(NFObject * self, SEL _cmd, void (^resultBlock)(char)) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        if (((struct TicTacToeEngine *)(self))->_gameOver) {
            return;
        }
        char w = 32;
        for (int i = 0; i < 3; i++) {
            {
                if (((struct TicTacToeEngine *)(self))->_board[i * 3] != 32 && ((struct TicTacToeEngine *)(self))->_board[i * 3] == ((struct TicTacToeEngine *)(self))->_board[i * 3 + 1] && ((struct TicTacToeEngine *)(self))->_board[i * 3] == ((struct TicTacToeEngine *)(self))->_board[i * 3 + 2]) {
                    {
                        w = ((struct TicTacToeEngine *)(self))->_board[i * 3];
                    }
                }
            }
        }
        for (int i = 0; i < 3; i++) {
            {
                if (((struct TicTacToeEngine *)(self))->_board[i] != 32 && ((struct TicTacToeEngine *)(self))->_board[i] == ((struct TicTacToeEngine *)(self))->_board[i + 3] && ((struct TicTacToeEngine *)(self))->_board[i] == ((struct TicTacToeEngine *)(self))->_board[i + 6]) {
                    {
                        w = ((struct TicTacToeEngine *)(self))->_board[i];
                    }
                }
            }
        }
        if (((struct TicTacToeEngine *)(self))->_board[0] != 32 && ((struct TicTacToeEngine *)(self))->_board[0] == ((struct TicTacToeEngine *)(self))->_board[4] && ((struct TicTacToeEngine *)(self))->_board[0] == ((struct TicTacToeEngine *)(self))->_board[8]) {
            w = ((struct TicTacToeEngine *)(self))->_board[0];
        }
        if (((struct TicTacToeEngine *)(self))->_board[2] != 32 && ((struct TicTacToeEngine *)(self))->_board[2] == ((struct TicTacToeEngine *)(self))->_board[4] && ((struct TicTacToeEngine *)(self))->_board[2] == ((struct TicTacToeEngine *)(self))->_board[6]) {
            w = ((struct TicTacToeEngine *)(self))->_board[2];
        }
        if (w != 32) {
            {
                ((struct TicTacToeEngine *)(self))->_winner = w;
                ((struct TicTacToeEngine *)(self))->_gameOver = 1;
                resultBlock(((struct TicTacToeEngine *)(self))->_winner);
                return;
            }
        }
        _Bool isFull = 1;
        for (int i = 0; i < 9; i++) {
            {
                if (((struct TicTacToeEngine *)(self))->_board[i] == 32) {
                    {
                        isFull = 0;
                        break;
                    }
                }
            }
        }
        if (isFull) {
            {
                ((struct TicTacToeEngine *)(self))->_winner = 68;
                ((struct TicTacToeEngine *)(self))->_gameOver = 1;
                resultBlock(((struct TicTacToeEngine *)(self))->_winner);
            }
        }
    }
}

void TicTacToeEngine_render(NFObject * self, SEL _cmd) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        printf("\033[H");
        printf("===================================================\n");
        printf("         ❌ ⭕ MICRIT 终端智能井字棋 (Tic-Tac-Toe)  \n");
        printf("===================================================\n");
        printf("  操作说明: WASD 移动选中框 | [空格键] 落子 | Q 退出 \n\n");
        for (int y = 0; y < 3; y++) {
            {
                printf("                 ");
                for (int x = 0; x < 3; x++) {
                    {
                        char cell = ((struct TicTacToeEngine *)(self))->_board[y * 3 + x];
                        if (y == ((struct TicTacToeEngine *)(self))->_cursorY && x == ((struct TicTacToeEngine *)(self))->_cursorX) {
                            {
                                if (cell == 32) {
                                    printf("[%c]", 95);
                                } else {
                                    printf("[%c]", cell);
                                }
                            }
                        } else {
                            {
                                if (cell == 32) {
                                    printf(" . ");
                                } else {
                                    printf(" %c ", cell);
                                }
                            }
                        }
                        if (x < 2) {
                            printf("|");
                        }
                    }
                }
                printf("\n");
                if (y < 2) {
                    printf("                 ---+---+---\n");
                }
            }
        }
        printf("\n---------------------------------------------------\n");
        if (!((struct TicTacToeEngine *)(self))->_gameOver) {
            {
                printf(" 📢 当前战局：轮到【 玩家 %c 】运筹帷幄！\n", ((struct TicTacToeEngine *)(self))->_currentTurn);
            }
        } else {
            {
                if (((struct TicTacToeEngine *)(self))->_winner == 68) {
                    {
                        printf(" 🤝 战局结果：棋逢对手，不分伯仲！本局平局 (Draw)！\n");
                    }
                } else {
                    {
                        printf(" 🎉 战局结果：大获全胜！恭喜【 玩家 %c 】斩获胜利！\n", ((struct TicTacToeEngine *)(self))->_winner);
                    }
                }
            }
        }
        printf(" 📜 棋局播报: %s\n", ((struct TicTacToeEngine *)(self))->_logMessage);
        printf("===================================================\n");
    }
}

NFClass * TicTacToeEngine_getClass(NFClass * self, SEL _cmd) {
    return &gald_TicTacToeEngine_class;
}

int main() {
    gald_autoreleasepool_t *__pool = gald_autoreleasepool_push();
    gald_meta_init();
    {
        gald_autoreleasepool_t * __pool = gald_autoreleasepool_push();
        {
            srand(time(NULL));
            enableRawMode();
            printf("\033[2J\033[H");
            NFObject *__gald_tmp_0 = (NFObject_alloc(&gald_TicTacToeEngine_class, __gald_sel_alloc));
            TicTacToeEngine * engine = ((struct gald_TicTacToeEngine_vtable *)__gald_tmp_0->isa->vtable)->init(__gald_tmp_0, __gald_sel_init);
            int matchId = 101;
            int rewardScore = 500;
            void (^celebrationBlock)(char finalWinner) = ^void(char finalWinner) {
    if (finalWinner == 68) {
        {
            printf(" 【赛事中心】战局 #%d 结束。平局无额外奖励。再接再厉！\n", matchId);
        }
    } else {
        {
            printf(" 【赛事中心】战局 #%d 完美闭幕！胜利者将独享 %d 点天梯积分！\n", matchId, rewardScore);
        }
    }
}
;
            while (!((struct gald_TicTacToeEngine_vtable *)engine->isa->vtable)->gameOver(engine, __gald_sel_gameOver)) {
                {
                    ((struct gald_TicTacToeEngine_vtable *)engine->isa->vtable)->render(engine, __gald_sel_render);
                    if (kbhit()) {
                        {
                            char ch;
                            if (read(STDIN_FILENO, &ch, 1) == 1) {
                                {
                                    if (ch == 113 || ch == 81) {
                                        break;
                                    }
                                    ((struct gald_TicTacToeEngine_vtable *)engine->isa->vtable)->processInfut_(engine, __gald_sel_processInfut_, ch);
                                }
                            }
                        }
                    }
                    ((struct gald_TicTacToeEngine_vtable *)engine->isa->vtable)->updateAndCheckWinWithBlock_(engine, __gald_sel_updateAndCheckWinWithBlock_, celebrationBlock);
                }
            }
            ((struct gald_TicTacToeEngine_vtable *)engine->isa->vtable)->render(engine, __gald_sel_render);
            disableRawMode();
            printf("\n===================================================\n");
            printf("                    THANK YOU                      \n");
            printf("===================================================\n");
            printf(" 🏁 终端棋局结束。Micrit 语言高级闭包与一维映射测试完毕！\n");
            printf("===================================================\n");
            if (engine) {
                NFObject_release(engine);
            }
        }
        gald_autoreleasepool_pop(__pool);
    }
    return 0;
    gald_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct gald_NFObject_vtable gald_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct gald_TicTacToeEngine_vtable gald_TicTacToeEngine_vtable_inst = {
    .init = TicTacToeEngine_init,
    .dealloc = NFObject_dealloc,
    .gameOver = TicTacToeEngine_gameOver,
    .winner = TicTacToeEngine_winner,
    .processInfut_ = TicTacToeEngine_processInfut_,
    .updateAndCheckWinWithBlock_ = TicTacToeEngine_updateAndCheckWinWithBlock_,
    .render = TicTacToeEngine_render,
};

struct gald_NFObject_meta_vtable gald_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct gald_TicTacToeEngine_meta_vtable gald_TicTacToeEngine_meta_vtable_inst = {
    .class = TicTacToeEngine_getClass,
};

NFClass gald_NFObject_class;
NFClass gald_TicTacToeEngine_class;

void gald_meta_init(void) {
    gald_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &gald_NFObject_vtable_inst,
        .class_vtable = &gald_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_TicTacToeEngine_class = (NFClass){
        .name = "TicTacToeEngine",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct TicTacToeEngine),
        .vtable = &gald_TicTacToeEngine_vtable_inst,
        .class_vtable = &gald_TicTacToeEngine_meta_vtable_inst,
        .protocol_count = 0,
    };
}
