// Generated by jetic
#import <stdio.h>
#import <stdlib.h>
#import <string.h>
#import <time.h>
#import <termios.h>
#import <unistd.h>
#import <sys/select.h>
#include <stdint.h>
#include <stddef.h>
#include "jeti/runtime.h"


#include <string.h>

struct jeti_NPObject_vtable;
struct jeti_TicTacToeEngine_vtable;

#define jeti_NPObject_vtable_index_init 2
#define jeti_NPObject_vtable_index_dealloc 3
#define jeti_TicTacToeEngine_vtable_index_init 2
#define jeti_TicTacToeEngine_vtable_index_gameOver 4
#define jeti_TicTacToeEngine_vtable_index_winner 5
#define jeti_TicTacToeEngine_vtable_index_processInfut_ 6
#define jeti_TicTacToeEngine_vtable_index_updateAndCheckWinWithBlock_ 7
#define jeti_TicTacToeEngine_vtable_index_render 8

static const SEL __jeti_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __jeti_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __jeti_sel_gameOver = {.name = "gameOver", .hash = 0x9087973D};
static const SEL __jeti_sel_render = {.name = "render", .hash = 0xEEF97A0D};
static const SEL __jeti_sel_processInfut_ = {.name = "processInfut_", .hash = 0xB4C50C83};
static const SEL __jeti_sel_updateAndCheckWinWithBlock_ = {.name = "updateAndCheckWinWithBlock_", .hash = 0xE3BBA5C5};

typedef struct NPObject NPObject;
typedef struct TicTacToeEngine TicTacToeEngine;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
void disableRawMode();
void enableRawMode();
int kbhit();
NPObject * TicTacToeEngine_init(NPObject * self, SEL _cmd);
_Bool TicTacToeEngine_gameOver(NPObject * self, SEL _cmd);
char TicTacToeEngine_winner(NPObject * self, SEL _cmd);
void TicTacToeEngine_processInfut_(NPObject * self, SEL _cmd, char ch);
void TicTacToeEngine_updateAndCheckWinWithBlock_(NPObject * self, SEL _cmd, void (^resultBlock)(char));
void TicTacToeEngine_render(NPObject * self, SEL _cmd);
NPClass * TicTacToeEngine_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass jeti_NPObject_class;
extern NPClass jeti_TicTacToeEngine_class;
void jeti_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct jeti_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct jeti_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct TicTacToeEngine {
    struct NPClass *isa;
    uint32_t retain_count;
    char _board[9];
    int _cursorX;
    int _cursorY;
    char _currentTurn;
    _Bool _gameOver;
    char _winner;
    char _logMessage[64];
};
typedef struct TicTacToeEngine TicTacToeEngine;
struct jeti_TicTacToeEngine_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    _Bool (*gameOver)(NPObject *, SEL);
    char (*winner)(NPObject *, SEL);
    void (*processInfut_)(NPObject *, SEL, char);
    void (*updateAndCheckWinWithBlock_)(NPObject *, SEL, void (^)(char));
    void (*render)(NPObject *, SEL);
};
struct jeti_TicTacToeEngine_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return jeti_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = jeti_alloc(self);
    return jeti_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return jeti_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &jeti_NPObject_class;
}

NPObject * jeti_alloc(struct NPClass * cls);
NPObject * jeti_init(NPObject * );
struct termios orig_termios;
void disableRawMode() {
    tcsetattr(STDIN_FILENO, TCSAFLUSH, &orig_termios);
    printf("\033[?25h");
    fflush(stdout);
}

void enableRawMode() {
    tcgetattr(STDIN_FILENO, &orig_termios);
    atexit(disableRawMode);
    struct termios raw = orig_termios;
    raw.c_lflag = raw.c_lflag & ~(ECHO | ICANON);
    tcsetattr(STDIN_FILENO, TCSAFLUSH, &raw);
    printf("\033[?25l");
    fflush(stdout);
}

int kbhit() {
    struct timeval tv = {0, 100000};
    fd_set fds;
    FD_ZERO(&fds);
    FD_SET(STDIN_FILENO, &fds);
    return select(STDIN_FILENO + 1, &fds, NULL, NULL, &tv);
}

NPObject * TicTacToeEngine_init(NPObject * self, SEL _cmd) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        self = NPObject_init(self, __jeti_sel_init);
        if (self) {
            {
                for (int i = 0; i < 9; i++) {
                    {
                        ((struct TicTacToeEngine *)(self))->_board[i] = 32;
                    }
                }
                ((struct TicTacToeEngine *)(self))->_cursorX = 1;
                ((struct TicTacToeEngine *)(self))->_cursorY = 1;
                ((struct TicTacToeEngine *)(self))->_currentTurn = 88;
                ((struct TicTacToeEngine *)(self))->_gameOver = 0;
                ((struct TicTacToeEngine *)(self))->_winner = 32;
                strcpy(((struct TicTacToeEngine *)(self))->_logMessage, "游戏开始！请使用 WASD 移动光标，[空格键]落子。");
            }
        }
        return self;
    }
}

_Bool TicTacToeEngine_gameOver(NPObject * self, SEL _cmd) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        return ((struct TicTacToeEngine *)(self))->_gameOver;
    }
}

char TicTacToeEngine_winner(NPObject * self, SEL _cmd) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        return ((struct TicTacToeEngine *)(self))->_winner;
    }
}

void TicTacToeEngine_processInfut_(NPObject * self, SEL _cmd, char ch) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        if (((struct TicTacToeEngine *)(self))->_gameOver) {
            return;
        }
        if (ch == 119 || ch == 87) {
            {
                if (((struct TicTacToeEngine *)(self))->_cursorY > 0) {
                    ((struct TicTacToeEngine *)(self))->_cursorY--;
                }
            }
        } else {
            if (ch == 115 || ch == 83) {
                {
                    if (((struct TicTacToeEngine *)(self))->_cursorY < 2) {
                        ((struct TicTacToeEngine *)(self))->_cursorY++;
                    }
                }
            } else {
                if (ch == 97 || ch == 65) {
                    {
                        if (((struct TicTacToeEngine *)(self))->_cursorX > 0) {
                            ((struct TicTacToeEngine *)(self))->_cursorX--;
                        }
                    }
                } else {
                    if (ch == 100 || ch == 68) {
                        {
                            if (((struct TicTacToeEngine *)(self))->_cursorX < 2) {
                                ((struct TicTacToeEngine *)(self))->_cursorX++;
                            }
                        }
                    } else {
                        if (ch == 32) {
                            {
                                int idx = ((struct TicTacToeEngine *)(self))->_cursorY * 3 + ((struct TicTacToeEngine *)(self))->_cursorX;
                                if (((struct TicTacToeEngine *)(self))->_board[idx] == 32) {
                                    {
                                        ((struct TicTacToeEngine *)(self))->_board[idx] = ((struct TicTacToeEngine *)(self))->_currentTurn;
                                        snprintf(((struct TicTacToeEngine *)(self))->_logMessage, sizeof(((struct TicTacToeEngine *)(self))->_logMessage), "玩家 %c 成功在棋盘 (%d, %d) 落子！", ((struct TicTacToeEngine *)(self))->_currentTurn, ((struct TicTacToeEngine *)(self))->_cursorX + 1, ((struct TicTacToeEngine *)(self))->_cursorY + 1);
                                        ((struct TicTacToeEngine *)(self))->_currentTurn = ((struct TicTacToeEngine *)(self))->_currentTurn == 88 ? 79 : 88;
                                    }
                                } else {
                                    {
                                        strcpy(((struct TicTacToeEngine *)(self))->_logMessage, "⚠️ 警告：该位置已有棋子，请移动光标另选格子！");
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}

void TicTacToeEngine_updateAndCheckWinWithBlock_(NPObject * self, SEL _cmd, void (^resultBlock)(char)) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        if (((struct TicTacToeEngine *)(self))->_gameOver) {
            return;
        }
        char w = 32;
        for (int i = 0; i < 3; i++) {
            {
                if (((struct TicTacToeEngine *)(self))->_board[i * 3] != 32 && ((struct TicTacToeEngine *)(self))->_board[i * 3] == ((struct TicTacToeEngine *)(self))->_board[i * 3 + 1] && ((struct TicTacToeEngine *)(self))->_board[i * 3] == ((struct TicTacToeEngine *)(self))->_board[i * 3 + 2]) {
                    {
                        w = ((struct TicTacToeEngine *)(self))->_board[i * 3];
                    }
                }
            }
        }
        for (int i = 0; i < 3; i++) {
            {
                if (((struct TicTacToeEngine *)(self))->_board[i] != 32 && ((struct TicTacToeEngine *)(self))->_board[i] == ((struct TicTacToeEngine *)(self))->_board[i + 3] && ((struct TicTacToeEngine *)(self))->_board[i] == ((struct TicTacToeEngine *)(self))->_board[i + 6]) {
                    {
                        w = ((struct TicTacToeEngine *)(self))->_board[i];
                    }
                }
            }
        }
        if (((struct TicTacToeEngine *)(self))->_board[0] != 32 && ((struct TicTacToeEngine *)(self))->_board[0] == ((struct TicTacToeEngine *)(self))->_board[4] && ((struct TicTacToeEngine *)(self))->_board[0] == ((struct TicTacToeEngine *)(self))->_board[8]) {
            w = ((struct TicTacToeEngine *)(self))->_board[0];
        }
        if (((struct TicTacToeEngine *)(self))->_board[2] != 32 && ((struct TicTacToeEngine *)(self))->_board[2] == ((struct TicTacToeEngine *)(self))->_board[4] && ((struct TicTacToeEngine *)(self))->_board[2] == ((struct TicTacToeEngine *)(self))->_board[6]) {
            w = ((struct TicTacToeEngine *)(self))->_board[2];
        }
        if (w != 32) {
            {
                ((struct TicTacToeEngine *)(self))->_winner = w;
                ((struct TicTacToeEngine *)(self))->_gameOver = 1;
                resultBlock(((struct TicTacToeEngine *)(self))->_winner);
                return;
            }
        }
        _Bool isFull = 1;
        for (int i = 0; i < 9; i++) {
            {
                if (((struct TicTacToeEngine *)(self))->_board[i] == 32) {
                    {
                        isFull = 0;
                        break;
                    }
                }
            }
        }
        if (isFull) {
            {
                ((struct TicTacToeEngine *)(self))->_winner = 68;
                ((struct TicTacToeEngine *)(self))->_gameOver = 1;
                resultBlock(((struct TicTacToeEngine *)(self))->_winner);
            }
        }
    }
}

void TicTacToeEngine_render(NPObject * self, SEL _cmd) {
    struct TicTacToeEngine * _self = ((struct TicTacToeEngine *)(self));
    {
        printf("\033[H");
        printf("===================================================\n");
        printf("         ❌ ⭕ MICRIT 终端智能井字棋 (Tic-Tac-Toe)  \n");
        printf("===================================================\n");
        printf("  操作说明: WASD 移动选中框 | [空格键] 落子 | Q 退出 \n\n");
        for (int y = 0; y < 3; y++) {
            {
                printf("                 ");
                for (int x = 0; x < 3; x++) {
                    {
                        char cell = ((struct TicTacToeEngine *)(self))->_board[y * 3 + x];
                        if (y == ((struct TicTacToeEngine *)(self))->_cursorY && x == ((struct TicTacToeEngine *)(self))->_cursorX) {
                            {
                                if (cell == 32) {
                                    printf("[%c]", 95);
                                } else {
                                    printf("[%c]", cell);
                                }
                            }
                        } else {
                            {
                                if (cell == 32) {
                                    printf(" . ");
                                } else {
                                    printf(" %c ", cell);
                                }
                            }
                        }
                        if (x < 2) {
                            printf("|");
                        }
                    }
                }
                printf("\n");
                if (y < 2) {
                    printf("                 ---+---+---\n");
                }
            }
        }
        printf("\n---------------------------------------------------\n");
        if (!((struct TicTacToeEngine *)(self))->_gameOver) {
            {
                printf(" 📢 当前战局：轮到【 玩家 %c 】运筹帷幄！\n", ((struct TicTacToeEngine *)(self))->_currentTurn);
            }
        } else {
            {
                if (((struct TicTacToeEngine *)(self))->_winner == 68) {
                    {
                        printf(" 🤝 战局结果：棋逢对手，不分伯仲！本局平局 (Draw)！\n");
                    }
                } else {
                    {
                        printf(" 🎉 战局结果：大获全胜！恭喜【 玩家 %c 】斩获胜利！\n", ((struct TicTacToeEngine *)(self))->_winner);
                    }
                }
            }
        }
        printf(" 📜 棋局播报: %s\n", ((struct TicTacToeEngine *)(self))->_logMessage);
        printf("===================================================\n");
    }
}

NPClass * TicTacToeEngine_getClass(NPClass * self, SEL _cmd) {
    return &jeti_TicTacToeEngine_class;
}

int main() {
    jeti_autoreleasepool_t *__pool = jeti_autoreleasepool_push();
    jeti_meta_init();
    {
        jeti_autoreleasepool_t * __pool = jeti_autoreleasepool_push();
        {
            srand(time(NULL));
            enableRawMode();
            printf("\033[2J\033[H");
            NPObject *__jeti_tmp_0 = (NPObject_alloc(&jeti_TicTacToeEngine_class, __jeti_sel_alloc));
            TicTacToeEngine * engine = ((struct jeti_TicTacToeEngine_vtable *)__jeti_tmp_0->isa->vtable)->init(__jeti_tmp_0, __jeti_sel_init);
            int matchId = 101;
            int rewardScore = 500;
            void (^celebrationBlock)(char finalWinner) = ^void(char finalWinner) {
    if (finalWinner == 68) {
        {
            printf(" 【赛事中心】战局 #%d 结束。平局无额外奖励。再接再厉！\n", matchId);
        }
    } else {
        {
            printf(" 【赛事中心】战局 #%d 完美闭幕！胜利者将独享 %d 点天梯积分！\n", matchId, rewardScore);
        }
    }
}
;
            while (!((struct jeti_TicTacToeEngine_vtable *)engine->isa->vtable)->gameOver(engine, __jeti_sel_gameOver)) {
                {
                    ((struct jeti_TicTacToeEngine_vtable *)engine->isa->vtable)->render(engine, __jeti_sel_render);
                    if (kbhit()) {
                        {
                            char ch;
                            if (read(STDIN_FILENO, &ch, 1) == 1) {
                                {
                                    if (ch == 113 || ch == 81) {
                                        break;
                                    }
                                    ((struct jeti_TicTacToeEngine_vtable *)engine->isa->vtable)->processInfut_(engine, __jeti_sel_processInfut_, ch);
                                }
                            }
                        }
                    }
                    ((struct jeti_TicTacToeEngine_vtable *)engine->isa->vtable)->updateAndCheckWinWithBlock_(engine, __jeti_sel_updateAndCheckWinWithBlock_, celebrationBlock);
                }
            }
            ((struct jeti_TicTacToeEngine_vtable *)engine->isa->vtable)->render(engine, __jeti_sel_render);
            disableRawMode();
            printf("\n===================================================\n");
            printf("                    THANK YOU                      \n");
            printf("===================================================\n");
            printf(" 🏁 终端棋局结束。Micrit 语言高级闭包与一维映射测试完毕！\n");
            printf("===================================================\n");
            if (engine) {
                NPObject_release(engine);
            }
        }
        jeti_autoreleasepool_pop(__pool);
    }
    return 0;
    jeti_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct jeti_NPObject_vtable jeti_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct jeti_TicTacToeEngine_vtable jeti_TicTacToeEngine_vtable_inst = {
    .init = TicTacToeEngine_init,
    .dealloc = NPObject_dealloc,
    .gameOver = TicTacToeEngine_gameOver,
    .winner = TicTacToeEngine_winner,
    .processInfut_ = TicTacToeEngine_processInfut_,
    .updateAndCheckWinWithBlock_ = TicTacToeEngine_updateAndCheckWinWithBlock_,
    .render = TicTacToeEngine_render,
};

struct jeti_NPObject_meta_vtable jeti_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct jeti_TicTacToeEngine_meta_vtable jeti_TicTacToeEngine_meta_vtable_inst = {
    .class = TicTacToeEngine_getClass,
};

NPClass jeti_NPObject_class;
NPClass jeti_TicTacToeEngine_class;

void jeti_meta_init(void) {
    jeti_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &jeti_NPObject_vtable_inst,
        .class_vtable = &jeti_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    jeti_TicTacToeEngine_class = (NPClass){
        .name = "TicTacToeEngine",
        .superclass = &jeti_NPObject_class,
        .instance_size = sizeof(struct TicTacToeEngine),
        .vtable = &jeti_TicTacToeEngine_vtable_inst,
        .class_vtable = &jeti_TicTacToeEngine_meta_vtable_inst,
        .protocol_count = 0,
    };
}
