// Generated by galdc
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "gald/runtime.h"


#include <string.h>

struct gald_NFObject_vtable;
struct gald_Counter_vtable;

#define gald_NFObject_vtable_index_init 2
#define gald_NFObject_vtable_index_dealloc 3
#define gald_Counter_vtable_index_init 2
#define gald_Counter_vtable_index_increment 4

static const SEL __gald_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __gald_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __gald_sel_increment = {.name = "increment", .hash = 0x3812E73E};

typedef struct NFObject NFObject;
typedef struct Counter Counter;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
NFObject * Counter_init(NFObject * self, SEL _cmd);
int Counter_increment(NFObject * self, SEL _cmd);
NFClass * Counter_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass gald_NFObject_class;
extern NFClass gald_Counter_class;
void gald_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct gald_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct gald_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct Counter {
    struct NFClass *isa;
    uint32_t retain_count;
    int count;
};
typedef struct Counter Counter;
struct gald_Counter_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    int (*increment)(NFObject *, SEL);
};
struct gald_Counter_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return gald_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = gald_alloc(self);
    return gald_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return gald_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFObject_class;
}

NFObject * gald_alloc(struct NFClass * cls);
NFObject * gald_init(NFObject * );
NFObject * Counter_init(NFObject * self, SEL _cmd) {
    struct Counter * _self = ((struct Counter *)(self));
    {
        self = NFObject_init(self, __gald_sel_init);
        if (self) {
            ((struct Counter *)(self))->count = 0;
        }
        return self;
    }
}

int Counter_increment(NFObject * self, SEL _cmd) {
    struct Counter * _self = ((struct Counter *)(self));
    {
        ((struct Counter *)(self))->count++;
        return ((struct Counter *)(self))->count;
    }
}

NFClass * Counter_getClass(NFClass * self, SEL _cmd) {
    return &gald_Counter_class;
}

int main() {
    gald_autoreleasepool_t *__pool = gald_autoreleasepool_push();
    gald_meta_init();
    {
        gald_autoreleasepool_t * __pool = gald_autoreleasepool_push();
        {
            NFObject *__gald_tmp_0 = (NFObject_alloc(&gald_Counter_class, __gald_sel_alloc));
            Counter * c = ((struct gald_Counter_vtable *)__gald_tmp_0->isa->vtable)->init(__gald_tmp_0, __gald_sel_init);
            printf("init: %d\n", ((struct Counter *)(c))->count);
            int v1 = ((struct gald_Counter_vtable *)c->isa->vtable)->increment(c, __gald_sel_increment);
            int v2 = ((struct gald_Counter_vtable *)c->isa->vtable)->increment(c, __gald_sel_increment);
            printf("after 2 increments: %d\n", v2);
            gald_release(c);
        }
        gald_autoreleasepool_pop(__pool);
    }
    printf("NFObject lifecycle OK\n");
    return 0;
    gald_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct gald_NFObject_vtable gald_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct gald_Counter_vtable gald_Counter_vtable_inst = {
    .init = Counter_init,
    .dealloc = NFObject_dealloc,
    .increment = Counter_increment,
};

struct gald_NFObject_meta_vtable gald_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct gald_Counter_meta_vtable gald_Counter_meta_vtable_inst = {
    .class = Counter_getClass,
};

NFClass gald_NFObject_class;
NFClass gald_Counter_class;

void gald_meta_init(void) {
    gald_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &gald_NFObject_vtable_inst,
        .class_vtable = &gald_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_Counter_class = (NFClass){
        .name = "Counter",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct Counter),
        .vtable = &gald_Counter_vtable_inst,
        .class_vtable = &gald_Counter_meta_vtable_inst,
        .protocol_count = 0,
    };
}
