// Generated by galdc
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "gald/runtime.h"
struct gald___gald_root_vtable;
struct gald_NFObject_vtable;
struct gald_NFObject_meta_vtable;
struct gald_Buffer_vtable;
struct gald_Buffer_meta_vtable;
struct gald_Buffer_A_ptr_vtable;
struct gald_Buffer_A_ptr_meta_vtable;
struct gald_Buffer_B_ptr_vtable;
struct gald_Buffer_B_ptr_meta_vtable;
struct gald_A_vtable;
struct gald_A_meta_vtable;
struct gald_B_vtable;
struct gald_B_meta_vtable;

static const SEL __gald_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __gald_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __gald_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __gald_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __gald_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __gald_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __gald_sel_add_ = {.name = "add:", .hash = 0x88D7D0CA};
static const SEL __gald_sel_get = {.name = "get", .hash = 0x540CA757};

typedef struct __gald_root __gald_root;
typedef struct NFObject NFObject;
typedef struct Buffer Buffer;
typedef struct Buffer_A_ptr Buffer_A_ptr;
typedef struct Buffer_B_ptr Buffer_B_ptr;
typedef struct A A;
typedef struct B B;

NFObject * __gald_root_init(NFObject * self, SEL _cmd);
void __gald_root_dealloc(NFObject * self, SEL _cmd);
void __gald_root_release(NFObject * self, SEL _cmd);
NFObject * __gald_root_retain(NFObject * self, SEL _cmd);
NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
void NFObject_release(NFObject * self, SEL _cmd);
NFObject * NFObject_retain(NFObject * self, SEL _cmd);
void Buffer_add_(NFObject * self, SEL _cmd, NFObject * item);
NFObject * Buffer_get(NFObject * self, SEL _cmd);
NFObject * gald_alloc(struct NFClass * cls);
NFObject * gald_init(NFObject * self);
void gald_release(NFObject * obj);
NFObject * gald_retain(NFObject * obj);
int main(void);
void Buffer_A_ptr_add_(A * self, SEL _cmd, A * item);
A * Buffer_A_ptr_get(A * self, SEL _cmd);
void Buffer_B_ptr_add_(B * self, SEL _cmd, B * item);
B * Buffer_B_ptr_get(B * self, SEL _cmd);

NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
NFClass * Buffer_getClass(NFClass * self, SEL _cmd);
NFClass * Buffer_A_ptr_getClass(NFClass * self, SEL _cmd);
NFClass * Buffer_B_ptr_getClass(NFClass * self, SEL _cmd);
NFClass * A_getClass(NFClass * self, SEL _cmd);
NFClass * B_getClass(NFClass * self, SEL _cmd);

struct gald___gald_root_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    void (*release)(NFObject *, SEL);
    NFObject * (*retain)(NFObject *, SEL);
};
struct gald_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    void (*release)(NFObject *, SEL);
    NFObject * (*retain)(NFObject *, SEL);
};
struct gald_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct gald_Buffer_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    void (*release)(NFObject *, SEL);
    NFObject * (*retain)(NFObject *, SEL);
    void (*add_)(NFObject *, SEL, NFObject *);
    NFObject * (*get)(NFObject *, SEL);
};
struct gald_Buffer_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct gald_Buffer_A_ptr_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    void (*release)(NFObject *, SEL);
    NFObject * (*retain)(NFObject *, SEL);
    void (*add_)(A *, SEL, A *);
    A * (*get)(A *, SEL);
};
struct gald_Buffer_A_ptr_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct gald_Buffer_B_ptr_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    void (*release)(NFObject *, SEL);
    NFObject * (*retain)(NFObject *, SEL);
    void (*add_)(B *, SEL, B *);
    B * (*get)(B *, SEL);
};
struct gald_Buffer_B_ptr_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct gald_A_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    void (*release)(NFObject *, SEL);
    NFObject * (*retain)(NFObject *, SEL);
};
struct gald_A_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct gald_B_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    void (*release)(NFObject *, SEL);
    NFObject * (*retain)(NFObject *, SEL);
};
struct gald_B_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};

struct __gald_root {
    struct NFClass *isa;
    uint32_t retain_count;
};
typedef struct __gald_root __gald_root;

struct Buffer {
    struct NFClass *isa;
    uint32_t retain_count;
    NFObject * _data[2];
    int _len;
};
typedef struct Buffer Buffer;

struct Buffer_A_ptr {
    struct NFClass *isa;
    uint32_t retain_count;
    A * _data[2];
    int _len;
};
typedef struct Buffer_A_ptr Buffer_A_ptr;

struct Buffer_B_ptr {
    struct NFClass *isa;
    uint32_t retain_count;
    B * _data[2];
    int _len;
};
typedef struct Buffer_B_ptr Buffer_B_ptr;

struct A {
    struct NFClass *isa;
    uint32_t retain_count;
};
typedef struct A A;

struct B {
    struct NFClass *isa;
    uint32_t retain_count;
};
typedef struct B B;

extern NFClass gald___gald_root_class;
extern NFClass gald_NFObject_class;
extern NFClass gald_Buffer_class;
extern NFClass gald_Buffer_A_ptr_class;
extern NFClass gald_Buffer_B_ptr_class;
extern NFClass gald_A_class;
extern NFClass gald_B_class;
void gald_meta_init(void);

struct gald___gald_root_vtable gald___gald_root_vtable_inst = {
    .init = __gald_root_init,
    .dealloc = __gald_root_dealloc,
    .release = __gald_root_release,
    .retain = __gald_root_retain,
};

struct gald_NFObject_vtable gald_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .release = NFObject_release,
    .retain = NFObject_retain,
};

struct gald_Buffer_vtable gald_Buffer_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .release = NFObject_release,
    .retain = NFObject_retain,
    .add_ = Buffer_add_,
    .get = Buffer_get,
};

struct gald_Buffer_A_ptr_vtable gald_Buffer_A_ptr_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .release = NFObject_release,
    .retain = NFObject_retain,
    .add_ = Buffer_A_ptr_add_,
    .get = Buffer_A_ptr_get,
};

struct gald_Buffer_B_ptr_vtable gald_Buffer_B_ptr_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .release = NFObject_release,
    .retain = NFObject_retain,
    .add_ = Buffer_B_ptr_add_,
    .get = Buffer_B_ptr_get,
};

struct gald_A_vtable gald_A_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .release = NFObject_release,
    .retain = NFObject_retain,
};

struct gald_B_vtable gald_B_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .release = NFObject_release,
    .retain = NFObject_retain,
};

struct gald_NFObject_meta_vtable gald_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct gald_Buffer_meta_vtable gald_Buffer_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = Buffer_getClass,
};

struct gald_Buffer_A_ptr_meta_vtable gald_Buffer_A_ptr_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = Buffer_A_ptr_getClass,
};

struct gald_Buffer_B_ptr_meta_vtable gald_Buffer_B_ptr_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = Buffer_B_ptr_getClass,
};

struct gald_A_meta_vtable gald_A_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = A_getClass,
};

struct gald_B_meta_vtable gald_B_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = B_getClass,
};

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NFClass * Buffer_getClass(NFClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NFClass * Buffer_A_ptr_getClass(NFClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NFClass * Buffer_B_ptr_getClass(NFClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NFClass * A_getClass(NFClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NFClass * B_getClass(NFClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NFClass gald___gald_root_class;
NFClass gald_NFObject_class;
NFClass gald_Buffer_class;
NFClass gald_Buffer_A_ptr_class;
NFClass gald_Buffer_B_ptr_class;
NFClass gald_A_class;
NFClass gald_B_class;

void gald_meta_init(void) {
    gald___gald_root_class = (NFClass){
        .name = "__gald_root",
        .superclass = NULL,
        .instance_size = sizeof(struct __gald_root),
        .vtable = &gald___gald_root_vtable_inst,
        .class_vtable = NULL,
        .protocol_count = 0,
    };
    gald_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = &gald___gald_root_class,
        .instance_size = sizeof(struct NFObject),
        .vtable = &gald_NFObject_vtable_inst,
        .class_vtable = &gald_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_Buffer_class = (NFClass){
        .name = "Buffer",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct Buffer),
        .vtable = &gald_Buffer_vtable_inst,
        .class_vtable = &gald_Buffer_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_Buffer_A_ptr_class = (NFClass){
        .name = "Buffer<A *>",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct Buffer_A_ptr),
        .vtable = &gald_Buffer_A_ptr_vtable_inst,
        .class_vtable = &gald_Buffer_A_ptr_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_Buffer_B_ptr_class = (NFClass){
        .name = "Buffer<B *>",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct Buffer_B_ptr),
        .vtable = &gald_Buffer_B_ptr_vtable_inst,
        .class_vtable = &gald_Buffer_B_ptr_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_A_class = (NFClass){
        .name = "A",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct A),
        .vtable = &gald_A_vtable_inst,
        .class_vtable = &gald_A_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_B_class = (NFClass){
        .name = "B",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct B),
        .vtable = &gald_B_vtable_inst,
        .class_vtable = &gald_B_meta_vtable_inst,
        .protocol_count = 0,
    };
}
NFObject * __gald_root_init(NFObject * self, SEL _cmd) {
  struct __gald_root * _self = (struct __gald_root *)self;
  {
    return gald_init(self);
  }
}

void __gald_root_dealloc(NFObject * self, SEL _cmd) {
  struct __gald_root * _self = (struct __gald_root *)self;
  {
    return;
  }
}

void __gald_root_release(NFObject * self, SEL _cmd) {
  struct __gald_root * _self = (struct __gald_root *)self;
  {
    gald_release(self);
  }
}

NFObject * __gald_root_retain(NFObject * self, SEL _cmd) {
  struct __gald_root * _self = (struct __gald_root *)self;
  {
    return gald_retain(self);
  }
}

NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
  return gald_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
  NFObject * obj = gald_alloc(self);
  return gald_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
  struct NFObject * _self = (struct NFObject *)self;
  {
    return gald_init(self);
  }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
  struct NFObject * _self = (struct NFObject *)self;
  {
    return;
  }
}

void NFObject_release(NFObject * self, SEL _cmd) {
  struct NFObject * _self = (struct NFObject *)self;
  {
    gald_release(self);
  }
}

NFObject * NFObject_retain(NFObject * self, SEL _cmd) {
  struct NFObject * _self = (struct NFObject *)self;
  {
    return gald_retain(self);
  }
}

void Buffer_add_(NFObject * self, SEL _cmd, NFObject * item) {
  struct Buffer * _self = (struct Buffer *)self;
  {
    if ((_self->_len < 2))     _self->_data[_self->_len++] = item;
  }
}

NFObject * Buffer_get(NFObject * self, SEL _cmd) {
  struct Buffer * _self = (struct Buffer *)self;
  {
    if ((_self->_len > 0))     {
      _self->_len--;
      NFObject * item = _self->_data[_self->_len];
      _self->_data[_self->_len] = 0;
      return item;
    }
    return 0;
  }
}

NFObject * gald_alloc(struct NFClass * cls);

NFObject * gald_init(NFObject * self);

void gald_release(NFObject * obj);

NFObject * gald_retain(NFObject * obj);

int main(void) {
  gald_meta_init();
  {
    NFObject *__gald_tmp_0 = (NFObject_alloc(&gald_Buffer_class, sel_registerName("alloc")));
    Buffer_A_ptr * aBuf = ((struct gald_NFObject_vtable *)__gald_tmp_0->isa->vtable)->init(__gald_tmp_0, sel_registerName("init"));
    NFObject *__gald_tmp_1 = (NFObject_alloc(&gald_Buffer_class, sel_registerName("alloc")));
    Buffer_B_ptr * bBuf = ((struct gald_NFObject_vtable *)__gald_tmp_1->isa->vtable)->init(__gald_tmp_1, sel_registerName("init"));
    printf("Two instantiations of Buffer exist\n");
  }
  return 0;
}

void Buffer_A_ptr_add_(A * self, SEL _cmd, A * item) {
  struct Buffer_A_ptr * _self = (struct Buffer_A_ptr *)self;
  {
    if ((_self->_len < 2))     _self->_data[_self->_len++] = item;
  }
}

A * Buffer_A_ptr_get(A * self, SEL _cmd) {
  struct Buffer_A_ptr * _self = (struct Buffer_A_ptr *)self;
  {
    if ((_self->_len > 0))     {
      _self->_len--;
      A * item = _self->_data[_self->_len];
      _self->_data[_self->_len] = 0;
      return item;
    }
    return 0;
  }
}

void Buffer_B_ptr_add_(B * self, SEL _cmd, B * item) {
  struct Buffer_B_ptr * _self = (struct Buffer_B_ptr *)self;
  {
    if ((_self->_len < 2))     _self->_data[_self->_len++] = item;
  }
}

B * Buffer_B_ptr_get(B * self, SEL _cmd) {
  struct Buffer_B_ptr * _self = (struct Buffer_B_ptr *)self;
  {
    if ((_self->_len > 0))     {
      _self->_len--;
      B * item = _self->_data[_self->_len];
      _self->_data[_self->_len] = 0;
      return item;
    }
    return 0;
  }
}

