// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"
struct nopa___nopa_root_vtable;
struct nopa_NPObject_vtable;
struct nopa_NPObject_meta_vtable;
struct nopa_Item_vtable;
struct nopa_Item_meta_vtable;
struct nopa_Holder_vtable;
struct nopa_Holder_meta_vtable;
struct nopa_Holder_Item_ptr_vtable;
struct nopa_Holder_Item_ptr_meta_vtable;

static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __nopa_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __nopa_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nopa_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __nopa_sel_put_ = {.name = "put:", .hash = 0xD36828BC};
static const SEL __nopa_sel_get = {.name = "get", .hash = 0x540CA757};

typedef struct __nopa_root __nopa_root;
typedef struct NPObject NPObject;
typedef struct Item Item;
typedef struct Holder Holder;
typedef struct Holder_Item_ptr Holder_Item_ptr;

NPObject * __nopa_root_init(NPObject * self, SEL _cmd);
void __nopa_root_dealloc(NPObject * self, SEL _cmd);
void __nopa_root_release(NPObject * self, SEL _cmd);
NPObject * __nopa_root_retain(NPObject * self, SEL _cmd);
NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
void NPObject_release(NPObject * self, SEL _cmd);
NPObject * NPObject_retain(NPObject * self, SEL _cmd);
void Holder_put_(NPObject * self, SEL _cmd, NPObject * item);
NPObject * Holder_get(NPObject * self, SEL _cmd);
NPObject * nopa_alloc(struct NPClass * cls);
NPObject * nopa_init(NPObject * self);
void nopa_release(NPObject * obj);
NPObject * nopa_retain(NPObject * obj);
int main(void);
void Holder_Item_ptr_put_(Item * self, SEL _cmd, Item * item);
Item * Holder_Item_ptr_get(Item * self, SEL _cmd);

NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPClass * Item_getClass(NPClass * self, SEL _cmd);
NPClass * Holder_getClass(NPClass * self, SEL _cmd);
NPClass * Holder_Item_ptr_getClass(NPClass * self, SEL _cmd);

struct nopa___nopa_root_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
};
struct nopa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
};
struct nopa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nopa_Item_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
};
struct nopa_Item_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nopa_Holder_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    void (*put_)(NPObject *, SEL, NPObject *);
    NPObject * (*get)(NPObject *, SEL);
};
struct nopa_Holder_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nopa_Holder_Item_ptr_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    void (*put_)(Item *, SEL, Item *);
    Item * (*get)(Item *, SEL);
};
struct nopa_Holder_Item_ptr_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};

struct __nopa_root {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct __nopa_root __nopa_root;

struct Item {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct Item Item;

struct Holder {
    struct NPClass *isa;
    uint32_t retain_count;
    NPObject * _data[4];
    int _count;
};
typedef struct Holder Holder;

struct Holder_Item_ptr {
    struct NPClass *isa;
    uint32_t retain_count;
    Item * _data[4];
    int _count;
};
typedef struct Holder_Item_ptr Holder_Item_ptr;

extern NPClass nopa___nopa_root_class;
extern NPClass nopa_NPObject_class;
extern NPClass nopa_Item_class;
extern NPClass nopa_Holder_class;
extern NPClass nopa_Holder_Item_ptr_class;
void nopa_meta_init(void);

struct nopa___nopa_root_vtable nopa___nopa_root_vtable_inst = {
    .init = __nopa_root_init,
    .dealloc = __nopa_root_dealloc,
    .release = __nopa_root_release,
    .retain = __nopa_root_retain,
};

struct nopa_NPObject_vtable nopa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
};

struct nopa_Item_vtable nopa_Item_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
};

struct nopa_Holder_vtable nopa_Holder_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .put_ = Holder_put_,
    .get = Holder_get,
};

struct nopa_Holder_Item_ptr_vtable nopa_Holder_Item_ptr_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .put_ = Holder_Item_ptr_put_,
    .get = Holder_Item_ptr_get,
};

struct nopa_NPObject_meta_vtable nopa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nopa_Item_meta_vtable nopa_Item_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Item_getClass,
};

struct nopa_Holder_meta_vtable nopa_Holder_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Holder_getClass,
};

struct nopa_Holder_Item_ptr_meta_vtable nopa_Holder_Item_ptr_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Holder_Item_ptr_getClass,
};

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Item_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Holder_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Holder_Item_ptr_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass nopa___nopa_root_class;
NPClass nopa_NPObject_class;
NPClass nopa_Item_class;
NPClass nopa_Holder_class;
NPClass nopa_Holder_Item_ptr_class;

void nopa_meta_init(void) {
    nopa___nopa_root_class = (NPClass){
        .name = "__nopa_root",
        .superclass = NULL,
        .instance_size = sizeof(struct __nopa_root),
        .vtable = &nopa___nopa_root_vtable_inst,
        .class_vtable = NULL,
        .protocol_count = 0,
    };
    nopa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = &nopa___nopa_root_class,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nopa_NPObject_vtable_inst,
        .class_vtable = &nopa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Item_class = (NPClass){
        .name = "Item",
        .superclass = &nopa_NPObject_class,
        .instance_size = sizeof(struct Item),
        .vtable = &nopa_Item_vtable_inst,
        .class_vtable = &nopa_Item_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Holder_class = (NPClass){
        .name = "Holder",
        .superclass = &nopa_NPObject_class,
        .instance_size = sizeof(struct Holder),
        .vtable = &nopa_Holder_vtable_inst,
        .class_vtable = &nopa_Holder_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Holder_Item_ptr_class = (NPClass){
        .name = "Holder<Item *>",
        .superclass = &nopa_NPObject_class,
        .instance_size = sizeof(struct Holder_Item_ptr),
        .vtable = &nopa_Holder_Item_ptr_vtable_inst,
        .class_vtable = &nopa_Holder_Item_ptr_meta_vtable_inst,
        .protocol_count = 0,
    };
}
NPObject * __nopa_root_init(NPObject * self, SEL _cmd) {
  struct __nopa_root * _self = (struct __nopa_root *)self;
  {
    return nopa_init(self);
  }
}

void __nopa_root_dealloc(NPObject * self, SEL _cmd) {
  struct __nopa_root * _self = (struct __nopa_root *)self;
  {
    return;
  }
}

void __nopa_root_release(NPObject * self, SEL _cmd) {
  struct __nopa_root * _self = (struct __nopa_root *)self;
  {
    nopa_release(self);
  }
}

NPObject * __nopa_root_retain(NPObject * self, SEL _cmd) {
  struct __nopa_root * _self = (struct __nopa_root *)self;
  {
    return nopa_retain(self);
  }
}

NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
  return nopa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
  NPObject * obj = nopa_alloc(self);
  return nopa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return nopa_init(self);
  }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return;
  }
}

void NPObject_release(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    nopa_release(self);
  }
}

NPObject * NPObject_retain(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return nopa_retain(self);
  }
}

void Holder_put_(NPObject * self, SEL _cmd, NPObject * item) {
  struct Holder * _self = (struct Holder *)self;
  {
    if ((_self->_count < 4))     _self->_data[_self->_count++] = item;
  }
}

NPObject * Holder_get(NPObject * self, SEL _cmd) {
  struct Holder * _self = (struct Holder *)self;
  {
    if ((_self->_count > 0))     return _self->_data[--_self->_count];
    return 0;
  }
}

NPObject * nopa_alloc(struct NPClass * cls);

NPObject * nopa_init(NPObject * self);

void nopa_release(NPObject * obj);

NPObject * nopa_retain(NPObject * obj);

int main(void) {
  nopa_meta_init();
  {
    NPObject *__nopa_tmp_0 = (NPObject_alloc(&nopa_Holder_class, sel_registerName("alloc")));
    Holder_Item_ptr * holder = ((struct nopa_NPObject_vtable *)__nopa_tmp_0->isa->vtable)->init(__nopa_tmp_0, sel_registerName("init"));
    NPObject *__nopa_tmp_1 = (NPObject_alloc(&nopa_Item_class, sel_registerName("alloc")));
    Item * r = ((struct nopa_NPObject_vtable *)__nopa_tmp_1->isa->vtable)->init(__nopa_tmp_1, sel_registerName("init"));
    ((struct nopa_Holder_vtable *)((NPObject *)(holder))->isa->vtable)->put_(holder, sel_registerName("put:"), r);
    Item * r2 = ((struct nopa_Holder_vtable *)((NPObject *)(holder))->isa->vtable)->get(holder, sel_registerName("get"));
    printf("Holder<Item*> works: %p\n", (void *)r2);
  }
  return 0;
}

void Holder_Item_ptr_put_(Item * self, SEL _cmd, Item * item) {
  struct Holder_Item_ptr * _self = (struct Holder_Item_ptr *)self;
  {
    if ((_self->_count < 4))     _self->_data[_self->_count++] = item;
  }
}

Item * Holder_Item_ptr_get(Item * self, SEL _cmd) {
  struct Holder_Item_ptr * _self = (struct Holder_Item_ptr *)self;
  {
    if ((_self->_count > 0))     return _self->_data[--_self->_count];
    return 0;
  }
}

