// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"


#include <string.h>

struct nopa_NFObject_vtable;
struct nopa_Board_vtable;

#define nopa_NFObject_vtable_index_init 2
#define nopa_NFObject_vtable_index_dealloc 3

static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nopa_sel_board = {.name = "board", .hash = 0xEF92FE2B};

typedef struct NFObject NFObject;
typedef struct Board Board;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
int * Board_board(NFObject * self, SEL _cmd);
void Board_setBoard_(NFObject * self, SEL _cmd, int * value);
NFClass * Board_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass nopa_NFObject_class;
extern NFClass nopa_Board_class;
void nopa_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct nopa_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct nopa_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct Board {
    struct NFClass *isa;
    uint32_t retain_count;
    int _board[9];
};
typedef struct Board Board;
struct nopa_Board_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    int * (*board)(NFObject *, SEL);
    void (*setBoard_)(NFObject *, SEL, int *);
};
struct nopa_Board_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return nopa_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = nopa_alloc(self);
    return nopa_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return nopa_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &nopa_NFObject_class;
}

NFObject * nopa_alloc(struct NFClass * cls);
NFObject * nopa_init(NFObject * );
int * Board_board(NFObject * self, SEL _cmd) {
    return ((struct Board *)(self))->_board;
}

void Board_setBoard_(NFObject * self, SEL _cmd, int * value) {
    memcpy(&((struct Board *)(self))->_board, value, sizeof(((struct Board *)(0))->_board));
}

NFClass * Board_getClass(NFClass * self, SEL _cmd) {
    return &nopa_Board_class;
}

int main() {
    nopa_autoreleasepool_t *__pool = nopa_autoreleasepool_push();
    nopa_meta_init();
    NFObject *__nopa_tmp_0 = (NFObject_alloc(&nopa_Board_class, __nopa_sel_alloc));
    Board * b = ((struct nopa_NFObject_vtable *)__nopa_tmp_0->isa->vtable)->init(__nopa_tmp_0, __nopa_sel_init);
    b->_board[0] = 1;
    b->_board[4] = 2;
    b->_board[8] = 3;
    printf("%d %d %d\n", ((struct nopa_Board_vtable *)b->isa->vtable)->board(b, __nopa_sel_board)[0], ((struct nopa_Board_vtable *)b->isa->vtable)->board(b, __nopa_sel_board)[4], ((struct nopa_Board_vtable *)b->isa->vtable)->board(b, __nopa_sel_board)[8]);
    return 0;
    nopa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nopa_NFObject_vtable nopa_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct nopa_Board_vtable nopa_Board_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .board = Board_board,
    .setBoard_ = Board_setBoard_,
};

struct nopa_NFObject_meta_vtable nopa_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct nopa_Board_meta_vtable nopa_Board_meta_vtable_inst = {
    .class = Board_getClass,
};

NFClass nopa_NFObject_class;
NFClass nopa_Board_class;

void nopa_meta_init(void) {
    nopa_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &nopa_NFObject_vtable_inst,
        .class_vtable = &nopa_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Board_class = (NFClass){
        .name = "Board",
        .superclass = &nopa_NFObject_class,
        .instance_size = sizeof(struct Board),
        .vtable = &nopa_Board_vtable_inst,
        .class_vtable = &nopa_Board_meta_vtable_inst,
        .protocol_count = 0,
    };
}
