// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"


#include <string.h>

struct nopa_NFObject_vtable;
struct nopa_Printer_vtable;

#define nopa_NFObject_vtable_index_init 2
#define nopa_NFObject_vtable_index_dealloc 3
#define nopa_Printer_vtable_index_print_ 4

static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nopa_sel_print_ = {.name = "print_", .hash = 0xD06F9075};

typedef struct NFObject NFObject;
typedef struct Printer Printer;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
void Printer_print_(NFObject * self, SEL _cmd, char * msg);
NFClass * Printer_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass nopa_NFObject_class;
extern NFClass nopa_Printer_class;
void nopa_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct nopa_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct nopa_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct Printer {
    struct NFClass *isa;
    uint32_t retain_count;
};
typedef struct Printer Printer;
struct nopa_Printer_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    void (*print_)(NFObject *, SEL, char *);
};
struct nopa_Printer_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return nopa_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = nopa_alloc(self);
    return nopa_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return nopa_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &nopa_NFObject_class;
}

NFObject * nopa_alloc(struct NFClass * cls);
NFObject * nopa_init(NFObject * );
void Printer_print_(NFObject * self, SEL _cmd, char * msg) {
    struct Printer * _self = ((struct Printer *)(self));
    {
        printf("%s\n", msg);
    }
}

NFClass * Printer_getClass(NFClass * self, SEL _cmd) {
    return &nopa_Printer_class;
}

int main() {
    nopa_autoreleasepool_t *__pool = nopa_autoreleasepool_push();
    nopa_meta_init();
    NFObject *__nopa_tmp_0 = (NFObject_alloc(&nopa_Printer_class, __nopa_sel_alloc));
    Printer * p = ((struct nopa_NFObject_vtable *)__nopa_tmp_0->isa->vtable)->init(__nopa_tmp_0, __nopa_sel_init);
    ((struct nopa_Printer_vtable *)p->isa->vtable)->print_(p, __nopa_sel_print_, "Hello from Micrit!");
    return 0;
    nopa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nopa_NFObject_vtable nopa_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct nopa_Printer_vtable nopa_Printer_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .print_ = Printer_print_,
};

struct nopa_NFObject_meta_vtable nopa_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct nopa_Printer_meta_vtable nopa_Printer_meta_vtable_inst = {
    .class = Printer_getClass,
};

NFClass nopa_NFObject_class;
NFClass nopa_Printer_class;

void nopa_meta_init(void) {
    nopa_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &nopa_NFObject_vtable_inst,
        .class_vtable = &nopa_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Printer_class = (NFClass){
        .name = "Printer",
        .superclass = &nopa_NFObject_class,
        .instance_size = sizeof(struct Printer),
        .vtable = &nopa_Printer_vtable_inst,
        .class_vtable = &nopa_Printer_meta_vtable_inst,
        .protocol_count = 0,
    };
}
