// Generated by nepac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nepa/runtime.h"


#include <string.h>

struct nepa_NPObject_vtable;
struct nepa_ForwardDeclared_vtable;
struct nepa_Container_vtable;

#define nepa_NPObject_vtable_index_init 2
#define nepa_NPObject_vtable_index_dealloc 3

static const SEL __nepa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nepa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nepa_sel_item = {.name = "item", .hash = 0x9F3833E6};
static const SEL __nepa_sel_value = {.name = "value", .hash = 0x425ED3CA};

typedef struct NPObject NPObject;
typedef struct ForwardDeclared ForwardDeclared;
typedef struct Container Container;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
int ForwardDeclared_value(NPObject * self, SEL _cmd);
void ForwardDeclared_setValue_(NPObject * self, SEL _cmd, int value);
NPClass * ForwardDeclared_getClass(NPClass * self, SEL _cmd);
ForwardDeclared * Container_item(NPObject * self, SEL _cmd);
void Container_setItem_(NPObject * self, SEL _cmd, ForwardDeclared * value);
NPClass * Container_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nepa_NPObject_class;
extern NPClass nepa_ForwardDeclared_class;
extern NPClass nepa_Container_class;
void nepa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nepa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nepa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct ForwardDeclared {
    struct NPClass *isa;
    uint32_t retain_count;
    int _value;
};
typedef struct ForwardDeclared ForwardDeclared;
struct nepa_ForwardDeclared_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    int (*value)(NPObject *, SEL);
    void (*setValue_)(NPObject *, SEL, int);
};
struct nepa_ForwardDeclared_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct Container {
    struct NPClass *isa;
    uint32_t retain_count;
    ForwardDeclared * _item;
};
typedef struct Container Container;
struct nepa_Container_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    ForwardDeclared * (*item)(NPObject *, SEL);
    void (*setItem_)(NPObject *, SEL, ForwardDeclared *);
};
struct nepa_Container_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nepa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nepa_alloc(self);
    return nepa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nepa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nepa_NPObject_class;
}

NPObject * nepa_alloc(struct NPClass * cls);
NPObject * nepa_init(NPObject * );
int ForwardDeclared_value(NPObject * self, SEL _cmd) {
    return ((struct ForwardDeclared *)(self))->_value;
}

void ForwardDeclared_setValue_(NPObject * self, SEL _cmd, int value) {
    ((struct ForwardDeclared *)(self))->_value = value;
}

NPClass * ForwardDeclared_getClass(NPClass * self, SEL _cmd) {
    return &nepa_ForwardDeclared_class;
}

ForwardDeclared * Container_item(NPObject * self, SEL _cmd) {
    return ((struct Container *)(self))->_item;
}

void Container_setItem_(NPObject * self, SEL _cmd, ForwardDeclared * value) {
    ((struct Container *)(self))->_item = value;
}

NPClass * Container_getClass(NPClass * self, SEL _cmd) {
    return &nepa_Container_class;
}

int main() {
    nepa_autoreleasepool_t *__pool = nepa_autoreleasepool_push();
    nepa_meta_init();
    NPObject *__nepa_tmp_0 = (NPObject_alloc(&nepa_Container_class, __nepa_sel_alloc));
    Container * c = ((struct nepa_NPObject_vtable *)__nepa_tmp_0->isa->vtable)->init(__nepa_tmp_0, __nepa_sel_init);
    NPObject *__nepa_tmp_1 = (NPObject_alloc(&nepa_ForwardDeclared_class, __nepa_sel_alloc));
    ForwardDeclared * f = ((struct nepa_NPObject_vtable *)__nepa_tmp_1->isa->vtable)->init(__nepa_tmp_1, __nepa_sel_init);
    f->_value = 42;
    c->_item = f;
    ForwardDeclared * tmp = ((struct nepa_Container_vtable *)c->isa->vtable)->item(c, __nepa_sel_item);
    printf("value=%d\n", ((struct nepa_ForwardDeclared_vtable *)tmp->isa->vtable)->value(tmp, __nepa_sel_value));
    return 0;
    nepa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nepa_NPObject_vtable nepa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nepa_ForwardDeclared_vtable nepa_ForwardDeclared_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .value = ForwardDeclared_value,
    .setValue_ = ForwardDeclared_setValue_,
};

struct nepa_Container_vtable nepa_Container_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .item = Container_item,
    .setItem_ = Container_setItem_,
};

struct nepa_NPObject_meta_vtable nepa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nepa_ForwardDeclared_meta_vtable nepa_ForwardDeclared_meta_vtable_inst = {
    .class = ForwardDeclared_getClass,
};

struct nepa_Container_meta_vtable nepa_Container_meta_vtable_inst = {
    .class = Container_getClass,
};

NPClass nepa_NPObject_class;
NPClass nepa_ForwardDeclared_class;
NPClass nepa_Container_class;

void nepa_meta_init(void) {
    nepa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nepa_NPObject_vtable_inst,
        .class_vtable = &nepa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nepa_ForwardDeclared_class = (NPClass){
        .name = "ForwardDeclared",
        .superclass = &nepa_NPObject_class,
        .instance_size = sizeof(struct ForwardDeclared),
        .vtable = &nepa_ForwardDeclared_vtable_inst,
        .class_vtable = &nepa_ForwardDeclared_meta_vtable_inst,
        .protocol_count = 0,
    };
    nepa_Container_class = (NPClass){
        .name = "Container",
        .superclass = &nepa_NPObject_class,
        .instance_size = sizeof(struct Container),
        .vtable = &nepa_Container_vtable_inst,
        .class_vtable = &nepa_Container_meta_vtable_inst,
        .protocol_count = 0,
    };
}
