// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"


#include <string.h>

struct nopa_NFObject_vtable;
struct nopa_ForwardDeclared_vtable;
struct nopa_Container_vtable;

#define nopa_NFObject_vtable_index_init 2
#define nopa_NFObject_vtable_index_dealloc 3

static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nopa_sel_item = {.name = "item", .hash = 0x9F3833E6};
static const SEL __nopa_sel_value = {.name = "value", .hash = 0x425ED3CA};

typedef struct NFObject NFObject;
typedef struct ForwardDeclared ForwardDeclared;
typedef struct Container Container;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
int ForwardDeclared_value(NFObject * self, SEL _cmd);
void ForwardDeclared_setValue_(NFObject * self, SEL _cmd, int value);
NFClass * ForwardDeclared_getClass(NFClass * self, SEL _cmd);
ForwardDeclared * Container_item(NFObject * self, SEL _cmd);
void Container_setItem_(NFObject * self, SEL _cmd, ForwardDeclared * value);
NFClass * Container_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass nopa_NFObject_class;
extern NFClass nopa_ForwardDeclared_class;
extern NFClass nopa_Container_class;
void nopa_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct nopa_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct nopa_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct ForwardDeclared {
    struct NFClass *isa;
    uint32_t retain_count;
    int _value;
};
typedef struct ForwardDeclared ForwardDeclared;
struct nopa_ForwardDeclared_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    int (*value)(NFObject *, SEL);
    void (*setValue_)(NFObject *, SEL, int);
};
struct nopa_ForwardDeclared_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
struct Container {
    struct NFClass *isa;
    uint32_t retain_count;
    ForwardDeclared * _item;
};
typedef struct Container Container;
struct nopa_Container_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    ForwardDeclared * (*item)(NFObject *, SEL);
    void (*setItem_)(NFObject *, SEL, ForwardDeclared *);
};
struct nopa_Container_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return nopa_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = nopa_alloc(self);
    return nopa_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return nopa_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &nopa_NFObject_class;
}

NFObject * nopa_alloc(struct NFClass * cls);
NFObject * nopa_init(NFObject * );
int ForwardDeclared_value(NFObject * self, SEL _cmd) {
    return ((struct ForwardDeclared *)(self))->_value;
}

void ForwardDeclared_setValue_(NFObject * self, SEL _cmd, int value) {
    ((struct ForwardDeclared *)(self))->_value = value;
}

NFClass * ForwardDeclared_getClass(NFClass * self, SEL _cmd) {
    return &nopa_ForwardDeclared_class;
}

ForwardDeclared * Container_item(NFObject * self, SEL _cmd) {
    return ((struct Container *)(self))->_item;
}

void Container_setItem_(NFObject * self, SEL _cmd, ForwardDeclared * value) {
    ((struct Container *)(self))->_item = value;
}

NFClass * Container_getClass(NFClass * self, SEL _cmd) {
    return &nopa_Container_class;
}

int main() {
    nopa_autoreleasepool_t *__pool = nopa_autoreleasepool_push();
    nopa_meta_init();
    NFObject *__nopa_tmp_0 = (NFObject_alloc(&nopa_Container_class, __nopa_sel_alloc));
    Container * c = ((struct nopa_NFObject_vtable *)__nopa_tmp_0->isa->vtable)->init(__nopa_tmp_0, __nopa_sel_init);
    NFObject *__nopa_tmp_1 = (NFObject_alloc(&nopa_ForwardDeclared_class, __nopa_sel_alloc));
    ForwardDeclared * f = ((struct nopa_NFObject_vtable *)__nopa_tmp_1->isa->vtable)->init(__nopa_tmp_1, __nopa_sel_init);
    f->_value = 42;
    c->_item = f;
    ForwardDeclared * tmp = ((struct nopa_Container_vtable *)c->isa->vtable)->item(c, __nopa_sel_item);
    printf("value=%d\n", ((struct nopa_ForwardDeclared_vtable *)tmp->isa->vtable)->value(tmp, __nopa_sel_value));
    return 0;
    nopa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nopa_NFObject_vtable nopa_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct nopa_ForwardDeclared_vtable nopa_ForwardDeclared_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .value = ForwardDeclared_value,
    .setValue_ = ForwardDeclared_setValue_,
};

struct nopa_Container_vtable nopa_Container_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .item = Container_item,
    .setItem_ = Container_setItem_,
};

struct nopa_NFObject_meta_vtable nopa_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct nopa_ForwardDeclared_meta_vtable nopa_ForwardDeclared_meta_vtable_inst = {
    .class = ForwardDeclared_getClass,
};

struct nopa_Container_meta_vtable nopa_Container_meta_vtable_inst = {
    .class = Container_getClass,
};

NFClass nopa_NFObject_class;
NFClass nopa_ForwardDeclared_class;
NFClass nopa_Container_class;

void nopa_meta_init(void) {
    nopa_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &nopa_NFObject_vtable_inst,
        .class_vtable = &nopa_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_ForwardDeclared_class = (NFClass){
        .name = "ForwardDeclared",
        .superclass = &nopa_NFObject_class,
        .instance_size = sizeof(struct ForwardDeclared),
        .vtable = &nopa_ForwardDeclared_vtable_inst,
        .class_vtable = &nopa_ForwardDeclared_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Container_class = (NFClass){
        .name = "Container",
        .superclass = &nopa_NFObject_class,
        .instance_size = sizeof(struct Container),
        .vtable = &nopa_Container_vtable_inst,
        .class_vtable = &nopa_Container_meta_vtable_inst,
        .protocol_count = 0,
    };
}
