// Generated by galdc
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "gald/runtime.h"


#include <string.h>

struct gald_NFObject_vtable;
struct gald_Num_vtable;

#define gald_NFObject_vtable_index_init 2
#define gald_NFObject_vtable_index_dealloc 3
#define gald_Num_vtable_index_getValue 4

static const SEL __gald_sel_getValue = {.name = "getValue", .hash = 0xF55160EC};
static const SEL __gald_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __gald_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};

typedef struct NFObject NFObject;
typedef struct Num Num;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
int Num_getValue(NFObject * self, SEL _cmd);
NFClass * Num_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass gald_NFObject_class;
extern NFClass gald_Num_class;
void gald_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct gald_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct gald_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct Num {
    struct NFClass *isa;
    uint32_t retain_count;
};
typedef struct Num Num;
struct gald_Num_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    int (*getValue)(NFObject *, SEL);
};
struct gald_Num_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return gald_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = gald_alloc(self);
    return gald_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return gald_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFObject_class;
}

NFObject * gald_alloc(struct NFClass * cls);
NFObject * gald_init(NFObject * );
int Num_getValue(NFObject * self, SEL _cmd) {
    struct Num * _self = ((struct Num *)(self));
    {
        return 7;
    }
}

NFClass * Num_getClass(NFClass * self, SEL _cmd) {
    return &gald_Num_class;
}

int main() {
    gald_autoreleasepool_t *__pool = gald_autoreleasepool_push();
    gald_meta_init();
    NFObject *__gald_tmp_0 = (({ NFObject *__gald_tmp_1 = (NFObject_alloc(&gald_Num_class, __gald_sel_alloc)); ((struct gald_NFObject_vtable *)__gald_tmp_1->isa->vtable)->init(__gald_tmp_1, __gald_sel_init); }));
    int val = ((struct gald_Num_vtable *)__gald_tmp_0->isa->vtable)->getValue(__gald_tmp_0, __gald_sel_getValue);
    printf("val=%d\n", val);
    return 0;
    gald_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct gald_NFObject_vtable gald_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct gald_Num_vtable gald_Num_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .getValue = Num_getValue,
};

struct gald_NFObject_meta_vtable gald_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct gald_Num_meta_vtable gald_Num_meta_vtable_inst = {
    .class = Num_getClass,
};

NFClass gald_NFObject_class;
NFClass gald_Num_class;

void gald_meta_init(void) {
    gald_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &gald_NFObject_vtable_inst,
        .class_vtable = &gald_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_Num_class = (NFClass){
        .name = "Num",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct Num),
        .vtable = &gald_Num_vtable_inst,
        .class_vtable = &gald_Num_meta_vtable_inst,
        .protocol_count = 0,
    };
}
