// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"


#include <string.h>

struct nopa_NPObject_vtable;
struct nopa_Player_vtable;

#define nopa_NPObject_vtable_index_init 2
#define nopa_NPObject_vtable_index_dealloc 3
#define nopa_Player_vtable_index_initWithLevel_ 4

static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_initWithLevel_ = {.name = "initWithLevel_", .hash = 0x335A278C};
static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};

typedef struct NPObject NPObject;
typedef struct Player Player;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * Player_initWithLevel_(NPObject * self, SEL _cmd, int l);
NPClass * Player_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nopa_NPObject_class;
extern NPClass nopa_Player_class;
void nopa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nopa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nopa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Player {
    struct NPClass *isa;
    uint32_t retain_count;
    int level;
};
typedef struct Player Player;
struct nopa_Player_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithLevel_)(NPObject *, SEL, int);
};
struct nopa_Player_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nopa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nopa_alloc(self);
    return nopa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nopa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nopa_NPObject_class;
}

NPObject * nopa_alloc(struct NPClass * cls);
NPObject * nopa_init(NPObject * );
NPObject * Player_initWithLevel_(NPObject * self, SEL _cmd, int l) {
    struct Player * _self = ((struct Player *)(self));
    {
        self = NPObject_init(self, __nopa_sel_init);
        if (self) {
            ((struct Player *)(self))->level = l;
        }
        return self;
    }
}

NPClass * Player_getClass(NPClass * self, SEL _cmd) {
    return &nopa_Player_class;
}

int main() {
    nopa_autoreleasepool_t *__pool = nopa_autoreleasepool_push();
    nopa_meta_init();
    {
        nopa_autoreleasepool_t * __pool = nopa_autoreleasepool_push();
        {
            NPObject *__nopa_tmp_0 = (NPObject_alloc(&nopa_Player_class, __nopa_sel_alloc));
            Player * p = ((struct nopa_Player_vtable *)__nopa_tmp_0->isa->vtable)->initWithLevel_(__nopa_tmp_0, __nopa_sel_initWithLevel_, 10);
            NPLog((NPString *)nopa_stringFromCstr("player: %s"), p ? [[p description] UTF8String] : "(null)");
            printf("level: %d\n", ((struct Player *)(p))->level);
            nopa_release(p);
        }
        nopa_autoreleasepool_pop(__pool);
    }
    printf("description OK\n");
    return 0;
    nopa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nopa_NPObject_vtable nopa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nopa_Player_vtable nopa_Player_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithLevel_ = Player_initWithLevel_,
};

struct nopa_NPObject_meta_vtable nopa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nopa_Player_meta_vtable nopa_Player_meta_vtable_inst = {
    .class = Player_getClass,
};

NPClass nopa_NPObject_class;
NPClass nopa_Player_class;

void nopa_meta_init(void) {
    nopa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nopa_NPObject_vtable_inst,
        .class_vtable = &nopa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Player_class = (NPClass){
        .name = "Player",
        .superclass = &nopa_NPObject_class,
        .instance_size = sizeof(struct Player),
        .vtable = &nopa_Player_vtable_inst,
        .class_vtable = &nopa_Player_meta_vtable_inst,
        .protocol_count = 0,
    };
}
