// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"


#include <string.h>

struct nopa_NFObject_vtable;
struct nopa_Game__Player_vtable;
struct nopa_UI__HUD_vtable;

#define nopa_NFObject_vtable_index_init 2
#define nopa_NFObject_vtable_index_dealloc 3
#define nopa_Game__Player_vtable_index_initWithLevel_ 4
#define nopa_UI__HUD_vtable_index_initWithValue_ 4

static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_initWithLevel_ = {.name = "initWithLevel_", .hash = 0x335A278C};
static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nopa_sel_initWithValue_ = {.name = "initWithValue_", .hash = 0xF0E5A305};

typedef struct NFObject NFObject;
typedef struct Game__Player Game__Player;
typedef struct UI__HUD UI__HUD;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
NFObject * Game__Player_initWithLevel_(NFObject * self, SEL _cmd, int l);
NFClass * Game__Player_getClass(NFClass * self, SEL _cmd);
NFObject * UI__HUD_initWithValue_(NFObject * self, SEL _cmd, int v);
NFClass * UI__HUD_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass nopa_NFObject_class;
extern NFClass nopa_Game__Player_class;
extern NFClass nopa_UI__HUD_class;
void nopa_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct nopa_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct nopa_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct Game__Player {
    struct NFClass *isa;
    uint32_t retain_count;
    int level;
};
typedef struct Game__Player Game__Player;
struct nopa_Game__Player_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    NFObject * (*initWithLevel_)(NFObject *, SEL, int);
};
struct nopa_Game__Player_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
struct UI__HUD {
    struct NFClass *isa;
    uint32_t retain_count;
    int value;
};
typedef struct UI__HUD UI__HUD;
struct nopa_UI__HUD_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    NFObject * (*initWithValue_)(NFObject *, SEL, int);
};
struct nopa_UI__HUD_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return nopa_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = nopa_alloc(self);
    return nopa_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return nopa_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &nopa_NFObject_class;
}

NFObject * nopa_alloc(struct NFClass * cls);
NFObject * nopa_init(NFObject * );
NFObject * Game__Player_initWithLevel_(NFObject * self, SEL _cmd, int l) {
    struct Game__Player * _self = ((struct Game__Player *)(self));
    {
        self = NFObject_init(self, __nopa_sel_init);
        if (self) {
            ((struct Game__Player *)(self))->level = l;
        }
        return self;
    }
}

NFClass * Game__Player_getClass(NFClass * self, SEL _cmd) {
    return &nopa_Game__Player_class;
}

NFObject * UI__HUD_initWithValue_(NFObject * self, SEL _cmd, int v) {
    struct UI__HUD * _self = ((struct UI__HUD *)(self));
    {
        self = NFObject_init(self, __nopa_sel_init);
        if (self) {
            ((struct UI__HUD *)(self))->value = v;
        }
        return self;
    }
}

NFClass * UI__HUD_getClass(NFClass * self, SEL _cmd) {
    return &nopa_UI__HUD_class;
}

int main() {
    nopa_autoreleasepool_t *__pool = nopa_autoreleasepool_push();
    nopa_meta_init();
    {
        nopa_autoreleasepool_t * __pool = nopa_autoreleasepool_push();
        {
            NFObject *__nopa_tmp_0 = (NFObject_alloc(&nopa_Game__Player_class, __nopa_sel_alloc));
            Game__Player * p = ((struct nopa_Game__Player_vtable *)__nopa_tmp_0->isa->vtable)->initWithLevel_(__nopa_tmp_0, __nopa_sel_initWithLevel_, 10);
            NFObject *__nopa_tmp_1 = (NFObject_alloc(&nopa_UI__HUD_class, __nopa_sel_alloc));
            UI__HUD * h = ((struct nopa_UI__HUD_vtable *)__nopa_tmp_1->isa->vtable)->initWithValue_(__nopa_tmp_1, __nopa_sel_initWithValue_, 42);
            printf("[alias] Player level=%d, HUD value=%d\n", ((struct Game__Player *)(p))->level, ((struct UI__HUD *)(h))->value);
            nopa_release(p);
            nopa_release(h);
        }
        nopa_autoreleasepool_pop(__pool);
    }
    return 0;
    nopa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nopa_NFObject_vtable nopa_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct nopa_Game__Player_vtable nopa_Game__Player_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .initWithLevel_ = Game__Player_initWithLevel_,
};

struct nopa_UI__HUD_vtable nopa_UI__HUD_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .initWithValue_ = UI__HUD_initWithValue_,
};

struct nopa_NFObject_meta_vtable nopa_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct nopa_Game__Player_meta_vtable nopa_Game__Player_meta_vtable_inst = {
    .class = Game__Player_getClass,
};

struct nopa_UI__HUD_meta_vtable nopa_UI__HUD_meta_vtable_inst = {
    .class = UI__HUD_getClass,
};

NFClass nopa_NFObject_class;
NFClass nopa_Game__Player_class;
NFClass nopa_UI__HUD_class;

void nopa_meta_init(void) {
    nopa_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &nopa_NFObject_vtable_inst,
        .class_vtable = &nopa_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Game__Player_class = (NFClass){
        .name = "Game__Player",
        .superclass = &nopa_NFObject_class,
        .instance_size = sizeof(struct Game__Player),
        .vtable = &nopa_Game__Player_vtable_inst,
        .class_vtable = &nopa_Game__Player_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_UI__HUD_class = (NFClass){
        .name = "UI__HUD",
        .superclass = &nopa_NFObject_class,
        .instance_size = sizeof(struct UI__HUD),
        .vtable = &nopa_UI__HUD_vtable_inst,
        .class_vtable = &nopa_UI__HUD_meta_vtable_inst,
        .protocol_count = 0,
    };
}
