// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"


#include <string.h>

struct nopa_NFObject_vtable;
struct nopa_Game__Player_vtable;
struct nopa_Game__Enemy_vtable;

#define nopa_NFObject_vtable_index_init 2
#define nopa_NFObject_vtable_index_dealloc 3
#define nopa_Game__Player_vtable_index_initWithId_ 4
#define nopa_Game__Enemy_vtable_index_initWithHP_ 4

static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_initWithId_ = {.name = "initWithId_", .hash = 0x8CE5C4CB};
static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nopa_sel_initWithHP_ = {.name = "initWithHP_", .hash = 0xF9AEAB6C};

typedef struct NFObject NFObject;
typedef struct Game__Player Game__Player;
typedef struct Game__Enemy Game__Enemy;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
NFObject * Game__Player_initWithId_(NFObject * self, SEL _cmd, int i);
NFClass * Game__Player_getClass(NFClass * self, SEL _cmd);
NFObject * Game__Enemy_initWithHP_(NFObject * self, SEL _cmd, int h);
NFClass * Game__Enemy_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass nopa_NFObject_class;
extern NFClass nopa_Game__Player_class;
extern NFClass nopa_Game__Enemy_class;
void nopa_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct nopa_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct nopa_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct Game__Player {
    struct NFClass *isa;
    uint32_t retain_count;
    int id;
};
typedef struct Game__Player Game__Player;
struct nopa_Game__Player_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    NFObject * (*initWithId_)(NFObject *, SEL, int);
};
struct nopa_Game__Player_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
struct Game__Enemy {
    struct NFClass *isa;
    uint32_t retain_count;
    int hp;
};
typedef struct Game__Enemy Game__Enemy;
struct nopa_Game__Enemy_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
    NFObject * (*initWithHP_)(NFObject *, SEL, int);
};
struct nopa_Game__Enemy_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return nopa_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = nopa_alloc(self);
    return nopa_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return nopa_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &nopa_NFObject_class;
}

NFObject * nopa_alloc(struct NFClass * cls);
NFObject * nopa_init(NFObject * );
NFObject * Game__Player_initWithId_(NFObject * self, SEL _cmd, int i) {
    struct Game__Player * _self = ((struct Game__Player *)(self));
    {
        self = NFObject_init(self, __nopa_sel_init);
        if (self) {
            return self;
        }
    }
}

NFClass * Game__Player_getClass(NFClass * self, SEL _cmd) {
    return &nopa_Game__Player_class;
}

NFObject * Game__Enemy_initWithHP_(NFObject * self, SEL _cmd, int h) {
    struct Game__Enemy * _self = ((struct Game__Enemy *)(self));
    {
        self = NFObject_init(self, __nopa_sel_init);
        if (self) {
            ((struct Game__Enemy *)(self))->hp = h;
        }
        return self;
    }
}

NFClass * Game__Enemy_getClass(NFClass * self, SEL _cmd) {
    return &nopa_Game__Enemy_class;
}

int main() {
    nopa_autoreleasepool_t *__pool = nopa_autoreleasepool_push();
    nopa_meta_init();
    {
        nopa_autoreleasepool_t * __pool = nopa_autoreleasepool_push();
        {
            NFObject *__nopa_tmp_0 = (NFObject_alloc(&nopa_Game__Player_class, __nopa_sel_alloc));
            Game__Player * p = ((struct nopa_Game__Player_vtable *)__nopa_tmp_0->isa->vtable)->initWithId_(__nopa_tmp_0, __nopa_sel_initWithId_, 7);
            NFObject *__nopa_tmp_1 = (NFObject_alloc(&nopa_Game__Enemy_class, __nopa_sel_alloc));
            Game__Enemy * e = ((struct nopa_Game__Enemy_vtable *)__nopa_tmp_1->isa->vtable)->initWithHP_(__nopa_tmp_1, __nopa_sel_initWithHP_, 80);
            printf("[using_ns] Player id=%d, Enemy hp=%d\n", ((struct Game__Player *)(p))->id, ((struct Game__Enemy *)(e))->hp);
            nopa_release(p);
            nopa_release(e);
        }
        nopa_autoreleasepool_pop(__pool);
    }
    return 0;
    nopa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nopa_NFObject_vtable nopa_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct nopa_Game__Player_vtable nopa_Game__Player_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .initWithId_ = Game__Player_initWithId_,
};

struct nopa_Game__Enemy_vtable nopa_Game__Enemy_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
    .initWithHP_ = Game__Enemy_initWithHP_,
};

struct nopa_NFObject_meta_vtable nopa_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct nopa_Game__Player_meta_vtable nopa_Game__Player_meta_vtable_inst = {
    .class = Game__Player_getClass,
};

struct nopa_Game__Enemy_meta_vtable nopa_Game__Enemy_meta_vtable_inst = {
    .class = Game__Enemy_getClass,
};

NFClass nopa_NFObject_class;
NFClass nopa_Game__Player_class;
NFClass nopa_Game__Enemy_class;

void nopa_meta_init(void) {
    nopa_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &nopa_NFObject_vtable_inst,
        .class_vtable = &nopa_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Game__Player_class = (NFClass){
        .name = "Game__Player",
        .superclass = &nopa_NFObject_class,
        .instance_size = sizeof(struct Game__Player),
        .vtable = &nopa_Game__Player_vtable_inst,
        .class_vtable = &nopa_Game__Player_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Game__Enemy_class = (NFClass){
        .name = "Game__Enemy",
        .superclass = &nopa_NFObject_class,
        .instance_size = sizeof(struct Game__Enemy),
        .vtable = &nopa_Game__Enemy_vtable_inst,
        .class_vtable = &nopa_Game__Enemy_meta_vtable_inst,
        .protocol_count = 0,
    };
}
