// Generated by nepac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nepa/runtime.h"


#include <string.h>

struct nepa_NPObject_vtable;
struct nepa_Game__Player_vtable;

#define nepa_NPObject_vtable_index_init 2
#define nepa_NPObject_vtable_index_dealloc 3
#define nepa_Game__Player_vtable_index_initWithScore_ 4

static const SEL __nepa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nepa_sel_initWithScore_ = {.name = "initWithScore_", .hash = 0xB141A938};
static const SEL __nepa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};

typedef struct NPObject NPObject;
typedef struct Game__Player Game__Player;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPObject * Game__Player_initWithScore_(NPObject * self, SEL _cmd, int s);
NPClass * Game__Player_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nepa_NPObject_class;
extern NPClass nepa_Game__Player_class;
void nepa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nepa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nepa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Game__Player {
    struct NPClass *isa;
    uint32_t retain_count;
    int score;
};
typedef struct Game__Player Game__Player;
struct nepa_Game__Player_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    NPObject * (*initWithScore_)(NPObject *, SEL, int);
};
struct nepa_Game__Player_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nepa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nepa_alloc(self);
    return nepa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nepa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nepa_NPObject_class;
}

NPObject * nepa_alloc(struct NPClass * cls);
NPObject * nepa_init(NPObject * );
NPObject * Game__Player_initWithScore_(NPObject * self, SEL _cmd, int s) {
    struct Game__Player * _self = ((struct Game__Player *)(self));
    {
        self = NPObject_init(self, __nepa_sel_init);
        if (self) {
            ((struct Game__Player *)(self))->score = s;
        }
        return self;
    }
}

NPClass * Game__Player_getClass(NPClass * self, SEL _cmd) {
    return &nepa_Game__Player_class;
}

int main() {
    nepa_autoreleasepool_t *__pool = nepa_autoreleasepool_push();
    nepa_meta_init();
    {
        nepa_autoreleasepool_t * __pool = nepa_autoreleasepool_push();
        {
            NPObject *__nepa_tmp_0 = (NPObject_alloc(&nepa_Game__Player_class, __nepa_sel_alloc));
            Game__Player * p = ((struct nepa_Game__Player_vtable *)__nepa_tmp_0->isa->vtable)->initWithScore_(__nepa_tmp_0, __nepa_sel_initWithScore_, 99);
            printf("[using_basic] Player score: %d\n", ((struct Game__Player *)(p))->score);
            nepa_release(p);
        }
        nepa_autoreleasepool_pop(__pool);
    }
    return 0;
    nepa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nepa_NPObject_vtable nepa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nepa_Game__Player_vtable nepa_Game__Player_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .initWithScore_ = Game__Player_initWithScore_,
};

struct nepa_NPObject_meta_vtable nepa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nepa_Game__Player_meta_vtable nepa_Game__Player_meta_vtable_inst = {
    .class = Game__Player_getClass,
};

NPClass nepa_NPObject_class;
NPClass nepa_Game__Player_class;

void nepa_meta_init(void) {
    nepa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nepa_NPObject_vtable_inst,
        .class_vtable = &nepa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nepa_Game__Player_class = (NPClass){
        .name = "Game__Player",
        .superclass = &nepa_NPObject_class,
        .instance_size = sizeof(struct Game__Player),
        .vtable = &nepa_Game__Player_vtable_inst,
        .class_vtable = &nepa_Game__Player_meta_vtable_inst,
        .protocol_count = 0,
    };
}
