// Generated by galdc
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "gald/runtime.h"


#include <string.h>

struct gald_NFObject_vtable;
struct gald_Foo_vtable;

#define gald_NFObject_vtable_index_init 2
#define gald_NFObject_vtable_index_dealloc 3
#define gald_Foo_vtable_index_init 2

static const SEL __gald_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __gald_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};

typedef struct NFObject NFObject;
typedef struct Foo Foo;



NFObject * NFObject_alloc(NFClass * self, SEL _cmd);
NFObject * NFObject_new(NFClass * self, SEL _cmd);
NFObject * NFObject_init(NFObject * self, SEL _cmd);
void NFObject_dealloc(NFObject * self, SEL _cmd);
NFClass * NFObject_getClass(NFClass * self, SEL _cmd);
NFObject * Foo_init(NFObject * self, SEL _cmd);
NFClass * Foo_getClass(NFClass * self, SEL _cmd);
int main();

extern NFClass gald_NFObject_class;
extern NFClass gald_Foo_class;
void gald_meta_init(void);

// struct NFClass defined in runtime.h
// struct NFObject defined in runtime.h
struct gald_NFObject_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct gald_NFObject_meta_vtable {
    NFObject * (*alloc)(NFClass *, SEL);
    NFObject * (*new)(NFClass *, SEL);
    NFClass * (*class)(NFClass *, SEL);
};
struct Foo {
    struct NFClass *isa;
    uint32_t retain_count;
};
typedef struct Foo Foo;
struct gald_Foo_vtable {
    NFObject * (*init)(NFObject *, SEL);
    void (*dealloc)(NFObject *, SEL);
};
struct gald_Foo_meta_vtable {
    NFClass * (*class)(NFClass *, SEL);
};
NFObject * NFObject_alloc(NFClass * self, SEL _cmd) {
    return gald_alloc(self);
}

NFObject * NFObject_new(NFClass * self, SEL _cmd) {
    NFObject * obj = gald_alloc(self);
    return gald_init(obj);
}

NFObject * NFObject_init(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return gald_init(self);
    }
}

void NFObject_dealloc(NFObject * self, SEL _cmd) {
    struct NFObject * _self = ((struct NFObject *)(self));
    {
        return;
    }
}

NFClass * NFObject_getClass(NFClass * self, SEL _cmd) {
    return &gald_NFObject_class;
}

NFObject * gald_alloc(struct NFClass * cls);
NFObject * gald_init(NFObject * );
NFObject * Foo_init(NFObject * self, SEL _cmd) {
    struct Foo * _self = ((struct Foo *)(self));
    {
        self = NFObject_init(self, __gald_sel_init);
        return self;
    }
}

NFClass * Foo_getClass(NFClass * self, SEL _cmd) {
    return &gald_Foo_class;
}

int main() {
    gald_autoreleasepool_t *__pool = gald_autoreleasepool_push();
    gald_meta_init();
    {
        gald_autoreleasepool_t * __pool = gald_autoreleasepool_push();
        {
            NFObject *__gald_tmp_0 = (NFObject_alloc(&gald_Foo_class, __gald_sel_alloc));
            Foo * f = ((struct gald_Foo_vtable *)__gald_tmp_0->isa->vtable)->init(__gald_tmp_0, __gald_sel_init);
            NFLog((NFString *)gald_stringFromCstr("obj: %s"), f ? [[f description] UTF8String] : "(null)");
            NFLog((NFString *)gald_stringFromCstr("null: %s"), (void *)0 ? [[(void *)0 description] UTF8String] : "(null)");
            gald_release(f);
        }
        gald_autoreleasepool_pop(__pool);
    }
    printf("NFLog %% OK\n");
    return 0;
    gald_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct gald_NFObject_vtable gald_NFObject_vtable_inst = {
    .init = NFObject_init,
    .dealloc = NFObject_dealloc,
};

struct gald_Foo_vtable gald_Foo_vtable_inst = {
    .init = Foo_init,
    .dealloc = NFObject_dealloc,
};

struct gald_NFObject_meta_vtable gald_NFObject_meta_vtable_inst = {
    .alloc = NFObject_alloc,
    .new = NFObject_new,
    .class = NFObject_getClass,
};

struct gald_Foo_meta_vtable gald_Foo_meta_vtable_inst = {
    .class = Foo_getClass,
};

NFClass gald_NFObject_class;
NFClass gald_Foo_class;

void gald_meta_init(void) {
    gald_NFObject_class = (NFClass){
        .name = "NFObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NFObject),
        .vtable = &gald_NFObject_vtable_inst,
        .class_vtable = &gald_NFObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    gald_Foo_class = (NFClass){
        .name = "Foo",
        .superclass = &gald_NFObject_class,
        .instance_size = sizeof(struct Foo),
        .vtable = &gald_Foo_vtable_inst,
        .class_vtable = &gald_Foo_meta_vtable_inst,
        .protocol_count = 0,
    };
}
