// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"
struct nopa_NPObject_vtable;
struct nopa_NPObject_meta_vtable;
struct nopa_Student_vtable;
struct nopa_Student_meta_vtable;

static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nopa_sel_new = {.name = "new", .hash = 0x28999611};
static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_dealloc = {.name = "dealloc", .hash = 0xD9929EB3};
static const SEL __nopa_sel_release = {.name = "release", .hash = 0x1036AE7E};
static const SEL __nopa_sel_retain = {.name = "retain", .hash = 0x88BCC57C};
static const SEL __nopa_sel_grade = {.name = "grade", .hash = 0xBC466E34};
static const SEL __nopa_sel_setGrade_ = {.name = "setGrade_", .hash = 0x286A7EC3};

typedef struct NPObject NPObject;
typedef struct Student Student;

NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
void NPObject_release(NPObject * self, SEL _cmd);
NPObject * NPObject_retain(NPObject * self, SEL _cmd);
int Student_grade(NPObject * self, SEL _cmd);
void Student_setGrade_(NPObject * self, SEL _cmd, int value);
NPObject * nopa_alloc(struct NPClass * cls);
NPObject * nopa_init(NPObject * self);
void nopa_release(NPObject * obj);
NPObject * nopa_retain(NPObject * obj);
int main(void);

NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
NPClass * Student_getClass(NPClass * self, SEL _cmd);

struct nopa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
};
struct nopa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct nopa_Student_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*release)(NPObject *, SEL);
    NPObject * (*retain)(NPObject *, SEL);
    int (*grade)(NPObject *, SEL);
    void (*setGrade_)(NPObject *, SEL, int);
};
struct nopa_Student_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};

struct Student {
    struct NPClass *isa;
    uint32_t retain_count;
    int _grade;
};
typedef struct Student Student;

extern NPClass nopa_NPObject_class;
extern NPClass nopa_Student_class;
void nopa_meta_init(void);

struct nopa_NPObject_vtable nopa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
};

struct nopa_Student_vtable nopa_Student_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .release = NPObject_release,
    .retain = NPObject_retain,
    .grade = Student_grade,
    .setGrade_ = Student_setGrade_,
};

struct nopa_NPObject_meta_vtable nopa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nopa_Student_meta_vtable nopa_Student_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = Student_getClass,
};

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass * Student_getClass(NPClass * self, SEL _cmd) {
    (void)_cmd;
    return self;
}

NPClass nopa_NPObject_class;
NPClass nopa_Student_class;

void nopa_meta_init(void) {
    nopa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nopa_NPObject_vtable_inst,
        .class_vtable = &nopa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Student_class = (NPClass){
        .name = "Student",
        .superclass = &nopa_NPObject_class,
        .instance_size = sizeof(struct Student),
        .vtable = &nopa_Student_vtable_inst,
        .class_vtable = &nopa_Student_meta_vtable_inst,
        .protocol_count = 0,
    };
}
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
  return nopa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
  NPObject * obj = nopa_alloc(self);
  return nopa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return nopa_init(self);
  }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return;
  }
}

void NPObject_release(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    nopa_release(self);
  }
}

NPObject * NPObject_retain(NPObject * self, SEL _cmd) {
  struct NPObject * _self = (struct NPObject *)self;
  {
    return nopa_retain(self);
  }
}

int Student_grade(NPObject * self, SEL _cmd) {
  return ((struct Student *)self)->_grade;
}

void Student_setGrade_(NPObject * self, SEL _cmd, int value) {
  ((struct Student *)self)->_grade = value;
}

NPObject * nopa_alloc(struct NPClass * cls);

NPObject * nopa_init(NPObject * self);

void nopa_release(NPObject * obj);

NPObject * nopa_retain(NPObject * obj);

int main(void) {
  nopa_meta_init();
  NPObject *__nopa_tmp_0 = (NPObject_alloc(&nopa_Student_class, sel_registerName("alloc")));
  Student * s = ((struct nopa_NPObject_vtable *)__nopa_tmp_0->isa->vtable)->init(__nopa_tmp_0, sel_registerName("init"));
  s->_grade = 5;
  printf("Grade: %d\n", ((struct nopa_Student_vtable *)(s)->isa->vtable)->grade(s, sel_registerName("grade")));
  return 0;
}

