[package]
name = "ovicc"
version = "0.1.0"
edition = "2021"

[dependencies]
ovic-cst = { path = "../cst" }
ovic-parser = { path = "../parser" }
ovic-binder = { path = "../binder" }
ovic-elaborator = { path = "../elaborator" }
ovic-codegen = { path = "../codegen" }
ovic-preprocessor = { path = "../preprocessor" }
ovic-symbol = { path = "../symbol" }
ovic-ast = { path = "../ast" }
ovic-cfg = { path = "../cfg" }
ovic-arc = { path = "../arc" }
ovic-async = { path = "../async" }
ovic-eh = { path = "../eh" }
ovic-defer = { path = "../defer" }
ovic-pattern = { path = "../pattern" }
ovic-trace = { path = "../trace" }
ovic-checker = { path = "../checker" }
attrs = { path = "../attrs" }
clap = "4.6.6"
clap_complete = "4.6.9"

[build-dependencies]
cc = "1.0"
