// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"


#include <string.h>

struct nopa_NPObject_vtable;
struct nopa_Student_vtable;

#define nopa_NPObject_vtable_index_init 2
#define nopa_NPObject_vtable_index_dealloc 3

typedef struct NPObject NPObject;
typedef struct Student Student;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
int Student_grade(NPObject * self, SEL _cmd);
void Student_setGrade_(NPObject * self, SEL _cmd, int value);
NPClass * Student_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nopa_NPObject_class;
extern NPClass nopa_Student_class;
void nopa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nopa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nopa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Student {
    struct NPClass *isa;
    uint32_t retain_count;
    int _grade;
};
typedef struct Student Student;
struct nopa_Student_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    int (*grade)(NPObject *, SEL);
    void (*setGrade_)(NPObject *, SEL, int);
};
struct nopa_Student_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nopa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nopa_alloc(self);
    return nopa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nopa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nopa_NPObject_class;
}

NPObject * nopa_alloc(struct NPClass * cls);
NPObject * nopa_init(NPObject * );
int Student_grade(NPObject * self, SEL _cmd) {
    return ((struct Student *)(self))->_grade;
}

void Student_setGrade_(NPObject * self, SEL _cmd, int value) {
    ((struct Student *)(self))->_grade = value;
}

NPClass * Student_getClass(NPClass * self, SEL _cmd) {
    return &nopa_Student_class;
}

int main() {
    nopa_autoreleasepool_t *__pool = nopa_autoreleasepool_push();
    nopa_meta_init();
    return 0;
    nopa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nopa_NPObject_vtable nopa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nopa_Student_vtable nopa_Student_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .grade = Student_grade,
    .setGrade_ = Student_setGrade_,
};

struct nopa_NPObject_meta_vtable nopa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nopa_Student_meta_vtable nopa_Student_meta_vtable_inst = {
    .class = Student_getClass,
};

NPClass nopa_NPObject_class;
NPClass nopa_Student_class;

void nopa_meta_init(void) {
    nopa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nopa_NPObject_vtable_inst,
        .class_vtable = &nopa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Student_class = (NPClass){
        .name = "Student",
        .superclass = &nopa_NPObject_class,
        .instance_size = sizeof(struct Student),
        .vtable = &nopa_Student_vtable_inst,
        .class_vtable = &nopa_Student_meta_vtable_inst,
        .protocol_count = 0,
    };
}
