use std::fmt;

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum TokenKind {
    // Identifiers / Keywords
    Identifier,
    Keyword,

    // Literals
    Integer,
    Float,
    String,
    AtString,
    AtNumber,
    /// `@(expr)` — boxed-expression literal. The checker rewrites it to the
    /// `NFNumber` factory matching the expression's static type.
    AtLParen,
    /// `@'c'` — boxed character literal (`NFNumber`).
    AtChar,
    /// `@YES` / `@NO` / `@true` / `@false` — boxed BOOL literal.
    AtBool,
    Char,
    Bool,

    // Operators
    Plus,
    Minus,
    Star,
    Slash,
    Percent,
    Ampersand,
    Pipe,
    Caret,
    Tilde,
    Exclam,
    Less,
    Greater,
    Assign,
    Comma,
    Dot,
    Semicolon,
    Colon,
    ColonColon,
    LBracket,
    RBracket,
    AtArray,
    LBrace,
    RBrace,
    AtDict,
    LParen,
    RParen,
    Arrow,
    Ellipsis,

    // Compound operators
    PlusAssign,
    MinusAssign,
    StarAssign,
    SlashAssign,
    PercentAssign,
    AndAssign,
    OrAssign,
    XorAssign,
    LShiftAssign,
    RShiftAssign,
    Eq,
    Neq,
    Leq,
    Geq,
    LShift,
    RShift,
    LogicalAnd,
    LogicalOr,
    Incr,
    Decr,
    ArrowStar,
    Question,

    // Preprocessor
    PpHash,
    PpDoubleHash,

    // Special
    Newline,
    Eof,
    Error,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeywordKind {
    AtInterface,
    AtImplementation,
    AtEnd,
    AtProperty,
    AtSynthesize,
    AtDynamic,
    AtSelector,
    AtEncode,
    AtProtocol,
    AtOptional,
    AtRequired,
    AtClass,
    AtTry,
    /// `@await` — suspension-point operator (async/await, route map #4).
    /// `@` because the task-state-machine is a compiler/runtime mechanism
    /// with no C syntax slot; `await` alone stays a plain C identifier.
    AtAwait,
    /// `@defer` — scope-exit execution block (Go-style defer). `@` because C
    /// has no syntax slot for "run this at every exit of my enclosing block";
    /// without it the programmer hand-writes cleanup at every return/break/
    /// throw. See AGENTS.md `@defer` section.
    AtDefer,
    AtCatch,
    AtFinally,
    AtThrow,
    /// `@throws` — trailing declaration annotation ("this method may throw"),
    /// distinct from the `@throw` statement. See AGENTS.md `@throws` section.
    AtThrows,
    AtSynchronized,
    AtAutoreleasepool,
    AtPublic,
    AtPackage,
    AtProtected,
    AtPrivate,
    AtDefs,
    AtNamespace,
    AtEndNamespace,
    AtUsing,
    AtNoArc,
    AtReadwrite,
    AtReadonly,
    AtWeak,
    AtStrong,
    AtAssign,
    AtRetain,
    AtCopy,
    AtNonatomic,
    AtGetter,
    AtSetter,

    Yes,
    No,
    Nil,
    Null,

    Self_,
    Super,
    Cmd,

    Block,
    Weak,
    Strong,
    Autoreleasing,
    UnsafeUnretained,

    Instancetype,
    Id,
    Class,
    Sel,
    Bool,
    Imp,
    NpZone,

    Return,
    If,
    Else,
    Switch,
    Case,
    Default,
    While,
    Do,
    For,
    In,
    Break,
    Continue,
    Goto,
    Sizeof,
    Typeof,
    Struct,
    Union,
    Enum,
    Typedef,

    Void,
    Char,
    Short,
    Int,
    Long,
    Float,
    Double,
    /// C99 `_Complex` — always follows `float`/`double` in a type specifier.
    Complex,
    Signed,
    Unsigned,
    Const,
    Volatile,
    Static,
    Extern,
    Auto,
    Register,
    Inline,
    Restrict,

    Import,
    Include,
    Define,
    Ifdef,
    Ifndef,
    Endif,
    Pragma,
    Elif,
    Undef,

    Asm,

    Extension,
    Alignof,

    None,
}

#[derive(Debug, Clone)]
pub struct Token {
    pub kind: TokenKind,
    pub keyword: KeywordKind,
    pub start: usize,
    pub length: usize,
    pub line: usize,
    pub column: usize,
    pub char_val: u8,
}

impl Token {
    pub fn text<'a>(&self, source: &'a str) -> &'a str {
        &source[self.start..self.start + self.length]
    }
}

impl fmt::Display for TokenKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            TokenKind::Identifier => write!(f, "identifier"),
            TokenKind::Keyword => write!(f, "keyword"),
            TokenKind::Integer => write!(f, "integer"),
            TokenKind::Float => write!(f, "float"),
            TokenKind::String => write!(f, "string"),
            TokenKind::AtString => write!(f, "at-string"),
            TokenKind::AtNumber => write!(f, "at-number"),
            TokenKind::Char => write!(f, "char"),
            TokenKind::Bool => write!(f, "bool"),
            TokenKind::Plus => write!(f, "'+'"),
            TokenKind::Minus => write!(f, "'-'"),
            TokenKind::Star => write!(f, "'*'"),
            TokenKind::Slash => write!(f, "'/'"),
            TokenKind::Percent => write!(f, "'%'"),
            TokenKind::Ampersand => write!(f, "'&'"),
            TokenKind::Pipe => write!(f, "'|'"),
            TokenKind::Caret => write!(f, "'^'"),
            TokenKind::Tilde => write!(f, "'~'"),
            TokenKind::Exclam => write!(f, "'!'"),
            TokenKind::Less => write!(f, "'<'"),
            TokenKind::Greater => write!(f, "'>'"),
            TokenKind::Assign => write!(f, "'='"),
            TokenKind::Comma => write!(f, "','"),
            TokenKind::Dot => write!(f, "'.'"),
            TokenKind::Semicolon => write!(f, "';'"),
            TokenKind::Colon => write!(f, "':'"),
            TokenKind::ColonColon => write!(f, "'::'"),
            TokenKind::LBracket => write!(f, "'['"),
            TokenKind::RBracket => write!(f, "']'"),
            TokenKind::AtArray => write!(f, "'@['"),
            TokenKind::LBrace => write!(f, "'{{'"),
            TokenKind::RBrace => write!(f, "'}}'"),
            TokenKind::AtDict => write!(f, "'@{{'"),
            TokenKind::LParen => write!(f, "'('"),
            TokenKind::RParen => write!(f, "')'"),
            TokenKind::Arrow => write!(f, "'->'"),
            TokenKind::Ellipsis => write!(f, "'...'"),
            TokenKind::PlusAssign => write!(f, "'+='"),
            TokenKind::MinusAssign => write!(f, "'-='"),
            TokenKind::StarAssign => write!(f, "'*='"),
            TokenKind::SlashAssign => write!(f, "'/='"),
            TokenKind::PercentAssign => write!(f, "'%='"),
            TokenKind::AndAssign => write!(f, "'&='"),
            TokenKind::OrAssign => write!(f, "'|='"),
            TokenKind::XorAssign => write!(f, "'^='"),
            TokenKind::LShiftAssign => write!(f, "'<<='"),
            TokenKind::RShiftAssign => write!(f, "'>>='"),
            TokenKind::Eq => write!(f, "'=='"),
            TokenKind::Neq => write!(f, "'!='"),
            TokenKind::Leq => write!(f, "'<='"),
            TokenKind::Geq => write!(f, "'>='"),
            TokenKind::LShift => write!(f, "'<<'"),
            TokenKind::RShift => write!(f, "'>>'"),
            TokenKind::LogicalAnd => write!(f, "'&&'"),
            TokenKind::LogicalOr => write!(f, "'||'"),
            TokenKind::Incr => write!(f, "'++'"),
            TokenKind::Decr => write!(f, "'--'"),
            TokenKind::ArrowStar => write!(f, "'->*'"),
            TokenKind::Question => write!(f, "'?'"),
            TokenKind::PpHash => write!(f, "'#'"),
            TokenKind::PpDoubleHash => write!(f, "'##'"),
            TokenKind::Newline => write!(f, "newline"),
            TokenKind::AtLParen => write!(f, "'@('"),
            TokenKind::AtChar => write!(f, "boxed character literal"),
            TokenKind::AtBool => write!(f, "boxed boolean literal"),
            TokenKind::Eof => write!(f, "EOF"),
            TokenKind::Error => write!(f, "error"),
        }
    }
}