// Generated by nopac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nopa/runtime.h"


#include <string.h>

struct nopa_NPObject_vtable;
struct nopa_Base_vtable;
struct nopa_Derived_vtable;

#define nopa_NPObject_vtable_index_init 2
#define nopa_NPObject_vtable_index_dealloc 3
#define nopa_Base_vtable_index_identify 4
#define nopa_Derived_vtable_index_identify 4

static const SEL __nopa_sel_identify = {.name = "identify", .hash = 0xB570D41D};
static const SEL __nopa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nopa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};

typedef struct NPObject NPObject;
typedef struct Base Base;
typedef struct Derived Derived;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
void Base_identify(NPObject * self, SEL _cmd);
NPClass * Base_getClass(NPClass * self, SEL _cmd);
void Derived_identify(NPObject * self, SEL _cmd);
NPClass * Derived_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nopa_NPObject_class;
extern NPClass nopa_Base_class;
extern NPClass nopa_Derived_class;
void nopa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nopa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nopa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Base {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct Base Base;
struct nopa_Base_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*identify)(NPObject *, SEL);
};
struct nopa_Base_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
struct Derived {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct Derived Derived;
struct nopa_Derived_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*identify)(NPObject *, SEL);
};
struct nopa_Derived_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nopa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nopa_alloc(self);
    return nopa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nopa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nopa_NPObject_class;
}

NPObject * nopa_alloc(struct NPClass * cls);
NPObject * nopa_init(NPObject * );
void Base_identify(NPObject * self, SEL _cmd) {
    struct Base * _self = ((struct Base *)(self));
    {
        printf("Base\n");
    }
}

NPClass * Base_getClass(NPClass * self, SEL _cmd) {
    return &nopa_Base_class;
}

void Derived_identify(NPObject * self, SEL _cmd) {
    struct Derived * _self = ((struct Derived *)(self));
    {
        printf("Derived\n");
        Base_identify(self, __nopa_sel_identify);
    }
}

NPClass * Derived_getClass(NPClass * self, SEL _cmd) {
    return &nopa_Derived_class;
}

int main() {
    nopa_autoreleasepool_t *__pool = nopa_autoreleasepool_push();
    nopa_meta_init();
    NPObject *__nopa_tmp_0 = (NPObject_alloc(&nopa_Derived_class, __nopa_sel_alloc));
    Derived * d = ((struct nopa_NPObject_vtable *)__nopa_tmp_0->isa->vtable)->init(__nopa_tmp_0, __nopa_sel_init);
    ((struct nopa_Derived_vtable *)d->isa->vtable)->identify(d, __nopa_sel_identify);
    return 0;
    nopa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nopa_NPObject_vtable nopa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nopa_Base_vtable nopa_Base_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .identify = Base_identify,
};

struct nopa_Derived_vtable nopa_Derived_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .identify = Derived_identify,
};

struct nopa_NPObject_meta_vtable nopa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nopa_Base_meta_vtable nopa_Base_meta_vtable_inst = {
    .class = Base_getClass,
};

struct nopa_Derived_meta_vtable nopa_Derived_meta_vtable_inst = {
    .class = Derived_getClass,
};

NPClass nopa_NPObject_class;
NPClass nopa_Base_class;
NPClass nopa_Derived_class;

void nopa_meta_init(void) {
    nopa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nopa_NPObject_vtable_inst,
        .class_vtable = &nopa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Base_class = (NPClass){
        .name = "Base",
        .superclass = &nopa_NPObject_class,
        .instance_size = sizeof(struct Base),
        .vtable = &nopa_Base_vtable_inst,
        .class_vtable = &nopa_Base_meta_vtable_inst,
        .protocol_count = 0,
    };
    nopa_Derived_class = (NPClass){
        .name = "Derived",
        .superclass = &nopa_Base_class,
        .instance_size = sizeof(struct Derived),
        .vtable = &nopa_Derived_vtable_inst,
        .class_vtable = &nopa_Derived_meta_vtable_inst,
        .protocol_count = 0,
    };
}
