// Generated by nepac
#include <stdio.h>
#include <stdint.h>
#include <stddef.h>
#include "nepa/runtime.h"


#include <string.h>

struct nepa_NPObject_vtable;
struct nepa_Dog_vtable;

#define nepa_NPObject_vtable_index_init 2
#define nepa_NPObject_vtable_index_dealloc 3
#define nepa_Dog_vtable_index_bark 4

static const SEL __nepa_sel_init = {.name = "init", .hash = 0x16B1D373};
static const SEL __nepa_sel_alloc = {.name = "alloc", .hash = 0xBAB1BB16};
static const SEL __nepa_sel_bark = {.name = "bark", .hash = 0x53DA78E3};

typedef struct NPObject NPObject;
typedef struct Dog Dog;



NPObject * NPObject_alloc(NPClass * self, SEL _cmd);
NPObject * NPObject_new(NPClass * self, SEL _cmd);
NPObject * NPObject_init(NPObject * self, SEL _cmd);
void NPObject_dealloc(NPObject * self, SEL _cmd);
NPClass * NPObject_getClass(NPClass * self, SEL _cmd);
void Dog_bark(NPObject * self, SEL _cmd);
NPClass * Dog_getClass(NPClass * self, SEL _cmd);
int main();

extern NPClass nepa_NPObject_class;
extern NPClass nepa_Dog_class;
void nepa_meta_init(void);

// struct NPClass defined in runtime.h
// struct NPObject defined in runtime.h
struct nepa_NPObject_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
};
struct nepa_NPObject_meta_vtable {
    NPObject * (*alloc)(NPClass *, SEL);
    NPObject * (*new)(NPClass *, SEL);
    NPClass * (*class)(NPClass *, SEL);
};
struct Dog {
    struct NPClass *isa;
    uint32_t retain_count;
};
typedef struct Dog Dog;
struct nepa_Dog_vtable {
    NPObject * (*init)(NPObject *, SEL);
    void (*dealloc)(NPObject *, SEL);
    void (*bark)(NPObject *, SEL);
};
struct nepa_Dog_meta_vtable {
    NPClass * (*class)(NPClass *, SEL);
};
NPObject * NPObject_alloc(NPClass * self, SEL _cmd) {
    return nepa_alloc(self);
}

NPObject * NPObject_new(NPClass * self, SEL _cmd) {
    NPObject * obj = nepa_alloc(self);
    return nepa_init(obj);
}

NPObject * NPObject_init(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return nepa_init(self);
    }
}

void NPObject_dealloc(NPObject * self, SEL _cmd) {
    struct NPObject * _self = ((struct NPObject *)(self));
    {
        return;
    }
}

NPClass * NPObject_getClass(NPClass * self, SEL _cmd) {
    return &nepa_NPObject_class;
}

NPObject * nepa_alloc(struct NPClass * cls);
NPObject * nepa_init(NPObject * );
void Dog_bark(NPObject * self, SEL _cmd) {
    struct Dog * _self = ((struct Dog *)(self));
    {
        printf("Woof!\n");
    }
}

NPClass * Dog_getClass(NPClass * self, SEL _cmd) {
    return &nepa_Dog_class;
}

int main() {
    nepa_autoreleasepool_t *__pool = nepa_autoreleasepool_push();
    nepa_meta_init();
    NPObject *__nepa_tmp_0 = (NPObject_alloc(&nepa_Dog_class, __nepa_sel_alloc));
    Dog * d = ((struct nepa_NPObject_vtable *)__nepa_tmp_0->isa->vtable)->init(__nepa_tmp_0, __nepa_sel_init);
    ((struct nepa_Dog_vtable *)d->isa->vtable)->bark(d, __nepa_sel_bark);
    return 0;
    nepa_autoreleasepool_pop(__pool);
}


// ─── Class metadata ─────────────────────────────────────

struct nepa_NPObject_vtable nepa_NPObject_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
};

struct nepa_Dog_vtable nepa_Dog_vtable_inst = {
    .init = NPObject_init,
    .dealloc = NPObject_dealloc,
    .bark = Dog_bark,
};

struct nepa_NPObject_meta_vtable nepa_NPObject_meta_vtable_inst = {
    .alloc = NPObject_alloc,
    .new = NPObject_new,
    .class = NPObject_getClass,
};

struct nepa_Dog_meta_vtable nepa_Dog_meta_vtable_inst = {
    .class = Dog_getClass,
};

NPClass nepa_NPObject_class;
NPClass nepa_Dog_class;

void nepa_meta_init(void) {
    nepa_NPObject_class = (NPClass){
        .name = "NPObject",
        .superclass = NULL,
        .instance_size = sizeof(struct NPObject),
        .vtable = &nepa_NPObject_vtable_inst,
        .class_vtable = &nepa_NPObject_meta_vtable_inst,
        .protocol_count = 0,
    };
    nepa_Dog_class = (NPClass){
        .name = "Dog",
        .superclass = &nepa_NPObject_class,
        .instance_size = sizeof(struct Dog),
        .vtable = &nepa_Dog_vtable_inst,
        .class_vtable = &nepa_Dog_meta_vtable_inst,
        .protocol_count = 0,
    };
}
